// @ts-nocheck
// Recetas adicionales: cenas
export const CENAS=[
/* ============================================================ 1. PESCADO / POLLO AL HORNO ============================================================ */
{id:'pescado_horno',meal:'Cena',cuisine:'Mediterránea',img:null,
 title:'Pescado blanco o pollo al horno con limón, tomate cherry y judías verdes, con puré de camote',
 sub:'Una bandeja, sabores frescos de limón, ajo y hierbas, y un puré de camote suave y cremoso. Ligera, fácil de masticar y lista en 50 minutos.',
 prep:20,cook:30,total:50,base:4,
 variants:[
  {id:'pollo',label:'Pechuga de pollo',sub:'Sin mariscos',kcal:480,p:39,c:49,f:14,d:'Pechuga aplanada a 1.5 cm para que quede jugosa y se cocine pareja.'},
  {id:'pescado',label:'Pescado blanco',sub:'Con pescado',sea:1,kcal:445,p:35,c:49,f:12,d:'Mahi-mahi, tilapia o bacalao en filetes de 2 cm de grosor.'}],
 groups:[
  {g:'Proteína y marinada',items:[
   ['prot',1.25,'lb',565,'g','pechuga de pollo (2 pechugas medianas)','pechuga de pollo','Ábrela por la mitad en horizontal (mariposa) o córtala en 4 filetes y aplánalos con la palma hasta 1.5 cm (⅝ in) de grosor.',['pollo'],.25],
   ['prot',1.25,'lb',565,'g','filetes de pescado blanco (mahi-mahi, tilapia o bacalao)','pescado blanco','De unos 140 g (5 oz) cada uno y 2 cm (¾ in) de grosor. Pide que los desespinen y revisa con los dedos que no queden espinas.',['pescado'],.25],
   ['aceite_m',1,'cda',15,'ml','aceite de oliva extra virgen (para la marinada)','aceite de oliva','Mide con cuchara.'],
   ['limon',2,'',120,'g','limón~es amarillo~s','limones','Ralla la cáscara antes de exprimirlos. Evita la parte blanca: amarga.',null,1],
   ['ajo',3,'',9,'g','diente~s de ajo','ajo','Picados muy finos o rallados.',null,1],
   ['oregano',1,'cdta',1.5,'g','orégano seco','orégano'],
   ['paprika',.5,'cdta',1.2,'g','pimentón dulce','pimentón dulce'],
   ['sal_m',.75,'cdta',4.5,'g','sal fina','sal fina','Para sazonar la proteína y las verduras.'],
   ['pimienta',.25,'cdta',.5,'g','pimienta negra recién molida','pimienta negra']]},
  {g:'Verduras de la bandeja',items:[
   ['cherry',2,'taza',300,'g','tomate cherry','tomate cherry','Enteros, con un pequeño corte para que no exploten.'],
   ['judias',1,'lb',450,'g','judías verdes (ejotes)','judías verdes','Sin los extremos duros. Si usas espárragos, quita el tercio inferior del tallo.'],
   ['aceite_v',1,'cda',15,'ml','aceite de oliva extra virgen (para las verduras)','aceite de oliva'],
   ['tomillo',1,'cda',3,'g','hojas de tomillo fresco (o 1 cdta. seco)','tomillo','Sin los tallos leñosos.']]},
  {g:'Puré de camote',items:[
   ['camote',1.5,'lb',680,'g','camote (batata) naranja','camote','Pelado y en cubos de 3 cm (1¼ in) para que hierva parejo.'],
   ['agua_c',4,'taza',950,'ml','agua para hervir','agua','Debe cubrir los cubos por 2 cm.'],
   ['sal_c',.25,'cdta',1.5,'g','sal fina','sal fina'],
   ['aceite_p',1,'cda',15,'ml','aceite de oliva extra virgen (para el puré)','aceite de oliva'],
   ['leche',.25,'taza',60,'ml','leche o bebida vegetal sin azúcar','leche','Tibia. Ajusta: más si lo quieres más suave.']]},
  {g:'Para servir',items:[
   ['limon_s',1,'',60,'g','limón amarillo (en gajos)','limón en gajos','Para exprimir sobre el plato.',null,1],
   ['perejil',.25,'taza',15,'g','perejil fresco picado','perejil','Hojas sin tallos gruesos.']]}],
 steps:[
  {t:'Precalienta el horno y prepara la marinada',time:'10 min',
   x:`Coloca una rejilla en el centro del horno y precalienta a 220 °C (425 °F). Forra una bandeja grande de hornear con papel pergamino. Ralla la cáscara de {limon:1/2} sobre un bowl y exprime su jugo (unas 4 cucharadas). Agrega {aceite_m}, {ajo}, {oregano}, {paprika}, {sal_m:1/2} y {pimienta}. Mezcla con un tenedor hasta que parezca una pasta suelta y aromática.`,
   cue:'La marinada huele intensamente a limón y ajo, con color dorado verdoso.'},
  {t:v=>v==='pollo'?'Aplana y marina el pollo':'Seca y marina el pescado',time:'15 min',timer:{d:900,pescado:600},
   x:v=>v==='pollo'
    ?`Pon {prot} entre dos hojas de papel pergamino y golpea suavemente con un rodillo o el fondo de una sartén hasta que todo tenga 1.5 cm (⅝ in) de grosor. Esto es lo que lo hace cocinarse parejo y quedar jugoso. Sécalo con papel de cocina y cúbrelo con la marinada por ambos lados. Déjalo reposar 15 minutos fuera de la nevera mientras sigues con los pasos 3 y 4.`
    :`Seca muy bien {prot} con papel de cocina por ambos lados: la humedad impide que se hornee bien y lo vuelve aguado. Colócalo sobre la bandeja y cúbrelo con la marinada. Déjalo solo 10 minutos: el limón en exceso “cocina” el pescado y lo vuelve harinoso. Mientras tanto sigue con los pasos 3 y 4.`,
   cue:'La proteína se ve brillante y bien cubierta, sin charcos de marinada alrededor.'},
  {t:'Pon el camote a hervir',time:'18 min',timer:1080,
   x:`Pela {camote} y córtalo en cubos de 3 cm (1¼ in). Ponlos en una olla mediana con {agua_c} y {sal_c}. Lleva a hervor a fuego alto, baja a fuego medio y cocina 15–18 minutos, hasta que un cuchillo entre sin resistencia. Cuélalos y devuélvelos a la olla caliente, sin tapa.`,
   cue:'Los cubos se deshacen al presionarlos con un tenedor y se ven brillantes.'},
  {t:'Hornea primero las verduras',time:'10 min',timer:600,
   x:`Mientras el camote hierve, extiende {judias} y {cherry} en una segunda bandeja, mezcla con {aceite_v}, {tomillo} y {sal_m:1/4} y distribúyelas en una sola capa. Hornea 8–10 minutos, hasta que las judías empiecen a arrugarse y los tomates se abran un poco.`,
   cue:'Las judías verdes tienen los bordes tostados y los tomates están blandos y jugosos.',
   warn:'No amontones la bandeja: si las verduras se tocan demasiado, se cuecen al vapor en vez de dorarse.'},
  {t:v=>v==='pollo'?'Agrega el pollo y hornea':'Agrega el pescado y hornea',time:v=>v==='pollo'?'18–20 min':'10–12 min',timer:{d:1140,pescado:660},
   x:v=>v==='pollo'
    ?`Saca la bandeja de verduras, empújalas a un lado y acomoda {prot} en la bandeja con papel pergamino, o junto a las verduras en la misma bandeja si cabe en una sola capa. Hornea 18–20 minutos, hasta que el centro de la parte más gruesa marque 74 °C (165 °F) en un termómetro de cocina. Si no tienes termómetro, corta la pieza más gruesa: el jugo debe salir transparente y el centro, blanco.`
    :`Acomoda {prot} con la piel (si tiene) hacia abajo, en una sola capa, entre las verduras o en una bandeja aparte. Hornea 10–12 minutos, hasta que el centro marque 63 °C (145 °F) y la carne se vea opaca. Para la adulta mayor y para quien tenga dudas, un minuto más está bien, siempre que no se seque.`,
   cue:v=>v==='pollo'?'Superficie dorada, jugo transparente al pinchar y carne firme pero elástica al presionar.':'La carne pasa de translúcida a blanca y opaca, y se separa en lascas con un tenedor.',
   warn:v=>v==='pollo'?'Seguridad: el pollo debe llegar a 74 °C (165 °F) en el centro. Nunca lo sirvas rosado.':'Seguridad: el pescado debe llegar a 63 °C (145 °F). Si queda translúcido en el centro, devuélvelo 2 minutos al horno.'},
  {t:'Haz el puré de camote',time:'5 min',timer:300,
   x:`Con los cubos aún calientes en la olla, agrega {aceite_p} y {leche} tibia. Aplasta con un prensapuré o un tenedor grande, y luego bate con una cuchara de madera 1 minuto, hasta que quede sedoso. Prueba y ajusta la sal. Si queda espeso, añade 1–2 cucharadas más de leche.`,
   cue:'El puré cae de la cuchara en cinta lenta, sin grumos, y se ve brillante.'},
  {t:'Reposa y sirve',time:'5 min',timer:180,
   x:`Deja reposar la proteína 3 minutos fuera del horno para que se reabsorban los jugos. Reparte el puré en {N} platos, coloca encima una porción de proteína y las verduras. Termina con {perejil}, un chorrito de jugo de {limon_s} y los gajos al lado.`}],
 tools:'2 bandejas de hornear, papel pergamino, olla mediana, termómetro de cocina, tabla y cuchillo, rallador fino, prensapuré o tenedor grande.',
 tips:[
  ['Para la adulta mayor','Con el pollo aplanado o el pescado, la textura es muy tierna. Revisa el pescado una vez más con los dedos antes de servirle, por si queda alguna espina.'],
  ['Para el que entrena fuerte','Sirve media porción más de proteína (2 filetes) y suma ½ taza más de puré. Es una forma sencilla de subir proteína y carbohidrato en la cena.'],
  ['Familias mixtas','Haz la bandeja con pollo para todos y hornea el pescado en un papel aparte para quien lo prefiera. Las verduras y el puré son comunes.']],
 store:'Refrigerado en recipientes separados dura 3 días (el pescado, 2 días). Recalienta el pollo y el puré tapados en microondas 1–2 minutos a potencia media; el pescado, 1 minuto, o se seca. Las verduras vuelven a la vida en una sartén seca 2 minutos.',
 swaps:['Judías verdes → espárragos (hornéalos solo 6–8 min), brócoli o calabacín en medias lunas.','Camote → papa amarilla o calabaza butternut en puré.','Limón → naranja agria o lima, para un toque más latino.','Pescado blanco → salmón (suma grasa buena y calorías) o pechuga de pavo.']},

/* ============================================================ 2. CHILI DE PAVO / TRES FRIJOLES ============================================================ */
{id:'chili_pavo',meal:'Cena',cuisine:'Americana tex-mex',img:null,
 title:'Chili de frijoles con pavo o vegetariano de tres frijoles, con arroz y aguacate',
 sub:'Un guiso espeso y reconfortante con pimientos, comino y chile suave. Se cocina una sola vez y rinde para el día siguiente.',
 prep:15,cook:55,total:70,base:4,
 variants:[
  {id:'pavo',label:'Con pavo',sub:'Sin mariscos',kcal:545,p:41,c:60,f:16,d:'Pavo molido magro (93 %) con dos tipos de frijoles.'},
  {id:'vegetariano',label:'Tres frijoles',sub:'Vegetariana',kcal:495,p:24,c:73,f:12,d:'Frijoles rojos, negros y pintos. Menos proteína que la versión con pavo.'}],
 groups:[
  {g:'Base del chili',items:[
   ['aceite',1,'cda',15,'ml','aceite de oliva','aceite de oliva','Mide con cuchara.'],
   ['cebolla',1,'',200,'g','cebolla amarilla grande','cebolla','En cubitos de 8 mm (⅜ in).',null,1],
   ['pimiento',2,'',300,'g','pimiento~s (1 rojo y 1 verde)','pimientos','En cubitos de 1 cm (⅜ in). Sin semillas.',null,1],
   ['zanahoria',1,'',80,'g','zanahoria mediana rallada','zanahoria','Rallada fina: da dulzor y se deshace.',null,1],
   ['ajo',4,'',12,'g','diente~s de ajo','ajo','Picado muy fino.',null,1],
   ['pavo',1,'lb',454,'g','pavo molido magro (93 %)','pavo molido','Retira del refrigerador 10 minutos antes.',['pavo'],.25]]},
  {g:'Especias y líquidos',items:[
   ['comino',2,'cdta',4,'g','comino molido','comino'],
   ['chile',1,'cda',8,'g','chile en polvo suave','chile en polvo','Elige uno suave (no “picante”). Puedes subir con hojuelas al servir.'],
   ['pimenton',1,'cdta',2.5,'g','pimentón ahumado','pimentón ahumado'],
   ['oregano',1,'cdta',1,'g','orégano seco','orégano'],
   ['pasta',2,'cda',32,'g','pasta de tomate','pasta de tomate'],
   ['tomate',2,'taza',425,'g','tomate triturado (1 lata de 15 oz)','tomate triturado','Sin azúcar añadida.'],
   ['caldo',1,'taza',240,'ml','caldo de pollo bajo en sodio','caldo de pollo','',['pavo']],
   ['caldo',1,'taza',240,'ml','caldo de vegetales bajo en sodio','caldo de vegetales','',['vegetariano']],
   ['sal',1,'cdta',6,'g','sal fina','sal fina','Los frijoles enlatados ya traen sal: empieza con la mitad y ajusta al final.']]},
  {g:'Frijoles',items:[
   ['fr_rojo',1,'',240,'g','lata~s de frijoles rojos (15 oz), escurrida~s y enjuagada~s','lata~s de frijoles rojos','Escúrrelos y enjuágalos bajo el chorro 30 segundos: eliminan casi la mitad del sodio.',null,1],
   ['fr_negro',1,'',240,'g','lata~s de frijoles negros (15 oz), escurrida~s y enjuagada~s','lata~s de frijoles negros','Mismo proceso.',null,1],
   ['fr_pinto',1,'',240,'g','lata~s de frijoles pintos (15 oz), escurrida~s y enjuagada~s','lata~s de frijoles pintos','Dan cremosidad al guiso.',['vegetariano'],1]]},
  {g:'Arroz',items:[
   ['arroz',.5,'taza',95,'g','arroz blanco de grano largo','arroz','Enjuágalo hasta que el agua salga casi clara.'],
   ['agua_a',1,'taza',240,'ml','agua','agua'],
   ['sal_a',.25,'cdta',1.5,'g','sal fina','sal fina']]},
  {g:'Para servir',items:[
   ['aguacate',.5,'',100,'g','aguacate Hass maduro','aguacate~s','Cortado en cubos de 1.5 cm justo antes de servir.',['pavo']],
   ['aguacate',1,'',200,'g','aguacate Hass maduro','aguacate~s','Cortado en cubos de 1.5 cm justo antes de servir.',['vegetariano']],
   ['yogur',.5,'taza',120,'g','yogur griego natural sin azúcar','yogur griego','Sustituye a la crema agria con mucha menos grasa.'],
   ['cilantro',.25,'taza',15,'g','cilantro fresco picado','cilantro'],
   ['lima',1,'',60,'g','limón verde (lima)','lima','Su jugo da frescura al final.',null,1]]}],
 steps:[
  {t:'Prepara todo',time:'12 min',
   x:`Pica {cebolla} y {pimiento} en cubitos parejos, ralla {zanahoria} y pica {ajo}. Abre las latas de frijoles ({fr_rojo} y {fr_negro}), escúrrelos en un colador y enjuágalos bajo agua fría. Mide {comino}, {chile}, {pimenton} y {oregano} en un platito para tenerlos listos.`,
   add:{vegetariano:'Añade al colador {fr_pinto}.'},
   cue:'Los frijoles escurridos ya no sueltan líquido espeso y las verduras están en cubos parejos.'},
  {t:'Pon el arroz a cocer',time:'25 min, sin atención',timer:1500,
   x:`Enjuaga {arroz} 30 segundos en un colador. Colócalo en una olla pequeña con tapa, con {agua_a} y {sal_a}. Hierve a fuego alto; cuando rompa el hervor, baja al mínimo, tapa y cocina 15 minutos sin destapar. Apaga y deja tapado 10 minutos más. Esponja con un tenedor.`,
   cue:'Granos hinchados, sueltos, sin agua en el fondo.'},
  {t:'Sofríe cebolla, pimientos y zanahoria',time:'7 min',timer:420,
   x:`En una olla grande o cacerola de fondo grueso (4–5 L / 4 qt) calienta {aceite} a fuego medio durante 1 minuto. Agrega la cebolla, los pimientos y la zanahoria con {sal:1/2}. Cocina 6–7 minutos, moviendo cada minuto, hasta que la cebolla esté translúcida y los pimientos blandos.`,
   cue:'La cebolla pierde el color blanco y se ve brillante; las verduras huelen dulces, no quemadas.'},
  {t:'Dora el pavo',time:'7 min',v:['pavo'],timer:420,
   x:`Sube el fuego a medio-alto y agrega {pavo} en trozos. Deshazlo con una cuchara de madera en pedazos pequeños y déjalo 2 minutos sin mover, para que se dore; revuelve y cocina 4–5 minutos más, hasta que no quede nada rosado.`,
   cue:'Granitos separados, dorados por los bordes, sin líquido rosado en el fondo.',
   warn:'Seguridad: la carne molida de pavo debe llegar a 74 °C (165 °F). Si hay mucho líquido, deja que se evapore antes de seguir.'},
  {t:'Tuesta las especias',time:'2 min',timer:90,
   x:`Baja a fuego medio. Agrega {ajo}, {comino}, {chile}, {pimenton}, {oregano} y {pasta}. Revuelve constantemente 60–90 segundos, hasta que la pasta se oscurezca un poco y el olor se vuelva intenso y ahumado. Si se pega, añade 1 cucharada de agua.`,
   cue:'Huele a especias tostadas y la pasta de tomate pasa de rojo vivo a rojo ladrillo.',
   warn:'Si el ajo o las especias se queman y huelen amargas, añade un poco de agua rápido: no dejes que se oscurezcan.'},
  {t:'Agrega líquidos y frijoles, y cuece a fuego lento',time:'25–30 min',timer:1650,
   x:v=>`Vierte {tomate} y {caldo}, raspando el fondo para despegar lo dorado. Incorpora ${v==='pavo'?'{fr_rojo} y {fr_negro}':'{fr_rojo}, {fr_negro} y {fr_pinto}'}. Lleva a hervor suave, baja a fuego bajo, tapa parcialmente y cocina 25–30 minutos, moviendo cada 5 minutos.`,
   cue:'Pequeñas burbujas lentas y un guiso que cubre la cuchara sin gotear rápido.',
   warn:'Si se pega abajo, baja el fuego y agrega ¼ de taza (60 ml) de agua.'},
  {t:'Espesa y ajusta el sabor',time:'5 min',timer:300,
   x:`Con el dorso de una cuchara de madera, aplasta una cuarta parte de los frijoles contra la pared de la olla: así el chili se espesa de forma natural. Cocina 5 minutos más sin tapa. Prueba y ajusta: más sal si le falta, más comino si quieres más cuerpo, un chorrito de jugo de {lima:1/2} para despertar los sabores.`,
   cue:'Al pasar la cuchara por el fondo, el surco tarda 2–3 segundos en cerrarse.'},
  {t:'Sirve',time:'5 min',
   x:`Esponja el arroz y sirve ½ taza (95 g) en cada plato para {N} porciones. Reparte el chili sobre el arroz. Termina con {aguacate} en cubos, cucharadas de {yogur}, {cilantro} y el jugo de {lima:1/2}.`}],
 tools:'Olla grande de fondo grueso (4–5 L / 4 qt), olla pequeña con tapa, cuchara de madera, colador, tabla y cuchillo, tazas medidoras.',
 tips:[
  ['Mejor al día siguiente','El chili reposa y gana sabor. Si puedes, prepáralo la víspera: los sabores se integran y queda más espeso.'],
  ['Picante a gusto','Cocina con chile suave y deja hojuelas, salsa picante o jalapeño picado en la mesa. Para la adulta mayor, evita el picante y sirve el aguacate bien maduro, fácil de masticar.'],
  ['Más proteína','En la versión vegetariana, sirve con huevo duro picado o suma una cucharada extra de yogur griego. Para el que entrena fuerte, ½ taza más de arroz y una porción extra de chili.']],
 store:'Refrigerado en recipiente tapado dura 4 días; congelado, hasta 3 meses (sin aguacate ni yogur). Recalienta en olla con 2–3 cucharadas de agua, a fuego medio, 5 minutos; o en microondas tapado 2–3 minutos, moviendo a la mitad.',
 swaps:['Pavo molido → pollo molido o pechuga de pollo desmenuzada.','Arroz → tortilla de maíz tostada o quinoa cocida.','Pasta de tomate → 2 cucharadas de salsa de tomate natural.','Caldo → agua con una pizca extra de sal y comino.']},

/* ============================================================ 3. POLLO AL LIMÓN ROSTIZADO ============================================================ */
{id:'pollo_limon_rostizado',meal:'Cena',cuisine:'Mediterránea latina',img:null,
 title:'Pollo asado al limón y hierbas con verduras rostizadas y papitas',
 sub:'Pollo jugoso con limón, ajo y orégano, acompañado de papitas doradas y verduras de colores. Dos bandejas, sin vigilar mucho.',
 prep:20,cook:40,total:60,base:4,
 variants:[
  {id:'pechuga',label:'Pechuga',sub:'Sin mariscos',kcal:450,p:44,c:34,f:15,d:'Pechuga aplanada a 2 cm de grosor para que se cocine pareja.'},
  {id:'muslo',label:'Muslo deshuesado',sub:'Sin mariscos',kcal:445,p:38,c:34,f:17,d:'Muslo deshuesado y sin piel: más tierno y jugoso, ideal para la adulta mayor.'}],
 groups:[
  {g:'Pollo y marinada',items:[
   ['prot',1.5,'lb',680,'g','pechuga de pollo (2 pechugas grandes)','pechuga de pollo','Ábrela por la mitad en horizontal (mariposa) para dejarla de 2 cm (¾ in) de grosor.',['pechuga'],.25],
   ['prot',1.5,'lb',680,'g','muslos de pollo deshuesados y sin piel','muslos de pollo','Retira el exceso de grasa. Aplánalos con la palma para que midan 2 cm (¾ in) parejos.',['muslo'],.25],
   ['aceite_m',1,'cda',15,'ml','aceite de oliva extra virgen (marinada)','aceite de oliva'],
   ['limon',2,'',120,'g','limón~es amarillo~s','limones','Ralla la cáscara antes de exprimirlos.',null,1],
   ['ajo',4,'',12,'g','diente~s de ajo','ajo','Picados o rallados.',null,1],
   ['oregano',2,'cdta',3,'g','orégano seco','orégano'],
   ['tomillo',1,'cda',3,'g','hojas de tomillo fresco (o 1 cdta. seco)','tomillo'],
   ['mostaza',1,'cda',15,'g','mostaza de Dijon','mostaza Dijon','Une la marinada y ayuda a dorar.'],
   ['paprika',1,'cdta',2.5,'g','pimentón dulce','pimentón dulce'],
   ['sal_m',1,'cdta',6,'g','sal fina','sal fina','La mitad para el pollo y la mitad para las verduras.'],
   ['pimienta',.5,'cdta',1,'g','pimienta negra recién molida','pimienta negra']]},
  {g:'Verduras y papitas',items:[
   ['papitas',1,'lb',454,'g','papitas pequeñas (criollas o cambray)','papitas','Cortadas por la mitad; si son más grandes que un huevo, en cuartos.'],
   ['zanahoria',3,'',240,'g','zanahoria~s medianas','zanahorias','En medias lunas de 1 cm (⅜ in).',null,1],
   ['calabacin',2,'',400,'g','calabacín~es (zucchini) mediano~s','calabacines','En rodajas gruesas de 1.5 cm (⅝ in).',null,1],
   ['pimiento',1,'',200,'g','pimiento rojo grande','pimiento rojo','En tiras de 2 cm (¾ in).',null,1],
   ['cebolla',1,'',150,'g','cebolla morada','cebolla morada','En gajos de 2 cm (¾ in).',null,1],
   ['aceite_v',2,'cda',30,'ml','aceite de oliva extra virgen (verduras)','aceite de oliva']]},
  {g:'Para servir',items:[
   ['limon_s',1,'',60,'g','limón amarillo','limón','Exprime al final.',null,1],
   ['perejil',.25,'taza',15,'g','perejil fresco picado','perejil']]}],
 steps:[
  {t:'Precalienta y prepara la marinada',time:'8 min',
   x:`Precalienta el horno a 220 °C (425 °F) con una rejilla en el centro y otra en la parte inferior. Ralla la cáscara de {limon:1/2} en un bowl y exprime su jugo. Añade {aceite_m}, {ajo}, {oregano}, {tomillo}, {mostaza}, {paprika}, {sal_m:1/2} y {pimienta}. Bate con un tenedor hasta formar una crema espesa y fragante.`,
   cue:'La marinada se ve homogénea, amarilla con motas de hierbas, y huele a limón y ajo.'},
  {t:v=>v==='pechuga'?'Aplana y marina la pechuga':'Prepara y marina el muslo',time:'20 min',timer:1200,
   x:v=>v==='pechuga'
    ?`Abre {prot} por la mitad en horizontal con un cuchillo afilado, con la mano plana sobre la pieza. Cada filete debe quedar de 2 cm (¾ in) de grosor. Sécalos con papel de cocina y úntalos con la marinada por ambos lados. Reposa 20 minutos fuera de la nevera mientras preparas las verduras; más tiempo en el refrigerador el limón la vuelve harinosa.`
    :`Recorta la grasa visible de {prot} y aplánalos con la palma hasta que midan 2 cm (¾ in). Sécalos con papel y úntalos con la marinada por ambos lados. Reposa 20 minutos fuera de la nevera mientras preparas las verduras. Los muslos aguantan bien una marinada más larga: hasta 2 horas en la nevera.`,
   cue:'Cada pieza queda cubierta de una capa pareja de hierbas.'},
  {t:'Corta y sazona las verduras',time:'12 min',
   x:`Corta {papitas}, {zanahoria}, {calabacin}, {pimiento} y {cebolla} como se indica en la lista. Mezcla las papitas y las zanahorias con {aceite_v:1/2} y {sal_m:1/4} en un bowl grande. Reserva aparte el calabacín, el pimiento y la cebolla, que entran más tarde.`,
   cue:'Piezas parejas, con una película fina de aceite y sin charcos.'},
  {t:'Hornea primero las papitas y las zanahorias',time:'15 min',timer:900,
   x:`Forra una bandeja grande con papel pergamino y extiende las papitas con el lado cortado hacia abajo, junto a las zanahorias, sin que se toquen. Hornea 15 minutos en la rejilla inferior, hasta que empiecen a dorarse por debajo.`,
   cue:'La base de las papitas se ve dorada y se despega sin romperse.',
   warn:'No amontones la bandeja: si hace falta, usa dos.'},
  {t:'Agrega el resto de las verduras y el pollo',time:v=>v==='pechuga'?'20–22 min':'22–25 min',timer:{d:1260,muslo:1440},
   x:`Saca la bandeja, agrega {calabacin}, {pimiento} y {cebolla} mezclados con el aceite restante ({aceite_v:1/2}) y {sal_m:1/4}, y devuélvela al horno en la rejilla inferior. En otra bandeja con papel pergamino pon {prot} y hornéala en la rejilla central. Hornea hasta que el pollo marque 74 °C (165 °F) en la parte más gruesa.`,
   cue:'Pollo dorado en los bordes, jugo transparente y verduras con bordes tostados.',
   warn:'Seguridad: el pollo debe llegar a 74 °C (165 °F). Si no tienes termómetro, corta el trozo más grueso: no debe haber nada rosado ni jugo turbio.'},
  {t:'Deja reposar el pollo',time:'5 min',timer:300,
   x:`Saca el pollo y déjalo reposar 5 minutos sobre una tabla, ligeramente cubierto con papel aluminio. En ese tiempo los jugos se reparten y la carne se mantiene tierna al cortar. Mientras, comprueba que las papitas se pinchan fácilmente con un tenedor; si no, devuelve la bandeja 3–5 minutos al horno.`,
   cue:'Al cortar, el jugo es transparente y la carne se ve blanca (pechuga) o beige oscura (muslo), sin zonas rosadas.'},
  {t:'Termina y sirve',time:'5 min',
   x:`Corta el pollo en láminas de 1 cm (⅜ in) contra la fibra. Reparte las verduras y las papitas en {N} platos y coloca el pollo encima. Termina con el jugo de {limon_s} y {perejil}. Para la adulta mayor, corta el pollo en trozos pequeños y sirve las verduras bien blandas.`}],
 tools:'2 bandejas de hornear con papel pergamino, bowl grande, tabla y cuchillo afilado, rallador fino, termómetro de cocina, papel aluminio.',
 tips:[
  ['Papitas bien doradas','Sécalas muy bien tras lavarlas y colócalas con el corte hacia abajo en la bandeja: se doran más y quedan crujientes por fuera, cremosas por dentro.'],
  ['Pechuga jugosa','Aplanarla a 2 cm y respetar el reposo de 5 minutos hace más diferencia que cualquier marinada. No la hornees de más: pasa de jugosa a seca en 2 minutos.'],
  ['Para la adulta mayor','Con el muslo deshuesado la carne es más tierna y fácil de masticar. Cocina las verduras 5 minutos más para que queden suaves.']],
 store:'Refrigerado en recipiente tapado dura 4 días. Recalienta el pollo en microondas 1–2 minutos a potencia media con una cucharada de agua, o envuelto en papel aluminio en el horno a 160 °C (325 °F) por 10 minutos. Las verduras recuperan textura en sartén seca 3 minutos.',
 swaps:['Papitas → camote en cubos de 3 cm (hornéalo igual).','Calabacín → ejotes o brócoli (agrégalos en el mismo momento).','Limón → naranja agria para un sabor más latino.','Orégano y tomillo → romero fresco picado fino.']},

/* ============================================================ 4. LOMO SALTADO LIGHT ============================================================ */
{id:'lomo_saltado_light',meal:'Cena',cuisine:'Peruana',img:null,
 title:'Lomo saltado ligero de res, pollo o camarones con papas al horno y arroz',
 sub:'El clásico peruano, más ligero: papas al horno en vez de fritas, cebolla y tomate crujientes y un fondo de soya y vinagre.',
 prep:25,cook:40,total:65,base:4,
 variants:[
  {id:'res',label:'Res magra',sub:'Sin mariscos',kcal:500,p:36,c:57,f:14,d:'Lomo fino o solomillo magro, en tiras finas.'},
  {id:'pollo',label:'Pollo',sub:'Sin mariscos',kcal:490,p:39,c:57,f:12,d:'Pechuga en tiras de 1 cm.'},
  {id:'camarones',label:'Camarones',sub:'Con mariscos',sea:1,kcal:450,p:35,c:57,f:9,d:'Camarones grandes, cocción de 2 minutos.'}],
 groups:[
  {g:'Proteína y marinada',items:[
   ['prot',1.25,'lb',565,'g','lomo fino o solomillo de res magro','res magra','Sin grasa visible. En tiras de 1 cm × 6 cm (⅜ × 2½ in) cortadas contra la fibra. Si la congelas 20 minutos, cortas más fino.',['res'],.25],
   ['prot',1.25,'lb',565,'g','pechuga de pollo','pollo','En tiras de 1 cm × 6 cm (⅜ × 2½ in) contra la fibra.',['pollo'],.25],
   ['prot',1.25,'lb',565,'g','camarones grandes, pelados y desvenados','camarones','Bien secos con papel de cocina.',['camarones'],.25],
   ['soya_m',1,'cda',15,'ml','salsa de soya baja en sodio (marinada)','soya'],
   ['comino',.5,'cdta',1,'g','comino molido','comino'],
   ['pimienta',.5,'cdta',1,'g','pimienta negra','pimienta negra']]},
  {g:'Papas al horno',items:[
   ['papa',1,'lb',454,'g','papas amarillas o Yukon Gold','papas','En bastones de 1.5 cm (⅝ in) de grosor, con piel bien lavada.'],
   ['aceite_p',1,'cda',15,'ml','aceite de oliva','aceite de oliva (papas)'],
   ['sal_p',.5,'cdta',3,'g','sal fina','sal fina (papas)']]},
  {g:'Vegetales y salsa',items:[
   ['cebolla',2,'',300,'g','cebolla~s roja~s','cebollas rojas','En gajos gruesos de 1.5 cm (⅝ in), separa las capas.',null,1],
   ['tomate',2,'',300,'g','tomate~s romero (pera) firme~s','tomates','En gajos gruesos; quita las semillas y la pulpa aguada con la cuchara.',null,1],
   ['pimiento',1,'',200,'g','pimiento rojo o amarillo','pimiento','En tiras de 1.5 cm (⅝ in).',null,1],
   ['aji',1,'cda',15,'g','pasta de ají amarillo (opcional)','ají amarillo','Da el sabor peruano. Si no la consigues, omite o usa ½ cdta. de pimentón.'],
   ['ajo',4,'',12,'g','diente~s de ajo','ajo','Picados finos.',null,1],
   ['soya',3,'cda',45,'ml','salsa de soya baja en sodio','soya'],
   ['vinagre',2,'cda',30,'ml','vinagre de vino tinto','vinagre tinto'],
   ['caldo',.25,'taza',60,'ml','caldo bajo en sodio (de res, pollo o vegetales)','caldo'],
   ['maicena',2,'cdta',6,'g','maicena','maicena'],
   ['aceite_s',1,'cda',15,'ml','aceite de aguacate (o canola)','aceite de aguacate','Con punto de humo alto. No uses oliva extra virgen aquí.'],
   ['cilantro',.5,'taza',30,'g','cilantro fresco picado','cilantro']]},
  {g:'Arroz',items:[
   ['arroz',.75,'taza',140,'g','arroz blanco de grano largo','arroz','Enjuágalo hasta que el agua salga casi clara.'],
   ['agua_a',1.5,'taza',355,'ml','agua','agua'],
   ['sal_a',.25,'cdta',1.5,'g','sal fina','sal fina (arroz)']]}],
 steps:[
  {t:'Hornea las papas',time:'35 min, sin atención',timer:2100,
   x:`Precalienta el horno a 230 °C (450 °F). Lava {papa}, sécalas bien y córtalas en bastones de 1.5 cm (⅝ in). Mézclalas con {aceite_p} y {sal_p} y extiéndelas en una bandeja con papel pergamino, en una sola capa y sin que se toquen. Hornea 35 minutos, volteándolas a los 18 minutos.`,
   cue:'Bordes dorados oscuros y centro blando al pinchar con un tenedor.',
   warn:'Si amontonas las papas se cuecen al vapor y quedan blandas: usa dos bandejas si hace falta.'},
  {t:'Cocina el arroz',time:'25 min, sin atención',timer:1500,
   x:`Enjuaga {arroz} en un colador 30 segundos. Ponlo en una olla con tapa con {agua_a} y {sal_a}. Hierve a fuego alto; cuando rompa el hervor, baja al mínimo, tapa y cocina 15 minutos sin destapar. Apaga y deja tapado 10 minutos más. Esponja con un tenedor.`,
   cue:'Granos sueltos e hinchados, sin agua en el fondo.'},
  {t:v=>v==='camarones'?'Prepara los camarones':'Corta y marina la proteína',time:'15 min',timer:{d:600,camarones:300},
   x:v=>`Corta ${v==='res'?'la carne':v==='pollo'?'el pollo':'los camarones por la mitad a lo largo si son muy grandes y sécalos'} como se indica y mezcla {prot} con {soya_m}, {comino} y {pimienta} en un bowl. ${v==='res'?'Déjala 10 minutos a temperatura ambiente.':v==='pollo'?'Déjalo 10 minutos a temperatura ambiente.':'Déjalos solo 5 minutos: la soya los vuelve salados y firmes si se pasan.'} Mientras, corta {cebolla}, {tomate}, {pimiento} y {ajo}.`,
   cue:'La proteína se ve oscurecida de manera pareja y sin charcos de líquido.'},
  {t:'Mezcla la salsa',time:'3 min',
   x:`En una taza, mezcla {soya}, {vinagre}, {caldo}, {aji} y {maicena} con un tenedor, hasta que no queden grumos. La maicena se asienta, así que revuelve de nuevo justo antes de usarla.`},
  {t:v=>v==='res'?'Sella la carne':v==='pollo'?'Sella el pollo':'Sella los camarones',time:v=>v==='res'?'4 min':v==='pollo'?'6 min':'3 min',timer:{d:240,pollo:360,camarones:150},
   x:v=>`Calienta una sartén grande de 30 cm (12 in) o un wok a fuego alto 2 minutos, hasta que una gota de agua baile y se evapore. Añade {aceite_s:1/2} y agrega ${v==='res'?'la carne en tandas, en una sola capa. Dora 1–2 minutos por lado hasta que esté marrón por fuera y apenas rosada por dentro; terminará en la salsa.':v==='pollo'?'el pollo en tandas, en una sola capa. Cocina 2–3 minutos por lado hasta que esté dorado; terminará de cocinarse en la salsa.':'los camarones en una sola capa. Dora 1 minuto por lado, hasta que estén apenas rosados; terminarán en la salsa.'} Pásalo a un plato con sus jugos.`,
   cue:'Dorado por fuera, con bordes tostados y sin líquido acumulado en la sartén.',
   warn:v=>v==='pollo'?'Seguridad: el pollo debe llegar a 74 °C (165 °F) en el centro al final.':v==='res'?'Seguridad: la carne en tiras termina en la salsa hasta 63 °C (145 °F). Para la adulta mayor, déjala sin rosado.':null},
  {t:'Saltea las verduras',time:'4 min',timer:240,
   x:`En la misma sartén a fuego alto, agrega {aceite_s:1/2}. Saltea {cebolla} 2 minutos sin mover mucho, hasta que se dore en los bordes. Añade {pimiento} y {tomate} y cocina 1–2 minutos más, hasta que el tomate empiece a ablandarse pero conserve forma. Agrega {ajo} y cocina 20 segundos más.`,
   cue:'Cebolla con bordes tostados y todavía crujiente; el tomate suelta jugo sin deshacerse.',
   warn:'No cocines de más: la gracia del saltado son las verduras firmes, no deshechas.'},
  {t:'Une todo y termina',time:'2 min',timer:120,
   x:v=>`Devuelve ${v==='camarones'?'los camarones':'la proteína'} con sus jugos a la sartén. Revuelve la salsa y viértela sobre todo. Cocina 1–2 minutos moviendo, hasta que burbujee y espese lo suficiente para cubrir las verduras. Apaga el fuego, agrega las papas al horno y {cilantro}, y mezcla con dos movimientos suaves para que no se rompan.`,
   cue:'Salsa brillante que cubre todo sin acumularse en el fondo.'},
  {t:'Sirve',time:'3 min',
   x:`Sirve unos ¾ de taza (140 g) de arroz cocido en cada plato y reparte el lomo saltado encima, para {N} porciones. Sirve de inmediato, para que las papas se mantengan crujientes.`}],
 tools:'Horno con bandeja, olla con tapa, sartén grande de 30 cm (12 in) o wok, bowl, taza para la salsa, tabla y cuchillo afilado, colador.',
 tips:[
  ['Fuego muy alto, tandas pequeñas','Amontonar la proteína la cuece al vapor y suelta agua. Mejor dos tandas pequeñas que una grande.'],
  ['Papas al horno al final','Mezcla las papas con la salsa solo al servir: si las dejas reposar en ella se ablandan. Si te gustan más suaves, añádelas 1 minuto antes.'],
  ['Para la adulta mayor','Corta las tiras más finas, cocina la cebolla un minuto más para que quede suave y sirve con un poco más de salsa.']],
 store:'Refrigerado en recipiente tapado dura 3 días (con camarones, 2). Recalienta en sartén con 2 cucharadas de agua, 3 minutos, o en microondas tapado 2 minutos. Las papas pierden el crujiente: devuélvelas 5 minutos a un horno caliente o a la freidora de aire.',
 swaps:['Papas → camote en bastones (mismo tiempo de horneado).','Arroz blanco → arroz integral (cocina 40 min) o arroz de coliflor.','Vinagre tinto → vinagre de manzana o de arroz.','Ají amarillo → una pizca de pimentón dulce y unas gotas de limón.']},

/* ============================================================ 5. CURRY DE GARBANZOS ============================================================ */
{id:'curry_garbanzos',meal:'Cena',cuisine:'Asiática',img:null,
 title:'Curry cremoso de garbanzos y espinaca con leche de coco light, sobre arroz basmati',
 sub:'Un curry suave y aromático con tomate, jengibre y leche de coco. Se cocina en una olla y se come con cuchara.',
 prep:15,cook:35,total:50,base:4,
 variants:[
  {id:'vegetariano',label:'Vegetariano',sub:'Vegetariana',kcal:460,p:18,c:66,f:14,d:'Dos latas de garbanzos y yogur griego para sumar proteína.'},
  {id:'camarones',label:'Con camarones',sub:'Con mariscos',sea:1,kcal:465,p:35,c:52,f:13,d:'Una lata de garbanzos más camarones al final.'}],
 groups:[
  {g:'Base del curry',items:[
   ['aceite',1,'cda',15,'ml','aceite de oliva o de aguacate','aceite'],
   ['cebolla',1,'',200,'g','cebolla amarilla grande','cebolla','En cubitos de 8 mm (⅜ in).',null,1],
   ['ajo',4,'',12,'g','diente~s de ajo','ajo','Picado muy fino.',null,1],
   ['jengibre',1,'cda',8,'g','jengibre fresco rallado','jengibre','Un trozo de 2.5 cm (1 in), pelado con el borde de una cuchara.'],
   ['curry',2,'cda',12,'g','curry en polvo suave','curry en polvo','Usa curry en polvo, no pasta, que a veces contiene camarón fermentado.'],
   ['curcuma',.5,'cdta',1,'g','cúrcuma molida','cúrcuma'],
   ['comino',1,'cdta',2,'g','comino molido','comino'],
   ['chile',.25,'cdta',.5,'g','hojuelas de chile','hojuelas de chile','Opcional. Omítelas para la adulta mayor.'],
   ['sal',1,'cdta',6,'g','sal fina','sal fina','Ajusta al final.']]},
  {g:'Garbanzos, líquidos y verduras',items:[
   ['garbanzos',2,'',480,'g','lata~s de garbanzos (15 oz), escurrida~s y enjuagada~s','lata~s de garbanzos','Escúrrelos y enjuágalos bien.',['vegetariano'],1],
   ['garbanzos',1,'',240,'g','lata~s de garbanzos (15 oz), escurrida~s y enjuagada~s','lata~s de garbanzos','Escúrrelos y enjuágalos bien.',['camarones'],1],
   ['tomate',1,'taza',245,'g','puré de tomate o tomate triturado','tomate triturado','Sin azúcar añadida.'],
   ['coco',1.75,'taza',415,'ml','leche de coco light (1 lata de 13.5 oz)','leche de coco light','Agita la lata antes de abrirla.'],
   ['caldo',.5,'taza',120,'ml','caldo de vegetales bajo en sodio','caldo de vegetales'],
   ['espinaca',10,'oz',280,'g','hojas de espinaca fresca (baby)','espinaca','Lavadas y escurridas. Se reducen a un puñito.'],
   ['camarones',1,'lb',454,'g','camarones medianos o grandes, pelados y desvenados','camarones','Bien secos con papel de cocina.',['camarones'],.25]]},
  {g:'Arroz basmati',items:[
   ['arroz',.75,'taza',140,'g','arroz basmati','arroz basmati','Enjuágalo 2 minutos hasta que el agua salga casi clara.'],
   ['agua_a',1.25,'taza',295,'ml','agua','agua'],
   ['sal_a',.25,'cdta',1.5,'g','sal fina','sal fina (arroz)']]},
  {g:'Para servir',items:[
   ['yogur',.5,'taza',120,'g','yogur griego natural sin azúcar','yogur griego'],
   ['cilantro',.25,'taza',15,'g','cilantro fresco picado','cilantro'],
   ['lima',1,'',60,'g','limón verde (lima)','lima','Su jugo da frescura al final.',null,1]]}],
 steps:[
  {t:'Prepara los ingredientes',time:'12 min',
   x:`Pica {cebolla}, {ajo} y {jengibre}. Abre la lata de coco y agítala antes de usarla. Escurre y enjuaga {garbanzos} en un colador. Lava {espinaca} y sécala con un paño. Mide {curry}, {curcuma}, {comino} y {chile} en un plato pequeño, y ten listos {tomate}, {coco} y {caldo}.`,
   add:{camarones:'Seca bien {camarones} con papel de cocina y espolvoréalos con una pizca de sal.'},
   cue:'Todo a la mano: el curry se cocina rápido y no da tiempo de picar después.'},
  {t:'Cocina el arroz basmati',time:'20 min, sin atención',timer:1200,
   x:`Enjuaga {arroz} 2 minutos bajo agua fría, hasta que salga casi clara. Ponlo en una olla con tapa con {agua_a} y {sal_a}. Hierve a fuego alto, tapa, baja al mínimo y cocina 12 minutos sin destapar. Apaga y deja 5 minutos más tapado. Esponja con un tenedor.`,
   cue:'Granos largos, sueltos, que se separan fácilmente sin agua en el fondo.'},
  {t:'Sofríe la cebolla',time:'6 min',timer:360,
   x:`En una olla o sartén honda de 28 cm (11 in), calienta {aceite} a fuego medio 1 minuto. Agrega {cebolla} con {sal:1/2} y cocina 5–6 minutos, moviendo cada minuto, hasta que esté blanda y translúcida, sin dorarse mucho.`,
   cue:'La cebolla se ve brillante, translúcida y huele dulce.'},
  {t:'Tuesta el ajo, el jengibre y las especias',time:'2 min',timer:90,
   x:`Añade {ajo} y {jengibre} y cocina 30 segundos. Agrega {curry}, {curcuma}, {comino} y {chile}, y mueve constantemente 45–60 segundos, hasta que el aroma se intensifique. Si se pega, añade una cucharada de agua.`,
   cue:'Huele a especias tostadas, sin olor a quemado.',
   warn:'Las especias se queman rápido y amargan. Si se oscurecen, añade el tomate de inmediato.'},
  {t:'Agrega el tomate, el coco y los garbanzos',time:'15 min',timer:900,
   x:`Vierte {tomate}, {coco} y {caldo} y revuelve raspando el fondo. Agrega {garbanzos}. Lleva a hervor suave, baja el fuego a bajo y cocina 15 minutos, moviendo cada 4–5 minutos. Con el dorso de la cuchara, aplasta unos cuantos garbanzos para que el curry se espese.`,
   cue:'El curry cubre la cuchara y deja un surco que tarda 2 segundos en cerrarse.',
   warn:'No lo dejes hervir con fuerza: la leche de coco light se separa y se ve cortada. Mantén burbujas pequeñas y lentas.'},
  {t:'Agrega la espinaca',time:'2 min',timer:120,
   x:`Incorpora {espinaca} por puñados, moviendo hasta que cada tanda se reduzca antes de agregar la siguiente. Cocina 1–2 minutos más, hasta que esté brillante y blanda.`,
   cue:'Hojas verde intenso, suaves, mezcladas con el curry.'},
  {t:'Cocina los camarones',time:'3–4 min',v:['camarones'],timer:210,
   x:`Sube a fuego medio. Agrega {camarones} y sumérgelos en el curry. Cocina 2–3 minutos, moviendo una vez, hasta que cada camarón forme una “C” abierta, rosada y opaca. Apaga el fuego de inmediato.`,
   cue:'Camarones rosados y opacos, formando una “C”. Si se cierran en una “O” apretada, se pasaron.',
   warn:'No los cocines de más: se ponen gomosos. Se terminan de cocinar con el calor residual.'},
  {t:'Sirve',time:'3 min',
   x:`Prueba y ajusta: más sal si le falta, jugo de {lima:1/2} para refrescar. Sirve ¾ de taza (140 g) de arroz en cada plato para {N} porciones, cubre con el curry y termina con cucharadas de {yogur}, {cilantro} y un chorrito del jugo de {lima:1/2}.`}],
 tools:'Olla o sartén honda de 28 cm (11 in), olla con tapa para el arroz, cuchara de madera, colador, rallador fino, tabla y cuchillo.',
 tips:[
  ['Textura cremosa sin crema','Aplastar una parte de los garbanzos espesa el curry de forma natural. No necesitas ni crema ni harina.'],
  ['Sabor profundo','Tostar las especias en el aceite 45–60 segundos antes de añadir líquidos hace una gran diferencia. No te saltes ese paso.'],
  ['Para la adulta mayor','Aplasta más garbanzos y omite el chile; así el curry es más suave y fácil de masticar. Sirve con arroz bien cocido.']],
 store:'Refrigerado en recipiente tapado dura 4 días (con camarones, 2). Congelado (sin camarones ni yogur), hasta 3 meses. Recalienta a fuego bajo con 2 cucharadas de agua, 5 minutos, moviendo; o en microondas tapado 2–3 minutos a potencia media.',
 swaps:['Arroz basmati → arroz de coliflor salteado 5 minutos (mismo curry encima).','Espinaca → col rizada (kale) sin tallos, con 3 minutos más de cocción.','Garbanzos → lentejas cocidas o frijoles blancos.','Leche de coco light → 1 taza de yogur griego mezclado con ½ taza de caldo (agrégalo fuera del fuego).']},

/* ============================================================ 6. HAMBURGUESA DE PAVO / FRIJOLES NEGROS ============================================================ */
{id:'hamburguesa_pavo',meal:'Cena',cuisine:'Americana saludable',img:null,
 title:'Hamburguesas caseras de pavo y avena (o de frijoles negros) con ensalada grande y camote al horno',
 sub:'Hamburguesas jugosas hechas en casa, sin pan, con una ensalada crujiente y bastones de camote dorados al horno.',
 prep:30,cook:40,total:70,base:4,
 variants:[
  {id:'pavo',label:'De pavo',sub:'Sin mariscos',kcal:485,p:35,c:46,f:18,d:'Pavo molido magro con avena y cebolla rallada.'},
  {id:'frijoles',label:'De frijoles negros',sub:'Vegetariana',kcal:480,p:18,c:73,f:13,d:'Frijoles negros, avena y huevo, con aguacate. Menos proteína que la de pavo.'}],
 groups:[
  {g:'Hamburguesas',items:[
   ['pavo',1.25,'lb',565,'g','pavo molido magro (93 %)','pavo molido','Frío, directo del refrigerador.',['pavo'],.25],
   ['avena',.5,'taza',45,'g','avena en hojuelas (tradicional)','avena en hojuelas','Aglutina y retiene la humedad.',['pavo']],
   ['frijoles',2,'',480,'g','lata~s de frijoles negros (15 oz), escurrida~s y enjuagada~s','lata~s de frijoles negros','Escúrrelos muy bien y sécalos con papel.',['frijoles'],1],
   ['avena',.75,'taza',68,'g','avena en hojuelas (tradicional)','avena en hojuelas','Aglutina y absorbe la humedad de los frijoles.',['frijoles']],
   ['huevo',1,'',50,'g','huevo grande','huevo','Une la mezcla.',null,1],
   ['cebolla',.5,'',80,'g','cebolla pequeña, rallada fina','cebolla','Rállala y exprímela en un paño para quitar el exceso de agua.'],
   ['ajo',2,'',6,'g','diente~s de ajo','ajo','Picado muy fino.',null,1],
   ['mostaza',1,'cda',15,'g','mostaza de Dijon','mostaza Dijon'],
   ['pimenton',1,'cdta',2.5,'g','pimentón ahumado','pimentón ahumado'],
   ['comino',.5,'cdta',1,'g','comino molido','comino'],
   ['sal_h',1,'cdta',6,'g','sal fina','sal fina','Para las hamburguesas.'],
   ['pimienta',.5,'cdta',1,'g','pimienta negra','pimienta negra'],
   ['aceite_h',2,'cdta',10,'ml','aceite de oliva (para la sartén)','aceite de oliva']]},
  {g:'Camote al horno',items:[
   ['camote',1.25,'lb',565,'g','camote (batata) naranja','camote','En bastones de 1.5 cm × 7 cm (⅝ × 3 in), con piel bien lavada.'],
   ['aceite_c',1,'cda',15,'ml','aceite de oliva','aceite de oliva (camote)'],
   ['sal_c',.5,'cdta',3,'g','sal fina','sal fina (camote)'],
   ['paprika',.5,'cdta',1.2,'g','pimentón dulce','pimentón dulce']]},
  {g:'Ensalada grande y salsa',items:[
   ['lechuga',1,'',350,'g','lechuga romana (1 cabeza grande, ≈ 8 tazas)','lechuga','Lavada, bien escurrida y cortada en tiras de 2 cm.',null,1],
   ['tomate',2,'',300,'g','tomate~s maduro~s','tomates','En cubos de 1.5 cm (⅝ in).',null,1],
   ['pepino',1,'',250,'g','pepino mediano','pepino','En medias lunas de 5 mm (¼ in).',null,1],
   ['limon',1,'',60,'g','limón verde (lima) o amarillo','limón','Su jugo es el aderezo.',null,1],
   ['aceite_s',1,'cda',15,'ml','aceite de oliva extra virgen (aderezo)','aceite de oliva (aderezo)'],
   ['yogur',.5,'taza',120,'g','yogur griego natural sin azúcar','yogur griego','Para la salsa de mostaza.'],
   ['aguacate',.5,'',100,'g','aguacate Hass maduro','aguacate~s','En láminas justo antes de servir.',['frijoles']]]}],
 steps:[
  {t:'Precalienta el horno y corta el camote',time:'12 min',
   x:`Precalienta el horno a 220 °C (425 °F) con una rejilla en el centro. Lava y seca {camote}, y córtalo en bastones de 1.5 cm × 7 cm (⅝ × 3 in) parejos. Mezcla con {aceite_c}, {sal_c} y {paprika}. Extiéndelos en una bandeja con papel pergamino, en una sola capa y sin que se toquen.`,
   cue:'Bastones parejos, brillantes de aceite y espaciados.'},
  {t:'Hornea los bastones de camote',time:'30 min',timer:1800,
   x:`Hornea 30 minutos, volteándolos con una espátula a los 15 minutos. Terminan crujientes por fuera y cremosos por dentro. Mientras se hornean, sigue con los pasos siguientes.`,
   cue:'Los bordes están caramelizados y oscuros, y un tenedor entra sin resistencia.',
   warn:'Si se doran demasiado por fuera pero siguen duros, baja la temperatura a 200 °C (400 °F) y hornea 5 minutos más.'},
  {t:v=>v==='pavo'?'Prepara la mezcla de pavo':'Prepara la mezcla de frijoles',time:'10 min',
   x:v=>v==='pavo'
    ?`En un bowl grande, mezcla {avena}, {huevo}, {cebolla}, {ajo}, {mostaza}, {pimenton}, {comino}, {sal_h} y {pimienta}. Agrega {pavo} y mezcla suavemente con las manos solo 20–30 segundos, hasta integrar. Si trabajas de más la carne, las hamburguesas quedan duras.`
    :`Pon {frijoles} en un bowl grande y aplasta con un tenedor, dejando la mitad de los frijoles enteros para dar textura. Agrega {avena}, {huevo}, {cebolla}, {ajo}, {mostaza}, {pimenton}, {comino}, {sal_h} y {pimienta}. Mezcla con una cuchara de madera hasta que la masa se pegue al apretarla.`,
   cue:v=>v==='pavo'?'La mezcla es pareja y suave, sin trozos grandes de avena o cebolla.':'Al apretar un puñado, la masa mantiene la forma sin desmoronarse.'},
  {t:'Forma las hamburguesas y enfríalas',time:'18 min',timer:900,
   x:`Divide la mezcla en {N} partes iguales y forma discos de 11 cm (4½ in) de diámetro y 2 cm (¾ in) de grosor, con una ligera hendidura en el centro con el pulgar: así no se abomban al cocinarse. Colócalas en un plato con papel pergamino y refrigera 15 minutos para que se firmen.`,
   cue:'Se ven firmes y mantienen la forma al levantarlas con la espátula.',
   warn:'Lávate las manos con jabón y agua tibia después de tocar el pavo crudo. Limpia también la tabla y el plato.'},
  {t:'Prepara la ensalada y la salsa',time:'10 min',
   x:`Mientras las hamburguesas se enfrían, mezcla {lechuga}, {tomate} y {pepino} en un bowl grande. En una taza mezcla {yogur}, {mostaza} y el jugo de {limon:1/2}; en otro bowl, prepara el aderezo con {aceite_s}, el resto del jugo de {limon:1/2} y una pizca de sal. Aliña la ensalada justo antes de servir, para que no se ablande.`,
   cue:'Verduras frescas y crujientes; la salsa de yogur es cremosa y espesa.'},
  {t:v=>v==='pavo'?'Cocina las hamburguesas de pavo':'Cocina las hamburguesas de frijoles',time:v=>v==='pavo'?'12 min':'9 min',timer:{d:720,frijoles:540},
   x:v=>v==='pavo'
    ?`Calienta una sartén antiadherente grande a fuego medio 1 minuto. Agrega {aceite_h} y cocina las hamburguesas 5–6 minutos por lado, sin aplastarlas con la espátula. Cocina hasta que el centro marque 74 °C (165 °F) en un termómetro de cocina.`
    :`Calienta una sartén antiadherente grande a fuego medio 1 minuto. Agrega {aceite_h} y cocina las hamburguesas 4 minutos por lado, sin moverlas hasta que se despeguen solas. Voltéalas con cuidado: son más frágiles que las de carne.`,
   cue:v=>v==='pavo'?'Costra dorada por ambos lados y jugo transparente al presionar.':'Costra dorada y firme, y centro caliente.',
   warn:v=>v==='pavo'?'Seguridad: el pavo molido debe llegar a 74 °C (165 °F) en el centro. Nunca lo sirvas rosado.':null},
  {t:'Sirve',time:'5 min',
   x:`Reparte la ensalada aliñada en {N} platos y coloca una hamburguesa en cada uno, con salsa de yogur encima. Sirve los bastones de camote al lado. Para la adulta mayor, corta la hamburguesa en trozos pequeños.`,
   add:{frijoles:'Corona con láminas de {aguacate}.'}}],
 tools:'Bandeja de hornear con papel pergamino, sartén antiadherente grande, 2 bowls grandes, rallador, termómetro de cocina, espátula, tabla y cuchillo.',
 tips:[
  ['Hamburguesas jugosas','No amases la mezcla de pavo y evita aplastarla en la sartén: cada presión exprime el jugo. La avena retiene la humedad.'],
  ['Prepara de más','Forma el doble y congela las crudas separadas con papel pergamino hasta 2 meses. Se cocinan directo del congelador con 3 minutos más por lado.'],
  ['Para quien entrena fuerte','Sirve dos hamburguesas y suma ½ taza más de camote. Es una cena alta en proteína y carbohidrato para recuperar.']],
 store:'Las hamburguesas cocidas se refrigeran 3 días en recipiente tapado. Recalienta en sartén tapada a fuego bajo 3 minutos por lado, o en microondas 1 minuto. Los bastones de camote pierden el crujiente: devuélvelos 5 minutos al horno. La ensalada, sin aliñar, aguanta 2 días.',
 swaps:['Camote → papas en bastones (mismo tiempo de horneado).','Avena → pan molido integral (⅓ de taza / 35 g).','Ensalada de lechuga → col morada rallada o espinaca baby.','Sin pan → envuelve la hamburguesa en hojas de lechuga o sirve en pan integral (suma ≈ 140 kcal).']}
];
