// @ts-nocheck
// Recetas modelo (datos). Ingredientes = [id, cantidad, unidad, g/ml, ud, nombre(~plural), corto, nota, variantes, redondeo]
export const RECETAS=[
{id:'pericos',meal:'Desayuno',cuisine:'Latina casera',img:'pericos',
 title:'Huevos pericos con tostada integral, aguacate y papaya',
 sub:'El desayuno clásico colombo-venezolano: huevos cremosos con tomate, pimiento y cebollín, con más fibra y menos grasa que la versión frita.',
 prep:15,cook:12,total:27,base:4,
 variants:[
  {id:'clasica',label:'Clásica',sub:'Sin mariscos',kcal:445,p:19,c:36,f:25,d:'2 huevos por persona, sin mariscos.'},
  {id:'camarones',label:'Con camarones',sub:'Con mariscos',sea:1,kcal:460,p:28,c:37,f:23,d:'1½ huevos por persona más 56 g de camarones.'}],
 groups:[
  {g:'Sofrito de pericos',items:[
   ['aceite',2,'cda',30,'ml','aceite de oliva extra virgen','aceite de oliva','Mide con cuchara. Una cucharada son 120 kcal.'],
   ['cebollin',6,'',100,'g','tallo~s de cebollín (cebolla larga)','cebollín','En rodajas de 3 mm (⅛ in). Separa lo blanco de lo verde y reserva el verde para decorar.'],
   ['tomate',2,'',300,'g','tomate~s maduro~s pero firme~s','tomate','Sin semillas ni pulpa aguada, en cubitos de 6 mm (¼ in).'],
   ['pimiento',.5,'taza',80,'g','pimiento rojo','pimiento rojo','En cubitos de 5 mm. Puedes cambiarlo por ají dulce.'],
   ['ajo',2,'',6,'g','diente~s de ajo','ajo','Picado muy fino o rallado.'],
   ['comino',.25,'cdta',.5,'g','comino molido','comino'],
   ['sal',.5,'cdta',3,'g','sal fina','sal fina','La mitad va al sofrito y la otra mitad a los huevos.'],
   ['pimienta',.25,'cdta',.5,'g','pimienta negra recién molida','pimienta negra']]},
  {g:'Huevos',items:[
   ['huevos',8,'',400,'g','huevo~s grande~s','huevos','A temperatura ambiente (sácalos 15 min antes) quedan más parejos.',['clasica'],1],
   ['huevos',6,'',300,'g','huevo~s grande~s','huevos','A temperatura ambiente (sácalos 15 min antes) quedan más parejos.',['camarones'],1],
   ['leche',3,'cda',45,'ml','leche o bebida vegetal sin azúcar','leche','Opcional. Hace los huevos más cremosos.']]},
  {g:'Camarones',v:['camarones'],items:[
   ['camarones',8,'oz',225,'g','camarones medianos (31/40), pelados y desvenados','camarones','Sécalos muy bien con papel. Sin humedad se doran en vez de hervirse.',['camarones']],
   ['pimenton',.5,'cdta',1.2,'g','pimentón ahumado','pimentón ahumado','',['camarones']]]},
  {g:'Para servir',items:[
   ['pan',4,'',120,'g','rebanada~s de pan 100 % integral','pan integral','Mejor si es de masa madre o con semillas.'],
   ['aguacate',1,'',200,'g','aguacate Hass grande y maduro','aguacate','Está listo si cede un poco al presionar con el pulgar.'],
   ['limon',1,'',60,'g','limón verde (lima)','limón verde','Su jugo va al aguacate y el resto en gajos para servir.'],
   ['papaya',3,'taza',450,'g','papaya madura en cubos','papaya','Cubos de 2 cm. Si no hay papaya, usa melón o piña.']]}],
 steps:[
  {t:'Prepara todo antes de encender el fuego',time:'10 min',
   x:`Los pericos se cocinan en minutos, así que todo debe estar cortado y al alcance antes de prender la estufa. Corta {cebollin} y separa lo blanco de lo verde; pica {tomate} y {pimiento}; pica {ajo} muy fino. En un bowl grande rompe {huevos}, agrega {leche} y {sal:1/2}, y bate con un tenedor unos 30 segundos, hasta que no queden hebras de clara y la mezcla sea de un amarillo parejo, sin espuma.`,
   add:{camarones:'Seca los camarones con papel de cocina, presionando, y mézclalos con {pimenton} y una pizca de sal.'},
   cue:'La mezcla de huevo se ve de un solo color y sin hilos transparentes.'},
  {t:'Dora los camarones',time:'3 min',v:['camarones'],timer:150,
   x:`Calienta una sartén antiadherente de 26–28 cm (10–11 in) a fuego medio-alto por 2 minutos. Añade {aceite:1/2}; cuando brille y se deslice con facilidad, pon los camarones en una sola capa, sin amontonar. Déjalos 60–90 segundos sin tocarlos, hasta que la base esté dorada. Voltéalos y cocina 45–60 segundos más. Pásalos a un plato; terminarán de calentarse al final.`,
   cue:'Cada camarón forma una “C” abierta, rosada y opaca. Si se cierra en una “O” apretada, se pasó de cocción y quedará gomoso.'},
  {t:'Sofríe el tomate y el pimiento',time:'5–6 min',timer:330,
   x:v=>`En la misma sartén (sin lavar), a fuego medio, calienta ${v==='camarones'?'{aceite:1/2}':'{aceite}'}. Añade lo blanco del cebollín y cocina 1 minuto hasta que se vea translúcido. Agrega {ajo}, {comino} y {pimienta}; revuelve 20–30 segundos, hasta que huela a ajo tostado (si se dora, amarga). Incorpora {tomate} y {pimiento} con {sal:1/2}. Cocina 4–5 minutos, revolviendo cada 30 segundos, hasta que el tomate suelte su jugo y quede una salsa espesa.`,
   cue:'Al pasar la espátula por el fondo queda un surco que tarda unos 2 segundos en cerrarse.',
   warn:'Si queda líquido en la sartén, cocina 1 minuto más. Ese exceso de agua vuelve los huevos aguados.'},
  {t:'Tuesta el pan y prepara el aguacate',time:'4 min',timer:180,
   x:`Mientras el sofrito termina, tuesta {pan} en tostadora durante 2–3 minutos, o en horno a 200 °C (400 °F) por 4 minutos. En un plato hondo aplasta {aguacate} con un tenedor, dejando trocitos visibles, y añade el jugo de {limon:1/2} y una pizca de sal.`},
  {t:'Cuaja los huevos, cremosos y brillantes',time:'2–3 min',timer:150,
   x:`Baja el fuego a medio-bajo. Vierte los huevos batidos sobre el sofrito y deja quietos 20 segundos, hasta que los bordes empiecen a cuajar. Con una espátula de silicona empuja suavemente los bordes hacia el centro, formando pliegues grandes, cada 10–15 segundos. Apaga el fuego cuando aún se vean brillantes y un poco húmedos: el calor de la sartén los termina mientras sirves.`,
   add:{camarones:'Cuando falten 20 segundos, devuelve los camarones a la sartén con sus jugos y mezcla con dos movimientos suaves.'},
   cue:'Pliegues cremosos, sin líquido transparente en el fondo y sin dorarse.',
   warn:'Seguridad: los huevos deben quedar cuajados, sin parte líquida. Si cocinas para niños, embarazadas o adultos mayores, déjalos 30 segundos más.'},
  {t:'Sirve',time:'3 min',
   x:`Reparte la preparación en {N} platos. Unta cada tostada con una parte del aguacate, sirve los pericos al lado y decora con el cebollín verde reservado. Acompaña con {papaya}, repartida en los platos, y gajos del resto del limón.`}],
 tools:'Sartén antiadherente de 26–28 cm (10–11 in), espátula de silicona, bowl grande y tenedor, tabla y cuchillo, tostadora u horno.',
 tips:[
  ['Fuego bajo, huevos cremosos','Con fuego alto los huevos expulsan agua y quedan gomosos. Si chisporrotean al caer en la sartén, retírala del fuego 10 segundos.'],
  ['Familias mixtas','Haz la versión clásica completa. En otra sartén dora los camarones (paso 2) y ponlos solo sobre los platos de quienes los quieren.'],
  ['Más proteína','Cambia 2 huevos enteros por 4 claras. Rinde más volumen con menos calorías.']],
 store:'Mejor recién hecho. El sofrito sin huevo se conserva 3 días en la nevera en un frasco tapado: caliéntalo en la sartén y agrega huevos frescos. Los huevos ya cocidos aguantan 1 día; caliéntalos 20–30 segundos en el microondas a potencia media, o quedarán secos.',
 swaps:['Pan integral → arepa pequeña asada (≈ 90 g) o tortilla de maíz.','Pimiento rojo → ají dulce (4 o 5 ajíes).','Papaya → melón, piña o mango.','Leche → bebida de avena o almendra sin azúcar, o 1 cda. de agua.']},

{id:'bowl',meal:'Almuerzo',cuisine:'Mediterránea',img:'bowl',
 title:'Bowl mediterráneo de quinoa con salsa de yogur y limón',
 sub:'Quinoa al limón, verduras crujientes y proteína dorada, con una salsa fresca de yogur y eneldo. Se arma en bowl y se prepara casi todo con anticipación.',
 prep:25,cook:30,total:55,base:4,
 variants:[
  {id:'pollo',label:'Con pollo',sub:'Sin mariscos',kcal:510,p:44,c:43,f:18,d:'Pechuga marinada con limón y orégano.'},
  {id:'camarones',label:'Con camarones',sub:'Con mariscos',sea:1,kcal:495,p:44,c:43,f:16,d:'Camarones grandes marinados 15 minutos.'},
  {id:'garbanzos',label:'Garbanzos',sub:'Vegetariana',kcal:530,p:26,c:68,f:17,d:'Garbanzos crujientes al horno. Menos proteína que las otras variantes.'}],
 groups:[
  {g:'Quinoa al limón',items:[
   ['quinoa',1,'taza',170,'g','quinoa blanca','quinoa','Se enjuaga antes de cocinarla.',['pollo','camarones']],
   ['quinoa',.75,'taza',130,'g','quinoa blanca','quinoa','Se enjuaga antes de cocinarla.',['garbanzos']],
   ['agua',2,'taza',475,'ml','agua o caldo bajo en sodio','agua','',['pollo','camarones']],
   ['agua',1.5,'taza',355,'ml','agua o caldo bajo en sodio','agua','',['garbanzos']],
   ['salq',.25,'cdta',1.5,'g','sal fina','sal fina'],
   ['ralladura',1,'cda',6,'g','ralladura fina de limón amarillo','ralladura de limón','Ralla la cáscara de 1 limón (solo lo amarillo) antes de exprimirlo.']]},
  {g:'Marinada y proteína',items:[
   ['prot',1.25,'lb',565,'g','pechuga de pollo sin piel ni hueso (o muslo deshuesado)','pechuga de pollo','Si es gruesa, aplánala a 2 cm (¾ in) de grosor para que se cocine pareja.',['pollo'],.25],
   ['prot',1.25,'lb',565,'g','camarones grandes (21/25), pelados y desvenados','camarones','Sécalos con papel antes de marinar.',['camarones'],.25],
   ['prot',2,'',480,'g','lata~s de garbanzos cocidos (425 g / 15 oz cada una, escurridos)','garbanzos','Enjuágalos y sécalos sobre una toalla. La humedad impide que se pongan crujientes.',['garbanzos']],
   ['aceite_m',2,'cda',30,'ml','aceite de oliva extra virgen','aceite de oliva'],
   ['jugo',4,'cda',60,'ml','jugo de limón fresco','jugo de limón','De unos 2 limones. Se reparte entre la marinada y la salsa.'],
   ['ajo',3,'',9,'g','diente~s de ajo','ajo','Rallados.'],
   ['oregano',2,'cdta',2,'g','orégano seco','orégano','Frótalo entre las palmas para despertar el aroma.'],
   ['pimenton',1,'cdta',2.5,'g','pimentón dulce (o ahumado)','pimentón'],
   ['sal_m',.75,'cdta',4.5,'g','sal fina','sal fina'],
   ['pimienta',.5,'cdta',1,'g','pimienta negra','pimienta negra']]},
  {g:'Ensalada',items:[
   ['pepino',1,'',300,'g','pepino inglés grande','pepino','En cubos de 1 cm (½ in); sin pelar si la cáscara es fina.'],
   ['cherry',1.5,'taza',225,'g','tomates cherry','tomates cherry','Cortados a la mitad.'],
   ['cebolla_m',.5,'',60,'g','cebolla morada pequeña','cebolla morada','En medias lunas muy finas. Remójala 10 minutos en agua con hielo para quitarle el picor.'],
   ['aceitunas',.5,'taza',75,'g','aceitunas Kalamata sin hueso','aceitunas','Cortadas a la mitad.'],
   ['feta',.25,'taza',40,'g','queso feta desmenuzado','queso feta','Opcional. Omítelo si quieres una versión sin lácteos.'],
   ['perejil',.5,'taza',25,'g','perejil fresco picado','perejil','Hojas y tallos tiernos.'],
   ['espinaca',4,'taza',120,'g','espinaca baby','espinaca baby']]},
  {g:'Salsa de yogur y limón',items:[
   ['yogur',1,'taza',240,'g','yogur griego natural sin azúcar','yogur griego'],
   ['ajo_s',1,'',3,'g','diente~s de ajo pequeño~s','ajo','Rallado fino. Si el diente es grande, usa la mitad.'],
   ['eneldo',2,'cda',6,'g','eneldo fresco picado (o menta)','eneldo'],
   ['sal_s',.25,'cdta',1.5,'g','sal fina','sal fina'],
   ['agua_s',1,'cda',15,'ml','agua fría','agua fría','Para aflojar la textura.']]},
  {g:'Aderezo rápido',items:[
   ['aceite_a',1,'cda',15,'ml','aceite de oliva extra virgen','aceite de oliva'],
   ['vinagre',1,'cda',15,'ml','vinagre de vino tinto','vinagre de vino tinto'],
   ['mostaza',1,'cdta',5,'g','mostaza Dijon','mostaza Dijon'],
   ['miel',1,'cdta',7,'g','miel','miel','Opcional.']]}],
 steps:[
  {t:'Prepara la marinada',time:'5 min + reposo',
   timer:{d:1200,camarones:900,garbanzos:0},
   x:v=>v==='garbanzos'
    ?`Precalienta el horno a 220 °C (425 °F) con la rejilla en el centro y una bandeja dentro: una bandeja caliente dora los garbanzos más rápido. Seca bien {prot} con papel o un paño limpio.`
    :`En un bowl grande mezcla {aceite_m}, {jugo:3/4}, {ajo}, {oregano}, {pimenton}, {sal_m} y {pimienta}. Agrega {prot} y voltea con las manos hasta que todo quede cubierto. Tapa y refrigera ${v==='pollo'?'20 minutos (máximo 4 horas: el limón en exceso vuelve la carne harinosa)':'15 minutos (no más de 20: el ácido empieza a “cocinar” el camarón y lo pone gomoso)'}.`,
   cue:v=>null},
  {t:'Cocina la quinoa',time:'25 min, casi sin esfuerzo',timer:1200,
   x:`Enjuaga {quinoa} en un colador fino bajo agua fría, frotando con la mano 30 segundos, para quitar la saponina que da sabor amargo. Escurre y tuesta los granos en una olla mediana seca, a fuego medio, 2 minutos, moviendo, hasta que huelan a nueces. Añade {agua} y {salq}; sube el fuego hasta que hierva con fuerza, tapa, baja al mínimo y cocina 15 minutos sin destapar. Apaga el fuego, deja tapada otros 5 minutos y esponja con un tenedor. Mezcla {ralladura}.`,
   cue:'Los granos se ven translúcidos, con un pequeño anillo blanco (el germen) separado, y el fondo de la olla está seco.'},
  {t:'Prepara las verduras y el aderezo',time:'15 min',timer:600,
   x:`Pon {cebolla_m} en un bowl con agua fría y hielo durante 10 minutos. Mientras, en un bowl grande combina {pepino}, {cherry}, {aceitunas} y {perejil}. En un frasco con tapa agrega {aceite_a}, {vinagre}, {mostaza} y {miel}; agita 15 segundos, hasta que se vea cremoso y no se separe. Escurre la cebolla, sécala con un paño y súmala a las verduras. Todavía no aliñes.`},
  {t:'Haz la salsa de yogur',time:'5 min',
   x:`Mezcla {yogur}, {ajo_s}, {eneldo}, {jugo:1/4}, {sal_s} y {agua_s}, hasta lograr una crema espesa que aun así caiga de la cuchara. Debe saber fresca y algo ácida. Refrigérala hasta el momento de servir.`},
  {t:'Sella el pollo',time:'12 min',v:['pollo'],timer:720,
   x:`Calienta una sartén grande de hierro o antiadherente a fuego medio-alto durante 3 minutos. Saca el pollo de la marinada y deja escurrir el exceso: si hay mucho líquido, el pollo hierve en vez de dorarse. Cocina 5–6 minutos por lado, sin moverlo los primeros 4, hasta que se forme una costra dorada. Déjalo reposar 5 minutos sobre una tabla y córtalo en tiras de 1 cm (⅜ in), siempre contra la fibra.`,
   cue:'Dorado por fuera, y al cortar el jugo sale claro y la carne es blanca por dentro.',
   warn:'Seguridad: la parte más gruesa debe marcar 74 °C (165 °F) con termómetro.'},
  {t:'Sella los camarones',time:'4 min',v:['camarones'],timer:180,
   x:`Calienta la sartén a fuego alto 2–3 minutos, hasta que una gota de agua salte y desaparezca. Saca los camarones de la marinada y deja escurrir. Cocínalos en una sola capa (en dos tandas si no caben) 90 segundos sin mover; voltéalos y cocina 45–60 segundos más. Pásalos de inmediato a un plato, porque siguen cocinándose con su propio calor.`,
   cue:'Forman una “C” abierta, rosada y opaca. Una “O” cerrada significa que se pasaron.'},
  {t:'Hornea los garbanzos',time:'25 min',v:['garbanzos'],timer:1500,
   x:`En un bowl mezcla los garbanzos secos con {aceite_m}, {ajo}, {oregano}, {pimenton}, {sal_m} y {pimienta}. Saca la bandeja caliente, extiende los garbanzos en una sola capa y hornea 20–25 minutos, sacudiendo la bandeja a los 10 minutos. Al sacarlos, rocía con {jugo:3/4}.`,
   cue:'Suenan como maracas al sacudir la bandeja, dorados y con la piel un poco arrugada. Se ponen más crujientes al enfriarse 2 minutos.'},
  {t:'Arma los bowls',time:'5 min',
   x:v=>`Aliña las verduras con dos tercios del aderezo y mezcla. Reparte {espinaca} en {N} bowls y encima pon la quinoa tibia y las verduras. Coloca ${v==='pollo'?'las tiras de pollo':v==='camarones'?'los camarones':'los garbanzos crujientes'} a un lado. Termina con 3 o 4 cucharadas de salsa de yogur por bowl, {feta} y un chorrito del aderezo restante.`,
   cue:'Un bowl bien armado tiene la mitad verduras, un cuarto de grano y un cuarto de proteína.'}],
 tools:'Olla mediana con tapa, colador fino, sartén grande de hierro o antiadherente (o bandeja de horno para los garbanzos), 2 bowls grandes, frasco con tapa, rallador fino.',
 tips:[
  ['Prepara por partes','Quinoa, aderezo y salsa se guardan por separado 4 días en la nevera. Arma el bowl al servir para que la espinaca no se marchite.'],
  ['Quinoa suelta, no pastosa','Respeta 1 parte de quinoa por 2 de agua y no destapes la olla durante la cocción. Si queda agua al final, tapa 3 minutos más fuera del fuego.'],
  ['Familias mixtas','Cocina la quinoa y las verduras una sola vez. Sella el pollo y los camarones en tandas separadas y cada quien elige su proteína.']],
 store:'Pollo: 4 días en la nevera. Camarones: 2 días, y se comen mejor fríos sobre la ensalada porque recalentados se endurecen. Garbanzos: 1 día en un recipiente sin tapar hermético; para devolverles el crujido, 5 minutos en horno a 200 °C (400 °F). La quinoa cocida se congela 3 meses.',
 swaps:['Quinoa → farro, arroz integral o cuscús integral.','Yogur griego → hummus (3 cdas. por bowl).','Queso feta → queso fresco desmenuzado.','Espinaca → rúcula o lechuga romana.']},

{id:'salteado',meal:'Cena',cuisine:'Internacional',img:'salteado',
 title:'Salteado de pollo y brócoli estilo wok con arroz integral',
 sub:'Pollo tierno con película de maicena, brócoli verde brillante y una salsa de soya, jengibre y ajonjolí. En 30 minutos activos, con un solo sartén.',
 prep:20,cook:40,total:60,base:4,
 variants:[
  {id:'pollo',label:'Con pollo',sub:'Sin mariscos',kcal:545,p:39,c:64,f:15,d:'Pechuga en láminas finas.'},
  {id:'camarones',label:'Con camarones',sub:'Con mariscos',sea:1,kcal:525,p:39,c:65,f:12,d:'Camarones grandes, cocción de 2 minutos.'},
  {id:'tofu',label:'Con tofu',sub:'Vegetariana',kcal:565,p:30,c:66,f:20,d:'Tofu extra firme dorado y crujiente.'}],
 groups:[
  {g:'Arroz integral',items:[
   ['arroz',1,'taza',190,'g','arroz integral de grano largo','arroz integral','Enjuágalo hasta que el agua salga casi clara.'],
   ['agua_a',2,'taza',475,'ml','agua','agua'],
   ['sal_a',.5,'cdta',3,'g','sal fina','sal fina']]},
  {g:'Proteína',items:[
   ['prot',1.25,'lb',565,'g','pechuga de pollo (o muslo deshuesado)','pollo','En láminas de 6 mm (¼ in) contra la fibra. Si la congelas 20 minutos, cortas más fino.',['pollo'],.25],
   ['prot',1.25,'lb',565,'g','camarones grandes, pelados y desvenados','camarones','Bien secos con papel de cocina.',['camarones'],.25],
   ['prot',2,'',800,'g','bloque~s de tofu extra firme (400 g / 14 oz)','tofu','Prénsalo 20 minutos y córtalo en cubos de 2 cm (¾ in).',['tofu']],
   ['soya_m',1,'cda',15,'ml','salsa de soya baja en sodio','soya'],
   ['maicena_m',1,'cda',8,'g','maicena','maicena'],
   ['agua_m',1,'cda',15,'ml','agua','agua','',['pollo','camarones']],
   ['pimienta_m',.25,'cdta',.5,'g','pimienta blanca o negra','pimienta']]},
  {g:'Vegetales',items:[
   ['brocoli',1,'',565,'g','cabeza~s grande~s de brócoli (≈ 5 tazas de floretes)','brócoli','Floretes de 4 cm (1½ in). Pela el tallo y córtalo en rodajas finas: también se come.'],
   ['zanahoria',2,'',150,'g','zanahoria~s mediana~s','zanahoria','En rodajas diagonales de 3 mm (⅛ in).'],
   ['pimiento',1,'',200,'g','pimiento rojo grande','pimiento','En tiras de 1 cm (⅜ in).'],
   ['champi',8,'oz',225,'g','champiñones','champiñones','Laminados de 5 mm. No los laves: límpialos con un paño húmedo.'],
   ['cebollin',4,'',60,'g','tallo~s de cebollín','cebollín','Rodajas de 5 mm. Separa los blancos de los verdes.'],
   ['ajo',4,'',12,'g','diente~s de ajo','ajo','Laminados finos.'],
   ['jengibre',1,'cda',8,'g','jengibre fresco rallado','jengibre','Un trozo de 2.5 cm (1 in), pelado con el borde de una cuchara.']]},
  {g:'Salsa',items:[
   ['caldo',.5,'taza',120,'ml','caldo bajo en sodio','caldo'],
   ['soya',3,'cda',45,'ml','salsa de soya baja en sodio','soya'],
   ['vinagre',1,'cda',15,'ml','vinagre de arroz (o de manzana)','vinagre de arroz'],
   ['miel',1,'cda',21,'g','miel o sirope de agave','miel'],
   ['maicena_s',2,'cdta',6,'g','maicena','maicena'],
   ['ajonjoli_a',2,'cdta',10,'ml','aceite de ajonjolí tostado','aceite de ajonjolí'],
   ['chile',.25,'cdta',.5,'g','hojuelas de chile','hojuelas de chile','Opcional.']]},
  {g:'Para cocinar y servir',items:[
   ['aceite_c',2,'cda',30,'ml','aceite de aguacate (o canola)','aceite de aguacate','Aceite con punto de humo alto. No uses oliva extra virgen aquí.'],
   ['agua_v',3,'cda',45,'ml','agua','agua','Para cocer el brócoli al vapor dentro de la sartén.'],
   ['ajonjoli',1,'cda',9,'g','semillas de ajonjolí tostado','ajonjolí tostado']]}],
 steps:[
  {t:'Cocina el arroz integral (empieza por aquí)',time:'50 min, sin atención',timer:3000,
   x:`Enjuaga {arroz} en un colador 30 segundos. Ponlo en una olla mediana de tapa ajustada con {agua_a} y {sal_a}. Hierve a fuego alto; cuando rompa el hervor, baja al mínimo, tapa y cocina 40 minutos sin destapar. Apaga y deja tapado 10 minutos más. Esponja con un tenedor.`,
   cue:'Granos hinchados, sin agua en el fondo, tiernos pero con algo de mordida.'},
  {t:v=>v==='tofu'?'Prensa y prepara el tofu':'Marina la proteína',time:v=>v==='tofu'?'25 min':'15 min',
   timer:{d:900,camarones:600,tofu:1200},
   x:v=>v==='tofu'
    ?`Envuelve {prot} en toallas de cocina, pon encima un plato con un peso (una lata grande) y deja 20 minutos para sacarle el agua. Córtalo en cubos de 2 cm (¾ in), mézclalos con {soya_m} y {pimienta_m} y espolvorea {maicena_m}. Voltea suavemente hasta que cada cubo tenga una capa seca y harinosa.`
    :`Mezcla en un bowl {soya_m}, {maicena_m}, {agua_m} y {pimienta_m}. Agrega {prot} y revuelve con las manos 1 minuto, hasta que no queden grumos de maicena y cada pieza tenga una película lisa. Esa capa fina (el “velveting” de la cocina china) mantiene la proteína jugosa a fuego alto. Déjala reposar ${v==='pollo'?'15':'10'} minutos fuera de la nevera.`},
  {t:'Corta los vegetales y mezcla la salsa',time:'15 min',
   x:`Corta {brocoli}, {zanahoria}, {pimiento}, {champi}, {cebollin}, {ajo} y {jengibre} como se indica en la lista. Agrúpalos por tiempo de cocción en tres platos: duros (brócoli y zanahoria), medios (pimiento, champiñones y cebollín blanco) y aromáticos (ajo y jengibre). En una taza mezcla {caldo}, {soya}, {vinagre}, {miel}, {maicena_s}, {ajonjoli_a} y {chile}. La maicena se asienta, así que revuelve otra vez justo antes de usarla.`},
  {t:v=>v==='pollo'?'Sella el pollo':v==='camarones'?'Sella los camarones':'Dora el tofu',time:v=>v==='tofu'?'6 min':'4 min',
   timer:{d:240,camarones:150,tofu:360},
   x:v=>`Calienta una sartén grande de 30 cm (12 in) o un wok a fuego alto durante 2 minutos, hasta que una gota de agua baile y se evapore. Añade {aceite_c:1/2} y esparce ${v==='tofu'?'los cubos de tofu':v==='pollo'?'el pollo':'los camarones'} en una sola capa, en tandas si hace falta: amontonar la proteína la cuece al vapor en lugar de dorarla. ${v==='pollo'?'Cocina 2 minutos sin mover, voltea y cocina 1–2 minutos más. Retírala con el centro apenas rosado; terminará en la salsa.':v==='camarones'?'Cocina 1 minuto por lado y retíralos cuando apenas estén rosados; terminarán en la salsa.':'Déjalo 2 minutos sin mover y gíralo cada minuto hasta dorar todas las caras. Pásalo a un plato.'}`,
   cue:'Dorado por fuera con bordes tostados, sin líquido acumulado en la sartén.'},
  {t:'Saltea los vegetales',time:'6 min',timer:360,
   x:`En la misma sartén, sin lavar, agrega {aceite_c:1/2} a fuego alto. Saltea el brócoli y la zanahoria 2 minutos, moviendo. Añade {agua_v}, tapa y cocina 2 minutos al vapor. Destapa, incorpora pimiento, champiñones y el cebollín blanco, y saltea 2–3 minutos más, hasta que los champiñones suelten su agua y se doren. Agrega el ajo y el jengibre y cocina 30 segundos, hasta que huela intenso pero sin dorar (el ajo quemado amarga).`,
   cue:'El brócoli está verde brillante y se deja pinchar con un tenedor, pero aún ofrece resistencia.'},
  {t:'Une todo con la salsa',time:'2 min',timer:120,
   x:`Devuelve la proteína y sus jugos a la sartén. Revuelve la salsa y viértela sobre todo. Cocina 1–2 minutos, moviendo, hasta que burbujee y espese lo suficiente para cubrir el dorso de una cuchara. Prueba y ajusta: más vinagre si está pesada, un chorrito de soya si le falta sal, chile si quieres picante.`,
   warn:v=>v==='pollo'?'Seguridad: la pieza más gruesa de pollo debe marcar 74 °C (165 °F). Si ves el centro rosado, déjalo 1 minuto más en la salsa.':null},
  {t:'Sirve',time:'3 min',
   x:`Sirve unos ¾ de taza (140 g) de arroz cocido en cada plato y reparte el salteado encima, para {N} porciones. Termina con {ajonjoli} y el cebollín verde en rodajas.`}],
 tools:'Olla mediana con tapa, sartén grande de 30 cm (12 in) o wok, bowl, taza para la salsa, tabla y cuchillo afilado, colador.',
 tips:[
  ['Por qué el fuego alto','Los vegetales se doran y quedan crujientes porque sueltan el agua rápido. A fuego medio se hierven en su propio jugo y salen blandos.'],
  ['Cocina arroz doble','Cocina el doble de arroz, repártelo en bolsas planas y congélalo hasta 3 meses. Se calienta en 2 minutos en microondas.'],
  ['Familias mixtas','Saltea los vegetales una sola vez y divide la sartén: pollo, camarones o tofu en tandas separadas, y cada quien se sirve lo suyo.']],
 store:'Refrigerado en recipiente tapado dura 4 días (con camarones, 2 días). Recalienta en sartén 3 minutos con 1 cucharada de agua para revivir la salsa, o en microondas 2 minutos tapado. El arroz se congela por separado.',
 swaps:['Brócoli → ejotes, bok choy o brócoli rabe.','Arroz integral → quinoa o arroz de coliflor.','Salsa de soya → tamari si necesitas evitar el gluten.','Miel → sirope de agave o 1 cdta. de azúcar moreno.']}
];


/* ===== Perfiles: la misma receta se adapta a quién la come ===== */
export const PERFILES=[
 {id:'std',label:'Adulto estándar',sub:'Plan de pérdida de peso',short:'',
  note:'Porción base de la receta. En la app, tus calorías salen de tus datos del Día 0.'},
 {id:'atleta',label:'Entrena fuerte',sub:'Hombre de 30 años',short:'quien entrena fuerte',
  note:'Con más masa muscular y mucho gasto, necesita porciones más grandes y proteína alta (cerca de 40 g por comida) para conservar músculo mientras baja grasa. Ajusta la porción a tu meta calórica del Día 0.'},
 {id:'mayor',label:'Adulta mayor',sub:'80 años, movilidad limitada',short:'la adulta mayor',
  note:'A esta edad, bajar de peso rápido se lleva músculo y fuerza. La prioridad es proteína en cada comida (25–30 g), buena hidratación y comida fácil de masticar y de preparar. Cualquier cambio de plan debe consultarse con su médico o nutricionista.'}];
export const PROF={
 pericos:{
  atleta:{mult:1.5,add:{kcal:51,p:11,c:0,f:0},plate:'1½ porciones: 3 huevos y 2 rebanadas de pan, con 3 claras extra en el revuelto. Aguacate: ½ unidad.',
   ad:['Las claras suman 11 g de proteína casi sin grasa.','Sube el pan integral a 2 rebanadas: aporta la energía para entrenar.']},
  mayor:{mult:.85,add:{kcal:51,p:11,c:0,f:0},plate:'Plato más pequeño (¾ de la porción) pero con 3 claras extra para llegar a unos 27 g de proteína. Servir en plato llano y cubos blandos.',
   ad:['Huevos totalmente firmes, nunca húmedos (riesgo de intoxicación).','Tomate sin piel y pan sin corteza dura, aguacate bien machacado.','Papaya muy madura, en cubos pequeños.','Preparación sentada: dejar todo cortado la noche anterior o usar vegetales congelados picados.']}},
 bowl:{
  atleta:{mult:1.4,add:{kcal:0,p:0,c:0,f:0},plate:'1½ porciones de quinoa y unos 200 g de pollo cocido (o 200 g de camarones, o 1½ tazas de garbanzos).',
   ad:['Más quinoa para reponer glucógeno después de entrenar.','Come el bowl 1–2 horas antes o después del entrenamiento.']},
  mayor:{mult:.8,add:{kcal:0,p:0,c:0,f:0},plate:'⅘ de porción, con la proteína desmenuzada y las verduras en cubos pequeños.',
   ad:['Pollo desmenuzado con tenedores (o muslo deshuesado, más tierno).','Verduras en cubos de 5 mm o ralladas; sin aceitunas ni cebolla cruda si cuesta digerirlas.','Espinaca picada fina o cocida 1 minuto.','Si no puede estar de pie mucho rato: usar pechuga en filetes finos y verduras ya cortadas del supermercado.']}},
 salteado:{
  atleta:{mult:1.4,add:{kcal:0,p:0,c:0,f:0},plate:'1½ porciones del salteado con 1 taza de arroz cocido.',
   ad:['Arroz integral extra: carbohidrato de energía sostenida.','Agrega 1 cda. de ajonjolí extra por porción.']},
  mayor:{mult:.8,add:{kcal:0,p:0,c:0,f:0},plate:'⅘ de porción, con las verduras bien blandas y la salsa algo más líquida.',
   ad:['Muslo deshuesado en lugar de pechuga: más tierno.','Verduras tapadas 2 minutos más, hasta aplastarse con tenedor.','Soya baja en sodio y sin sal extra si su médico lo indica.','Arroz más blando (50 min de cocción) o arroz blanco si masticar o digerir es difícil.']}}};
export const PSTEP={
 pericos:{0:{atleta:'Añade 3 claras al bowl de huevos por cada persona; aportan 11 g de proteína casi sin grasa.',mayor:'Preparación sentada: deja el cebollín, el tomate y el pimiento cortados la noche anterior, o usa tomate y pimiento congelados ya picados.'},
  2:{mayor:'Pela los tomates antes de cortarlos: escáldalos 30 segundos en agua hirviendo y la piel se suelta sola. Cocina el sofrito 2 minutos más, hasta que quede muy suave.'},
  3:{atleta:'Tuesta 2 rebanadas por persona.',mayor:'Tuesta el pan solo hasta dorar suave y retira la corteza dura. Machaca el aguacate hasta que quede cremoso, casi una pasta, para untar.'},
  4:{mayor:'Cocina los huevos hasta que estén totalmente firmes, sin partes brillantes ni húmedas: 1 minuto más que en la receta base. En personas mayores, los huevos poco cocidos aumentan el riesgo de intoxicación alimentaria.'},
  5:{atleta:'Sirve 1½ porciones: 3 huevos y 2 tostadas.',mayor:'Sirve la papaya muy madura, en cubos pequeños, o licuada con yogur como batido para sumar proteína.'}},
 bowl:{0:{mayor:'Si cuesta apretar o aplanar, compra pechuga ya en filetes finos o usa muslos deshuesados; no hace falta aplanarla.'},
  4:{mayor:'Cocina el pollo 1–2 minutos más por lado (sin pasarte de 74 °C / 165 °F), o hornéalo tapado a 180 °C (350 °F) por 20 minutos: queda más jugoso y se desmenuza fácil.'},
  7:{atleta:'Arma tu bowl con 1½ porciones de quinoa y unos 200 g de proteína.',mayor:'Pica las verduras en cubos de 5 mm o ralla el pepino, omite las aceitunas y la cebolla cruda si cuesta digerirlas, y desmenuza la proteína con dos tenedores en lugar de cortarla en tiras.'}},
 salteado:{0:{atleta:'Cocina 1½ tazas de arroz para que alcance para porciones de 1½.',mayor:'Si el arroz integral cuesta masticarlo o digerirlo, cocínalo 50 minutos en vez de 40 con ½ taza (120 ml) extra de agua, o cámbialo por arroz blanco.'},
  3:{mayor:'Usa muslo deshuesado en lugar de pechuga: queda más tierno. Si la sartén pesa, usa una más liviana o cocina en dos tandas pequeñas.'},
  4:{mayor:'Cocina las verduras tapadas 2 minutos más, hasta que el brócoli y la zanahoria se aplasten con un tenedor. La verdura crujiente cuesta masticarla.'},
  5:{mayor:'Deja la salsa un poco más líquida (agrega 2 cdas. de caldo) para que el arroz y las verduras queden húmedos y se traguen mejor.'},
  6:{atleta:'Sirve 1½ porciones del salteado con 1 taza de arroz.'}}};
