// @ts-nocheck
// Recetas adicionales: desayunos
export const DESAYUNOS=[
{id:'avena_noche',meal:'Desayuno',cuisine:'Americana saludable',img:'avena_noche',
 title:'Avena remojada con yogur, chía y frutos rojos',
 sub:'Se prepara la noche anterior y por la mañana ya está lista: avena cremosa y fría, con semillas de chía y fruta fresca. Perfecta para días de prisa y para quien tiene poco tiempo en la cocina.',
 prep:10,cook:0,total:10,base:4,
 variants:[
  {id:'yogur',label:'Con yogur griego',sub:'Con lácteos · sin mariscos',kcal:360,p:17,c:52,f:9,d:'Leche, yogur griego natural y miel. Más proteína y textura cremosa.'},
  {id:'vegana',label:'Vegana',sub:'Sin lácteos ni huevo',kcal:335,p:14,c:47,f:10,d:'Bebida de soya sin azúcar, yogur de soya natural y miel de maple. Sin ningún producto animal.'}],
 groups:[
  {g:'Base de avena (se remoja toda la noche)',items:[
   ['avena',2,'taza',160,'g','avena en hojuelas tradicionales (no instantánea)','avena en hojuelas','Las hojuelas tradicionales quedan suaves pero con cuerpo; la instantánea se vuelve papilla. Si en casa hay personas celíacas, busca avena con sello sin gluten.'],
   ['leche',2,'taza',475,'ml','leche (entera o semidescremada)','leche','Fría, directo de la nevera.',['yogur']],
   ['soya',2,'taza',475,'ml','bebida de soya sin azúcar','bebida de soya','Sin azúcar y sin sabor a vainilla para controlar la dulzura. Revisa que diga sin azúcar añadida.',['vegana']],
   ['yogurg',1,'taza',240,'g','yogur griego natural sin azúcar','yogur griego','Natural, sin sabores. El de bajo contenido graso rinde igual de cremoso.',['yogur']],
   ['yogurs',1,'taza',240,'g','yogur de soya natural sin azúcar','yogur de soya','Natural, sin azúcar. Revisa la etiqueta: algunos llevan leche.',['vegana']],
   ['chia',4,'cda',48,'g','semillas de chía','semillas de chía','Absorben el líquido y espesan la avena. No las sustituyas por linaza molida sin ajustar el líquido.'],
   ['miel',4,'cdta',28,'g','miel de abeja','miel','Mide con cucharita rasa. Ajusta al gusto: si la fruta está muy dulce, usa menos.',['yogur']],
   ['maple',4,'cdta',20,'ml','miel de maple (sirope de arce) puro','miel de maple','Reemplaza la miel en la versión vegana.',['vegana']],
   ['vainilla',1,'cdta',5,'ml','extracto de vainilla','vainilla','Extracto puro o esencia de buena calidad.'],
   ['canela',.5,'cdta',1.2,'g','canela molida','canela'],
   ['sal',.125,'cdta',.75,'g','sal fina','sal fina','Una pizca realza el dulzor de la avena.']]},
  {g:'Para servir',items:[
   ['frutos',2,'taza',300,'g','frutos rojos (fresas, arándanos, frambuesas o moras)','frutos rojos','Frescos o congelados. Si son congelados, descongélalos en la nevera la noche anterior y escúrrelos.']]}],
 steps:[
  {t:'Mezcla los ingredientes secos',time:'3 min',
   x:`Elige 4 frascos de vidrio con tapa de unos 350 ml (12 oz), o un recipiente grande con tapa. En un bowl grande mezcla {avena}, {chia}, {canela} y {sal} con una cuchara, hasta que las semillas queden repartidas por toda la avena.`,
   cue:'Se ve una mezcla pareja de hojuelas claras con puntitos negros, sin grumos de chía.'},
  {t:'Agrega los líquidos y revuelve bien',time:'3 min',
   x:v=>v==='yogur'
    ?`Vierte {leche} sobre la mezcla seca, añade {yogurg}, {miel} y {vainilla}. Revuelve con una cuchara durante 1 minuto, raspando el fondo del bowl, hasta que no queden hojuelas secas ni bolsas de yogur.`
    :`Vierte {soya} sobre la mezcla seca, añade {yogurs}, {maple} y {vainilla}. Revuelve con una cuchara durante 1 minuto, raspando el fondo del bowl, hasta que no queden hojuelas secas ni bolsas de yogur.`,
   cue:'La mezcla se ve líquida y de un color uniforme; es normal, la avena aún no se ha hinchado.',
   warn:'Si no revuelves bien el fondo, la chía se acumula en un bloque gelatinoso. Revuelve hasta tocar el fondo.'},
  {t:'Deja reposar 5 minutos y revuelve de nuevo',time:'5 min',timer:300,
   x:`Deja el bowl quieto 5 minutos. La chía empieza a hincharse y a espesar. Revuelve otra vez 20 segundos, para romper cualquier grumo de chía que se haya formado.`,
   cue:'La mezcla ya se ve más espesa y cuando levantas la cuchara cae despacio.'},
  {t:'Reparte en los frascos',time:'3 min',
   x:`Con una cuchara grande, reparte la mezcla en los frascos, a razón de unas ¾ de taza (180 ml) por frasco; son {N} porciones. Deja 2 cm (¾ in) libres arriba para poder revolver y servir la fruta. Cierra con tapa. Si lo prefieres, anota la fecha en la tapa con una cinta.`},
  {t:'Refrigera toda la noche',time:'6–12 h',timer:28800,
   x:`Lleva los frascos a la nevera, a 4 °C (40 °F) o menos, y déjalos mínimo 6 horas; lo ideal son 8 a 12 horas. En ese tiempo la avena absorbe el líquido, se ablanda y se vuelve cremosa.`,
   cue:'Al día siguiente la mezcla se ve espesa, como un pudín suave, y al inclinar el frasco no se desliza.',
   warn:'No la dejes fuera de la nevera: contiene lácteos o bebida vegetal y es un alimento frío que debe mantenerse frío.'},
  {t:'Prepara la fruta y sirve',time:'5 min',
   x:`Por la mañana lava {frutos} y sécalos con papel. Si son fresas, quítales las hojitas y córtalas en cuartos. Destapa los frascos y revuelve cada uno con una cuchara. Si la avena quedó muy espesa, agrega 1 o 2 cucharadas de leche o bebida vegetal y mezcla. Termina con los frutos rojos encima. Se come fría, o también tibia: caliéntala 60–90 segundos en el microondas, sin tapa.`,
   cue:'Debe tener la consistencia de una crema espesa, que cae de la cuchara pero sostiene la fruta encima.'}],
 tools:'4 frascos de vidrio con tapa de 350 ml (12 oz) o un recipiente grande, bowl grande, cuchara, tazas y cucharas medidoras, tabla y cuchillo.',
 tips:[
  ['La proporción que nunca falla','Por cada 1/2 taza (40 g) de avena usa 1/2 taza de líquido, 1/4 taza de yogur y 1 cucharada de chía. Con esa proporción puedes cambiar los sabores sin arruinar la textura.'],
  ['Antes de salir de casa','Si la llevas al trabajo, deja la fruta en un envase aparte y agrégala justo antes de comer: así no suelta jugo ni se ablanda.'],
  ['Cuando se espesa demasiado','La chía sigue absorbiendo líquido. Si al segundo día la avena está muy firme, añade un chorrito de leche o bebida vegetal y mezcla.']],
 store:'Sin fruta, en frascos tapados y en la nevera, se conserva hasta 3 días. Con fruta fresca encima, consúmela dentro de las siguientes 24 horas. No la congeles.',
 swaps:['Fresas, arándanos y moras → banano en rodajas, durazno o manzana rallada con canela.','Miel o miel de maple → 1 cucharadita de azúcar morena o puré de dátiles.','Yogur griego → requesón o yogur natural espeso (versión con lácteos).','Leche o bebida de soya → bebida de almendra o de avena sin azúcar.']},

{id:'parfait_yogur',meal:'Desayuno',cuisine:'Mediterránea',img:'parfait_yogur',
 title:'Parfait de yogur griego con granola casera de nueces y mango',
 sub:'Capas de yogur cremoso, granola de nueces recién horneada, crujiente y apenas dulce, y fruta fresca. Ligero, con buena saciedad y bonito para servir en vasos.',
 prep:10,cook:20,total:30,base:4,
 variants:[
  {id:'mango',label:'Con mango',sub:'Con lácteos y nueces · sin mariscos',kcal:415,p:23,c:49,f:14,d:'Mango maduro en cubos. Dulce y tropical.'},
  {id:'rojos',label:'Con frutos rojos',sub:'Con lácteos y nueces · sin mariscos',kcal:390,p:22,c:43,f:14,d:'Fresas, arándanos y frambuesas. Más frescos y menos azúcar.'}],
 groups:[
  {g:'Granola casera de nueces',items:[
   ['avena',1,'taza',80,'g','avena en hojuelas tradicionales','avena en hojuelas','Si hay personas celíacas, usa avena con sello sin gluten.'],
   ['nueces',.5,'taza',55,'g','nueces sin sal','nueces','Pícalas en trozos de 5 mm (¼ in), ni muy finos ni enteros. Contiene frutos secos: avisa si alguien tiene alergia.'],
   ['aceite',1,'cda',15,'ml','aceite de oliva extra virgen','aceite de oliva','Mide con cuchara.'],
   ['miel',2,'cda',42,'g','miel de abeja','miel','Si está cristalizada, caliéntala 10 segundos en el microondas.'],
   ['canela',.5,'cdta',1.2,'g','canela molida','canela'],
   ['sal',.125,'cdta',.75,'g','sal fina','sal fina']]},
  {g:'Yogur',items:[
   ['yogur',3,'taza',720,'g','yogur griego natural sin azúcar','yogur griego','Natural, espeso y frío. El de bajo contenido graso funciona muy bien.'],
   ['vainilla',1,'cdta',5,'ml','extracto de vainilla','vainilla','Aromatiza el yogur sin añadir azúcar.']]},
  {g:'Fruta',v:['mango'],items:[
   ['mango',3,'taza',480,'g','mango maduro en cubos','mango maduro','Pelado y cortado en cubos de 1,5 cm (½ in). Está maduro si cede un poco al presionar y huele dulce junto al tallo.']]},
  {g:'Fruta',v:['rojos'],items:[
   ['frutos',3,'taza',430,'g','frutos rojos (fresas, arándanos, frambuesas)','frutos rojos','Lavados y secos. Las fresas en cuartos. Pueden ser congelados, descongelados y escurridos.']]}],
 steps:[
  {t:'Calienta el horno y mezcla la granola',time:'8 min',
   x:`Precalienta el horno a 160 °C (325 °F) con la rejilla en el centro. Forra una bandeja con papel pergamino. En un bowl grande mezcla {avena}, {nueces}, {canela} y {sal}. En una taza aparte calienta {aceite} con {miel} durante 10 segundos en el microondas, hasta que se vea fluida, y viértela sobre la avena. Revuelve con una cuchara durante 1 minuto, hasta que cada hojuela quede apenas brillante.`,
   cue:'No hay zonas secas y la mezcla se pega un poco al formar un puñado.'},
  {t:'Extiende y hornea la granola',time:'18–20 min',timer:1200,
   x:`Extiende la mezcla sobre la bandeja en una capa delgada, de unos 1 cm (⅜ in), y presiónala suavemente con el dorso de la cuchara. Hornea 20 minutos en total, y a los 10 minutos revuélvela y vuelve a extenderla para que dore parejo.`,
   cue:'Dorado claro, aroma a nuez tostada y bordes color caramelo.',
   warn:'Las nueces y la miel se queman muy rápido: en los últimos 5 minutos no te alejes del horno. Si ves bordes oscuros, sácala de inmediato.'},
  {t:'Enfría la granola sin tocarla',time:'15 min',timer:900,
   x:`Saca la bandeja y déjala enfriar 15 minutos sin tocarla. Recién salida del horno se ve blanda, y se pone crujiente al enfriar. Luego rómpela con las manos en trozos de tamaño variado.`,
   cue:'Al enfriar suena crujiente al partirla y ya no se siente pegajosa.'},
  {t:'Prepara la fruta',time:'5 min',
   x:v=>v==='mango'
    ?`Pela el mango con un pelador o cuchillo, corta la pulpa alrededor de la semilla y pícala en cubos de 1,5 cm (½ in). Reserva {mango} en un bowl; si queda mucho jugo en la tabla, agrégalo a la fruta.`
    :`Lava {frutos} bajo un chorro suave de agua fría y sécalos con papel. Quita las hojitas a las fresas y córtalas en cuartos. Reserva en un bowl.`,
   cue:'La fruta se ve brillante, firme y sin agua acumulada en el bowl.'},
  {t:'Bate el yogur con vainilla',time:'1 min',
   x:`En un bowl mediano mezcla {yogur} con {vainilla} y bate con una cuchara 20 segundos, hasta que quede liso y cremoso, sin grumos.`},
  {t:'Arma los parfaits en capas',time:'5 min',
   x:`Usa {N} vasos altos o frascos de unos 350 ml (12 oz). Pon una cucharada de granola en el fondo, luego una capa de yogur (aprox. ¾ de taza / 180 g por porción), después fruta y repite. Termina con fruta y una cucharada de granola encima. Sirve de inmediato para conservar lo crujiente.`,
   cue:'Se ven franjas definidas de blanco, dorado y color de fruta.',
   warn:'Si no vas a comer enseguida, guarda la granola en un envase aparte y agrégala al final: con el yogur se ablanda en menos de 30 minutos.'}],
 tools:'Bandeja de horno, papel pergamino, bowl grande y mediano, cuchara, tabla y cuchillo, 4 vasos o frascos de 350 ml (12 oz).',
 tips:[
  ['Granola para toda la semana','La granola rinde un poco más de lo que pide una porción. Guarda lo que sobre en un frasco: te sirve para 2 o 3 desayunos más.'],
  ['El yogur más cremoso','Si tu yogur está aguado, escúrrelo 15 minutos en un colador con un paño limpio y quedará más espeso.'],
  ['Opción para dentadura delicada','Si alguien tiene dificultad para masticar, tritura la granola gruesa en una bolsa con un rodillo hasta convertirla en migas finas.']],
 store:'La granola enfriada se guarda en un frasco hermético a temperatura ambiente hasta 7 días. El yogur y la fruta, en la nevera hasta 3 días por separado. El parfait armado conviene comerlo dentro de las 2 horas.',
 swaps:['Nueces → almendras laminadas, pecanas o semillas de girasol (sin frutos secos).','Mango → durazno, piña o papaya en cubos.','Miel → miel de maple.','Yogur griego → yogur de coco o de soya natural sin azúcar (versión sin lácteos).']},

{id:'tortilla_vegetales',meal:'Desayuno',cuisine:'Latina casera',img:'tortilla_vegetales',
 title:'Tortilla de claras y huevos con espinaca, champiñones y queso fresco, con arepa',
 sub:'Una tortilla francesa esponjosa y abundante en verduras, con más proteína que una de solo huevos, acompañada de una arepita pequeña asada en sartén.',
 prep:20,cook:20,total:40,base:4,
 variants:[
  {id:'clasica',label:'Clásica',sub:'Con lácteos · sin mariscos',kcal:375,p:21,c:29,f:20,d:'1 huevo entero y 2 claras por persona, con espinaca, champiñones y queso fresco.'},
  {id:'camarones',label:'Con camarones',sub:'Con mariscos',sea:1,kcal:410,p:31,c:29,f:19,d:'Menos yemas y 56 g de camarones por persona dentro de la tortilla.'}],
 groups:[
  {g:'Arepitas',items:[
   ['harina',1,'taza',125,'g','harina de maíz precocida (tipo P.A.N.)','harina de maíz precocida','Es harina de maíz, no maicena ni harina de trigo.'],
   ['agua',1,'taza',240,'ml','agua tibia','agua tibia','Tibia, no caliente.'],
   ['sal',.75,'cdta',4.5,'g','sal fina','sal fina','Se reparte: ⅓ en la masa, ⅓ en las verduras y ⅓ en los huevos.']]},
  {g:'Verduras',items:[
   ['aceite',2,'cda',30,'ml','aceite de oliva extra virgen','aceite de oliva','Se reparte entre salteado y tortillas.'],
   ['champi',2,'taza',150,'g','champiñones blancos en láminas','champiñones','Límpialos con un paño húmedo, sin remojarlos. Láminas de 4 mm (⅙ in).'],
   ['cebolla',.5,'',60,'g','cebolla blanca','cebolla','Picada en cuadritos de 4 mm.'],
   ['ajo',2,'',6,'g','diente~s de ajo','ajo','Picado muy fino.'],
   ['espinaca',4,'taza',120,'g','espinaca fresca (hojas tiernas)','espinaca','Lavada y muy bien seca; la humedad aguaría la tortilla.'],
   ['queso',.75,'taza',100,'g','queso fresco desmenuzado','queso fresco','En trozos de 1 cm (⅜ in). Si es muy salado, usa menos sal.']]},
  {g:'Huevos',items:[
   ['huevos',4,'',200,'g','huevo~s grande~s','huevo~s','Enteros, a temperatura ambiente si es posible.',['clasica'],1],
   ['huevos',3,'',150,'g','huevo~s grande~s','huevo~s','Enteros, a temperatura ambiente si es posible.',['camarones'],1],
   ['claras',8,'',264,'g','clara~s de huevo','clara~s','Puedes usar claras líquidas pasteurizadas: 1 taza (240 ml).',null,1],
   ['pimienta',.25,'cdta',.5,'g','pimienta negra recién molida','pimienta negra']]},
  {g:'Camarones',v:['camarones'],items:[
   ['camarones',8,'oz',225,'g','camarones medianos, pelados y desvenados','camarones','Descongelados y muy secos. Pícalos en 3 trozos.',['camarones'],.5]]}],
 steps:[
  {t:'Prepara las verduras y los huevos',time:'10 min',
   x:`Quita las puntas a las hojas de {espinaca} si tienen tallos gruesos y sécalas con papel o centrífuga. Corta {champi} en láminas de 4 mm (⅙ in), pica {cebolla} y {ajo} muy fino, y desmenuza {queso}. En un bowl rompe {huevos} y {claras}, agrega {sal:1/3} y {pimienta} y bate con un tenedor 30 segundos, hasta que no se vean hilos de clara.`,
   add:{camarones:'Seca los camarones con papel, presionando, pícalos en 3 trozos cada uno y sazónalos con una pizca de sal.'},
   cue:'La mezcla de huevo se ve homogénea, amarilla clara y con pocas burbujas.'},
  {t:'Haz la masa de las arepitas',time:'8 min',timer:300,
   x:`Mezcla {harina} con {sal:1/3} en un bowl. Agrega {agua} poco a poco y amasa 2 minutos con las manos, hasta que no queden grumos. Tapa y deja reposar 5 minutos. Luego forma 4 bolitas y aplástalas hasta obtener discos de 9 cm (3½ in) de diámetro y 1 cm (⅜ in) de grosor, alisando los bordes con los dedos húmedos.`,
   cue:'La masa se ve lisa, no se pega a las manos y no se agrieta en los bordes.',
   warn:'Si los bordes se agrietan, la masa está seca: añade 1 cucharada de agua y amasa de nuevo.'},
  {t:'Asa las arepitas',time:'11 min',timer:660,
   x:`Calienta una sartén antiadherente o un comal a fuego medio, unos 180 °C (350 °F), 2 minutos. Coloca los discos sin aceite y cocínalos 5 a 6 minutos por lado, sin moverlos, hasta que se formen manchas doradas y una costra firme. Envuélvelas en un paño limpio para que se mantengan tibias y suaves por dentro.`,
   cue:'Al golpearlas con los dedos suenan huecas y la costra está seca y dorada.',
   warn:'Si el fuego está muy alto, se queman por fuera y quedan crudas por dentro.'},
  {t:'Dora los camarones',time:'3 min',v:['camarones'],timer:150,
   x:`En la sartén grande de 26 cm (10 in), a fuego medio-alto, calienta {aceite:1/4}. Cuando brille, añade {camarones} en una sola capa y cocina 60 a 90 segundos hasta que cambien de color; voltea y cocina 30 segundos más. Pásalos a un plato.`,
   cue:'Cada camarón se ve rosado y opaco formando una “C”. Si se cierra en “O”, se pasó de cocción.'},
  {t:'Saltea los champiñones, la cebolla y la espinaca',time:'7 min',timer:420,
   x:v=>`Usa una sartén antiadherente de 26 cm (10 in) a fuego medio-alto y caliéntala 1 minuto. Añade ${v==='camarones'?'{aceite:1/4}':'{aceite:1/2}'}, luego los champiñones en una sola capa y déjalos 2 minutos sin mover, hasta que suelten agua y empiecen a dorar. Revuelve, agrega la cebolla y {sal:1/3} y cocina 2 minutos. Añade el ajo 30 segundos y, al final, la espinaca por puñados, 1 minuto, hasta que se marchite. Pasa todo a un plato.`,
   cue:'El fondo de la sartén ya no tiene líquido y los champiñones están dorados.',
   warn:'Si queda agua en la sartén, sigue cocinando unos 30–60 segundos más. El agua vuelve la tortilla aguada.'},
  {t:'Cuaja las tortillas y rellénalas',time:'8 min',timer:300,
   x:`Limpia la sartén con papel. Baja a fuego medio-bajo, unos 150 °C (300 °F), y calienta {aceite:1/4}. Vierte la mitad de los huevos y deja 20 segundos, hasta que los bordes cuajen. Con una espátula empuja los bordes hacia el centro e inclina la sartén para que fluya el huevo líquido; repite 1 minuto. Cuando casi no haya líquido pero la superficie aún se vea brillante, esparce la mitad de las verduras y el queso sobre una mitad, dobla y tapa 30 segundos para que el queso se ablande. Repite con el resto. Haz 2 tortillas.`,
   add:{camarones:'Reparte los camarones junto con las verduras y el queso.'},
   cue:'La tortilla se despega sola al mover la sartén y tiene un color amarillo claro, sin partes doradas.',
   warn:'Seguridad: el huevo debe quedar totalmente cuajado, sin parte líquida, sobre todo para niños, embarazadas y adultos mayores. Deja 30 segundos más.'},
  {t:'Corta y sirve',time:'3 min',
   x:`Corta cada tortilla por la mitad. Abre las arepitas por el borde con un cuchillo, sin separarlas del todo, y sirve cada una con media tortilla al lado: son {N} porciones. Si quieres, acompaña con tomate en rodajas.`}],
 tools:'Sartén antiadherente de 26 cm (10 in), comal o segunda sartén, espátula de silicona, 2 bowls, tenedor, tabla y cuchillo, paño limpio.',
 tips:[
  ['Tortilla jugosa, no seca','El fuego medio-bajo es la clave. Con fuego alto la tortilla se dora, se pone gomosa y suelta agua.'],
  ['Familias mixtas','Haz la versión clásica completa. En otra sartén dora los camarones y agrégalos solo a las tortillas de quienes los quieren.'],
  ['Rinde el tiempo','Las arepitas se pueden dejar hechas la noche anterior: recalienta 2 minutos por lado en sartén seca.']],
 store:'La tortilla es mejor recién hecha. Se conserva 1 día en la nevera, recalentada 30 segundos en microondas a potencia media. Las arepitas duran 3 días en la nevera, bien envueltas.',
 swaps:['Queso fresco → requesón o queso mozzarella bajo en grasa.','Espinaca → acelga o kale picados finos.','Arepa → 2 tortillas de maíz pequeñas calentadas.','Champiñones → pimiento o calabacín picados.']},

{id:'tostada_hummus',meal:'Desayuno',cuisine:'Mediterránea',img:'tostada_hummus',
 title:'Tostada integral con hummus, huevo poché, tomate y rúcula',
 sub:'Una tostada crujiente con crema de garbanzos, tomate fresco y hojas de rúcula, coronada con un huevo de yema suave. Ligera, rápida y llena de sabor.',
 prep:10,cook:12,total:22,base:4,
 variants:[
  {id:'huevo',label:'Huevo poché',sub:'Sin mariscos',kcal:350,p:18,c:34,f:16,d:'1 huevo poché por persona sobre 2 rebanadas.'},
  {id:'salmon',label:'Salmón ahumado',sub:'Con pescado ahumado',sea:1,kcal:340,p:22,c:34,f:13,d:'Unas lonjas de salmón ahumado en lugar del huevo.'}],
 groups:[
  {g:'Base de la tostada',items:[
   ['pan',8,'',240,'g','rebanada~s de pan 100 % integral','pan integral','Rebanadas de unos 30 g. Mejor con semillas o de masa madre.',null,1],
   ['hummus',.75,'taza',180,'g','hummus (de garbanzos)','hummus','Comprado o casero. Revisa que no tenga demasiado aceite añadido.'],
   ['tomate',2,'',240,'g','tomate~s pequeño~s maduro~s','tomate~s','En rodajas de 5 mm (¼ in). Sazónalos con una pizca de sal 5 minutos antes.'],
   ['rucula',3,'taza',60,'g','rúcula (arúgula) baby','rúcula','Lavada y seca. Si le parece amarga a alguien, mezcla con espinaca.'],
   ['aceite',4,'cdta',20,'ml','aceite de oliva extra virgen','aceite de oliva','Para aliñar la rúcula.'],
   ['limon',1,'',60,'g','limón amarillo','limón','Su jugo va a la rúcula; el resto, en gajos para servir.'],
   ['sal',.5,'cdta',3,'g','sal fina','sal fina'],
   ['pimienta',.25,'cdta',.5,'g','pimienta negra recién molida','pimienta negra'],
   ['pimenton',.5,'cdta',1,'g','pimentón dulce','pimentón dulce','Un toque de color y sabor al final.']]},
  {g:'Huevos pochés',v:['huevo'],items:[
   ['huevos',4,'',200,'g','huevo~s muy fresco~s','huevo~s','Los frescos dejan la clara más compacta. Rómpelos en tazas aparte.',['huevo'],1],
   ['vinagre',1,'cda',15,'ml','vinagre blanco','vinagre blanco','Ayuda a que la clara se junte alrededor de la yema.',['huevo']]]},
  {g:'Salmón',v:['salmon'],items:[
   ['salmon',8,'oz',225,'g','salmón ahumado en lonjas','salmón ahumado','Es salado: ajusta la sal del resto.',['salmon'],.5]]}],
 steps:[
  {t:'Prepara las verduras',time:'6 min',
   x:`Lava y seca {rucula}. Corta {tomate} en rodajas de 5 mm (¼ in) y ponlas sobre papel de cocina con {sal:1/4} para que suelten agua. En un bowl pequeño mezcla {aceite} con el jugo de {limon:1/2} y {pimienta:1/2}. Saca {hummus} de la nevera para que esté más fácil de untar.`,
   cue:'Las rodajas de tomate están firmes y con un poco de líquido sobre el papel.'},
  {t:'Calienta el agua para pochar',time:'6 min',v:['huevo'],timer:360,
   x:`Llena una sartén honda o una olla ancha de 24–28 cm con unos 8 cm (3 in) de agua, y añade {vinagre} y {sal:1/4}. Calienta a fuego medio hasta que aparezcan burbujitas pequeñas en el fondo y el vapor suba, a unos 85–90 °C (185–195 °F). Baja el fuego para mantenerlo ahí, sin hervir fuerte.`,
   cue:'Burbujitas finas que se pegan al fondo, sin hervor fuerte.',
   warn:'Si el agua hierve con fuerza, los huevos se rompen y la clara se deshilacha.'},
  {t:'Tuesta el pan',time:'3 min',timer:150,
   x:`Tuesta {pan} en tostadora de 2 a 3 minutos, o en el horno a 200 °C (400 °F) sobre una bandeja durante 4 minutos, hasta que estén dorados y firmes. Colócalas en una rejilla para que no se humedezcan.`,
   cue:'Dorado parejo, crujiente al tocar y con aroma a pan tostado.'},
  {t:'Cocina los huevos pochés',time:'4 min',v:['huevo'],timer:210,
   x:`Rompe cada uno de {huevos} en una taza pequeña. Con una cuchara haz un remolino suave en el agua y desliza cada huevo cerca de la superficie. Cocina 3 minutos para yema suave, o 4 minutos para yema más firme. Retíralos con una espumadera y sécalos sobre papel.`,
   cue:'La clara está opaca y firme, y la yema se mueve como gelatina al tocar.',
   warn:'Seguridad: para niños, embarazadas y adultos mayores, cocínalos 4 minutos, hasta que la yema esté firme.'},
  {t:'Prepara el salmón',time:'2 min',v:['salmon'],
   x:`Separa las lonjas de {salmon} con cuidado y dóblalas en ondas sueltas. Déjalo en la nevera hasta el momento de armar.`,
   cue:'Las lonjas se ven brillantes y de color naranja intenso.',
   warn:'El pescado ahumado en frío no se recomienda a embarazadas ni a personas con defensas bajas; en esos casos elige la versión con huevo.'},
  {t:'Arma las tostadas',time:'4 min',
   x:v=>`Unta cada rebanada con una capa de 5 mm de {hummus}. Reparte las rodajas de tomate. Mezcla la rúcula con el aliño y colócala encima. ${v==='huevo'?'Corona cada par de tostadas con un huevo poché, y espolvorea con {pimenton} y un poco de pimienta.':'Pon encima las ondas de salmón y espolvorea con {pimenton}.'} Sirve {N} porciones de 2 tostadas, con gajos de limón al lado.`,
   cue:'La tostada se ve en capas y con el huevo o el salmón al centro.'}],
 tools:'Sartén honda u olla ancha, espumadera, 4 tazas pequeñas, tostadora o bandeja de horno, tabla y cuchillo.',
 tips:[
  ['Poché sin sorpresas','Si es tu primera vez, haz un huevo de prueba. También puedes colar el huevo antes en un colador fino para quitar la parte más líquida de la clara.'],
  ['Hummus casero rápido','Licúa 1½ tazas de garbanzos cocidos, 2 cucharadas de tahini, jugo de 1 limón, 1 diente de ajo y 3 cucharadas de agua fría.'],
  ['Para quien mastica poco','Parte la tostada en tiras finas o deja el pan solo ligeramente tostado para que no raspe.']],
 store:'Los ingredientes se guardan por separado. El hummus dura 4 días en la nevera. Los huevos pochés se pueden hacer con 1 día de antelación: guárdalos en agua fría y caliéntalos 30 segundos en agua caliente. La tostada armada se come en el momento.',
 swaps:['Hummus → puré de aguacate o requesón.','Rúcula → espinaca baby o berros.','Pan integral → arepa pequeña asada o tortilla de maíz.','Huevo poché → huevo cocido en rodajas.']},

{id:'burrito_frijoles',meal:'Desayuno',cuisine:'Latina / Tex-Mex',img:'burrito_frijoles',
 title:'Burrito de desayuno integral de frijoles negros, huevo revuelto y salsa fresca',
 sub:'Una tortilla integral rellena de frijoles negros cremosos, huevo revuelto y salsa fresca de tomate. Se come con la mano y se puede llevar al trabajo.',
 prep:15,cook:12,total:27,base:4,
 variants:[
  {id:'huevo',label:'Con huevo',sub:'Sin mariscos',kcal:395,p:17,c:41,f:18,d:'Huevo revuelto con verduras (1½ huevos por persona).'},
  {id:'tofu',label:'Con tofu revuelto',sub:'Vegana · sin mariscos',kcal:390,p:20,c:43,f:16,d:'Tofu firme desmenuzado con cúrcuma y levadura nutricional. Sin huevo ni lácteos.'}],
 groups:[
  {g:'Salsa fresca',items:[
   ['tomate',2,'',240,'g','tomate~s maduro~s','tomate~s','Sin semillas, en cubitos de 6 mm (¼ in).'],
   ['cebolla_roja',.25,'taza',40,'g','cebolla roja picada fina','cebolla roja','Si pica mucho, enjuágala 30 segundos en agua fría.'],
   ['cilantro',.25,'taza',8,'g','cilantro fresco picado','cilantro','Hojas y tallos tiernos.'],
   ['jalapeno',.5,'',8,'g','jalapeño sin semillas (opcional)','jalapeño','Omítelo si hay personas que no toleran el picante.'],
   ['limon',1,'',60,'g','limón verde (lima)','limón verde','Para la salsa; el resto va en gajos.']]},
  {g:'Relleno',items:[
   ['aceite',3,'cdta',15,'ml','aceite de oliva extra virgen','aceite de oliva','Se reparte entre sofrito y revuelto.'],
   ['cebolla',.5,'taza',80,'g','cebolla blanca picada','cebolla blanca','En cuadritos de 5 mm.'],
   ['pimiento',.5,'taza',80,'g','pimiento verde o rojo picado','pimiento','En cuadritos de 5 mm.'],
   ['ajo',2,'',6,'g','diente~s de ajo','ajo','Picado muy fino.'],
   ['comino',.5,'cdta',1,'g','comino molido','comino'],
   ['frijoles',1.25,'taza',215,'g','frijoles negros cocidos (de lata, escurridos y enjuagados)','frijoles negros','Enjuágalos 30 segundos para bajar el sodio.'],
   ['agua',3,'cda',45,'ml','agua','agua'],
   ['sal',.5,'cdta',3,'g','sal fina','sal fina','Se reparte entre salsa, sofrito y revuelto.'],
   ['pimienta',.25,'cdta',.5,'g','pimienta negra recién molida','pimienta negra']]},
  {g:'Huevos',v:['huevo'],items:[
   ['huevos',6,'',300,'g','huevo~s grande~s','huevo~s','A temperatura ambiente.',['huevo'],1]]},
  {g:'Tofu revuelto',v:['tofu'],items:[
   ['tofu',14,'oz',400,'g','tofu firme','tofu firme','Escurrido y presionado 10 minutos con papel.',['tofu']],
   ['curcuma',.5,'cdta',1.5,'g','cúrcuma molida','cúrcuma','Da el color amarillo.',['tofu']],
   ['levadura',4,'cda',20,'g','levadura nutricional (hojuelas)','levadura nutricional','Aporta sabor a queso sin lácteos. Es opcional.',['tofu']],
   ['pimenton',.5,'cdta',1,'g','pimentón ahumado','pimentón ahumado','',['tofu']]]},
  {g:'Para armar',items:[
   ['tortillas',4,'',180,'g','tortilla~s integral~es de harina de trigo (20 cm / 8 in)','tortilla~s integral~es','Revisa la etiqueta si es vegana: algunas llevan manteca o lácteos.',null,1],
   ['aguacate',1,'',120,'g','aguacate pequeño maduro','aguacate','En láminas de 5 mm.']]}],
 steps:[
  {t:'Prepara la salsa fresca',time:'10 min',timer:600,
   x:`Pica {tomate}, {cebolla_roja}, {cilantro} y {jalapeno}. Mezcla todo en un bowl con el jugo de {limon:1/2} y {sal:1/6}. Déjala macerar 10 minutos para que se integren los sabores.`,
   add:{tofu:'Mientras la salsa reposa, envuelve el tofu en papel de cocina, ponle un plato pesado encima y déjalo escurrir 10 minutos.'},
   cue:'La salsa suelta jugo y se ve brillante, con los sabores unidos.'},
  {t:'Sofríe las verduras y calienta los frijoles',time:'8 min',timer:420,
   x:`En una sartén de 26 cm (10 in), a fuego medio (unos 160 °C / 320 °F), calienta {aceite:1/3}. Añade {cebolla} y {pimiento} con {sal:1/6} y cocina 4 minutos, hasta que ablanden. Agrega {ajo}, {comino} y {pimienta} 30 segundos. Incorpora {frijoles} y {agua}; cocina 3 minutos y aplasta unos pocos con un tenedor para que la mezcla espese. Pasa a un bowl.`,
   cue:'Los frijoles se ven cremosos, con algunos granos enteros y un olor tostado a comino.',
   warn:'Si se pegan al fondo, añade 1 cucharada de agua y baja el fuego.'},
  {t:'Prepara el relleno proteico',time:'4 min',timer:210,
   x:v=>v==='huevo'
    ?`En la misma sartén, a fuego medio-bajo, calienta {aceite:2/3}. Bate {huevos} con {sal:1/6} y viértelos. Deja quietos 20 segundos y revuelve suave con una espátula, 2 minutos, hasta que estén cuajados pero cremosos. Retira del fuego cuando aún brillen un poco.`
    :`Desmenuza {tofu} con las manos o un tenedor en trozos pequeños. En la misma sartén, a fuego medio, calienta {aceite:2/3}, añade el tofu con {curcuma}, {pimenton} y {sal:1/6}. Cocina 3 minutos revolviendo y añade {levadura}; cocina 1 minuto más, hasta que se vea seco y amarillo.`,
   cue:'Huevo: pliegues cremosos sin líquido. Tofu: trozos amarillos que parecen huevo revuelto.',
   warn:'Seguridad: el huevo debe quedar cuajado. Para niños, embarazadas y adultos mayores, cocínalo 30 segundos más.'},
  {t:'Calienta las tortillas',time:'2 min',
   x:`Calienta {tortillas} una a una en una sartén seca a fuego medio, 20–30 segundos por lado, hasta que se vean flexibles y con pequeñas burbujas. O envuélvelas en papel de cocina húmedo y caliéntalas 30 segundos en el microondas.`,
   cue:'Se doblan sin romperse.',
   warn:'Las tortillas frías se agrietan al enrollar.'},
  {t:'Arma los burritos',time:'5 min',
   x:`Pela {aguacate} y córtalo en láminas. En el centro de cada tortilla, deja 2 cm libres en los bordes, coloca los frijoles, el relleno, la salsa escurrida y el aguacate. Dobla los lados hacia el centro y enrolla desde abajo, apretando. Colócalos con la unión hacia abajo.`,
   cue:'El burrito queda compacto, sin que el relleno se salga.'},
  {t:'Sella y sirve',time:'3 min',
   x:`Dora cada burrito 1 minuto por lado, con la unión hacia abajo primero, en sartén seca a fuego medio. Córtalos por la mitad en diagonal y sirve {N} porciones con el resto de la salsa y gajos del limón.`,
   cue:'Dorado ligero y sellado.'}],
 tools:'Sartén de 26 cm (10 in), espátula, tabla y cuchillo, 2 bowls, tenedor.',
 tips:[
  ['Burritos para llevar','Envuélvelos en papel aluminio o pergamino una vez enrollados para llevarlos al trabajo; se calientan en 1 minuto.'],
  ['No se rompe','No pongas demasiado relleno; una tortilla de 20 cm (8 in) aguanta unas 3/4 de taza.'],
  ['Más proteína','Agrega 2 claras extra al revuelto o 2 cdas de queso fresco por burrito (no vegano).']],
 store:'Los burritos armados se congelan hasta 1 mes envueltos individualmente. Descongela en la nevera y calienta 2 minutos en sartén. La salsa fresca dura 2 días en la nevera.',
 swaps:['Frijoles negros → frijoles rojos o pintos.','Tortilla integral → tortilla de maíz grande o de espinaca.','Pimiento → champiñones o espinaca.','Aguacate → un poco de yogur natural en la versión con huevo.']},

{id:'panqueques_avena',meal:'Desayuno',cuisine:'Americana',img:'panqueques_avena',
 title:'Panqueques de avena y banano con fresas y yogur',
 sub:'Panqueques suaves y esponjosos hechos con avena licuada y banano maduro, sin harina refinada ni azúcar añadida, servidos con fresas y yogur.',
 prep:10,cook:15,total:25,base:4,
 variants:[
  {id:'clasica',label:'Clásica',sub:'Con lácteos y huevo · sin mariscos',kcal:370,p:19,c:55,f:9,d:'Avena, banano, huevo y leche. 3 panqueques por persona.'},
  {id:'proteina',label:'Con proteína en polvo',sub:'Con lácteos y huevo · sin mariscos',kcal:430,p:31,c:56,f:10,d:'Con 2 medidas de proteína en polvo sabor vainilla, más líquido para compensar.'}],
 groups:[
  {g:'Masa de panqueques',items:[
   ['avena',2,'taza',160,'g','avena en hojuelas tradicionales','avena en hojuelas','Si hay personas celíacas, usa avena con sello sin gluten.'],
   ['bananos',2,'',240,'g','banano~s maduro~s (con manchas marrones)','banano~s','Pelados. Mientras más maduros, más dulces.'],
   ['huevos',3,'',150,'g','huevo~s grande~s','huevo~s','',null,1],
   ['leche',1,'taza',240,'ml','leche (o bebida vegetal sin azúcar)','leche','',['clasica']],
   ['leche',1.25,'taza',300,'ml','leche (o bebida vegetal sin azúcar)','leche','Un poco más de líquido, porque la proteína seca la masa.',['proteina']],
   ['proteina',8,'cda',60,'g','proteína en polvo sabor vainilla (2 medidas)','proteína en polvo','Opcional. Depende de la marca; usa 2 medidas de 30 g. Revisa que no tenga alérgenos para tu familia.',['proteina']],
   ['polvo',2,'cdta',8,'g','polvo de hornear','polvo de hornear','Que no esté vencido: si es viejo, los panqueques no esponjan.'],
   ['vainilla',1,'cdta',5,'ml','extracto de vainilla','vainilla'],
   ['canela',1,'cdta',2.4,'g','canela molida','canela'],
   ['sal',.25,'cdta',1.5,'g','sal fina','sal fina'],
   ['aceite',1,'cdta',5,'ml','aceite de oliva suave o de aguacate','aceite','Para engrasar la sartén.']]},
  {g:'Para servir',items:[
   ['yogur',1,'taza',240,'g','yogur griego natural sin azúcar','yogur griego','Frío, natural.'],
   ['fresas',2,'taza',300,'g','fresas frescas','fresas','Sin hojas, en láminas de 4 mm.'],
   ['maple',4,'cdta',20,'ml','miel de maple (opcional)','miel de maple','Una cucharadita por persona. Puedes omitirla.']]}],
 steps:[
  {t:'Licúa la masa',time:'4 min',
   x:v=>`En la licuadora pon ${v==='proteina'?'{leche}, {huevos}, {bananos}, {vainilla}, {canela}, {sal}, {polvo}, {proteina} y {avena}':'{leche}, {huevos}, {bananos}, {vainilla}, {canela}, {sal}, {polvo} y {avena}'}. Licúa a velocidad media 30 a 45 segundos, hasta que la masa quede lisa, con algunas motitas de avena. Raspa las paredes y licúa 10 segundos más.`,
   cue:'La masa se ve color crema, espesa, y cae de la cuchara en cinta gruesa.',
   warn:'No licúes más de 1 minuto: la masa se calienta y los panqueques quedan gomosos.'},
  {t:'Deja reposar la masa',time:'5 min',timer:300,
   x:`Vierte la masa en una jarra o bowl y déjala reposar 5 minutos: la avena absorbe líquido y la masa espesa. Si queda demasiado espesa, añade 1–2 cucharadas de leche.`,
   cue:'Al levantar la cuchara cae despacio y deja un rastro que tarda 2 segundos en deshacerse.'},
  {t:'Prepara las fresas y el yogur',time:'4 min',
   x:`Mientras reposa la masa, lava las {fresas}, quítales las hojitas y córtalas en láminas de 4 mm (⅙ in). Pon {yogur} en un bowl y reparte la {maple} en un plato pequeño para servir.`},
  {t:'Calienta la sartén',time:'3 min',timer:180,
   x:`Precalienta el horno a 90 °C (200 °F) para mantener tibios los panqueques. Calienta una sartén antiadherente de 26 cm (10 in) a fuego medio-bajo, unos 160–170 °C (325–340 °F), 3 minutos. Engrásala con {aceite} usando un papel.`,
   cue:'Una gota de agua “baila” unos segundos y se evapora.',
   warn:'Si el fuego está alto, los panqueques se queman por fuera y quedan crudos por dentro.'},
  {t:'Cocina los panqueques',time:'12 min',timer:150,
   x:`Vierte ¼ de taza (60 ml) de masa por panqueque; caben 3 o 4 por tanda. Cocina 2 a 3 minutos, hasta que aparezcan burbujas pequeñas y los bordes se vean secos. Voltea con una espátula y cocina 1½ a 2 minutos más. Pásalos a una bandeja en el horno. Repite hasta tener 12 panqueques, y vuelve a engrasar la sartén si hace falta.`,
   cue:'Dorado claro por ambos lados, y al presionar el centro regresa solo.',
   warn:'No los aplastes con la espátula: se pierde lo esponjoso. Si el primero sale pálido o se pega, ajusta el fuego antes de seguir.'},
  {t:'Sirve',time:'3 min',
   x:`Reparte 3 panqueques por persona ({N} platos). Corona con una parte del yogur, las fresas y un hilo de miel de maple.`,
   cue:'Se ven altos, esponjosos y con las fresas brillantes.'}],
 tools:'Licuadora, sartén antiadherente de 26 cm (10 in), espátula, bandeja de horno, tazas medidoras, tabla y cuchillo.',
 tips:[
  ['El primer panqueque','Suele salir peor: sirve de prueba para ajustar el fuego.'],
  ['Sin licuadora','Machaca los bananos con un tenedor y muele la avena en un procesador, o usa harina de avena.'],
  ['Para congelar','Deja enfriar, separa con papel y congela hasta 1 mes. Calienta en la tostadora.']],
 store:'Los panqueques cocidos duran 3 días en la nevera en un envase tapado y 1 mes en el congelador. La masa cruda se puede guardar 1 día en la nevera, pero pierde esponjosidad.',
 swaps:['Fresas → arándanos o durazno en rodajas.','Banano → 1 taza de puré de manzana sin azúcar o de calabaza.','Yogur griego → yogur de soya natural sin azúcar.','Leche → bebida de avena o almendra sin azúcar.']}
];
