// @ts-nocheck
// Recetas adicionales: almuerzos
export const ALMUERZOS=[
// ───────────────────────────── 1. ENSALADA GRIEGA CON POLLO ─────────────────────────────
{id:'ensalada_griega_pollo',meal:'Almuerzo',cuisine:'Mediterránea',img:'ensalada_griega_pollo',
 title:'Ensalada griega con pollo a la plancha y garbanzos crujientes',
 sub:'Pepino, tomate, aceitunas y queso feta con un aderezo de limón y orégano. La proteína va encima: pollo jugoso o una montaña de garbanzos crujientes al horno.',
 prep:25,cook:35,total:60,base:4,
 variants:[
  {id:'pollo',label:'Con pollo',sub:'Sin mariscos',kcal:460,p:43,c:26,f:21,d:'Pechuga marinada con limón y orégano, más un puñado de garbanzos crujientes.'},
  {id:'garbanzos',label:'Solo garbanzos',sub:'Vegetariana',kcal:460,p:19,c:52,f:19,d:'Garbanzos crujientes como proteína principal. Tiene menos proteína que la versión con pollo.'}],
 groups:[
  {g:'Pollo a la plancha',v:['pollo'],items:[
   ['pollo',1.25,'lb',565,'g','pechuga de pollo sin piel ni hueso (o muslo deshuesado)','pechuga de pollo','Aplánala a 2 cm (¾ in) de grosor para que se cocine pareja.',null,.25],
   ['aceite_p',1,'cda',15,'ml','aceite de oliva extra virgen','aceite de oliva'],
   ['jugo_p',2,'cda',30,'ml','jugo de limón fresco','jugo de limón','De 1 limón grande. El resto del jugo va en el aderezo.'],
   ['ajo_p',2,'',6,'g','diente~s de ajo','diente~s de ajo','Rallados finos.'],
   ['oregano_p',1,'cdta',1,'g','orégano seco','orégano','Frótalo entre las palmas para despertar el aroma.'],
   ['sal_p',.5,'cdta',3,'g','sal fina','sal fina'],
   ['pimienta_p',.25,'cdta',.5,'g','pimienta negra molida','pimienta negra']]},
  {g:'Garbanzos crujientes',items:[
   ['garb',1,'',240,'g','lata~s de garbanzos cocidos (425 g / 15 oz cada una, escurridos)','lata~s de garbanzos','Enjuágalos y sécalos muy bien: la humedad impide que se pongan crujientes.',['pollo']],
   ['garb',3,'',720,'g','lata~s de garbanzos cocidos (425 g / 15 oz cada una, escurridos)','lata~s de garbanzos','Enjuágalos y sécalos muy bien: la humedad impide que se pongan crujientes. Necesitarás dos bandejas.',['garbanzos']],
   ['aceite_g',1,'cda',15,'ml','aceite de oliva extra virgen','aceite de oliva',null,['pollo']],
   ['aceite_g',2,'cda',30,'ml','aceite de oliva extra virgen','aceite de oliva',null,['garbanzos']],
   ['pimenton',1,'cdta',2.5,'g','pimentón dulce (o ahumado)','pimentón'],
   ['oregano_g',1,'cdta',1,'g','orégano seco','orégano'],
   ['ajo_polvo',.5,'cdta',1.5,'g','ajo en polvo','ajo en polvo'],
   ['sal_g',.25,'cdta',1.5,'g','sal fina','sal fina']]},
  {g:'Ensalada',items:[
   ['lechuga',6,'taza',280,'g','lechuga romana en trozos','lechuga romana','Lavada y bien seca, en trozos del tamaño de un bocado.'],
   ['pepino',1,'',300,'g','pepino inglés grande','pepino','En medias lunas de 1 cm (⅜ in); sin pelar si la cáscara es fina.'],
   ['tomates',2,'taza',300,'g','tomates cherry','tomates cherry','Cortados a la mitad.'],
   ['pimiento',1,'',150,'g','pimiento verde mediano','pimiento verde','En tiras finas, sin semillas.'],
   ['cebolla',.5,'',60,'g','cebolla morada pequeña','cebolla morada','En medias lunas muy finas.'],
   ['aceitunas',.5,'taza',75,'g','aceitunas Kalamata sin hueso','aceitunas','Cortadas a la mitad. Son saladas: no añadas más sal a la ensalada.'],
   ['feta',.5,'taza',75,'g','queso feta desmenuzado','queso feta','Opcional. Sin él la ensalada queda más ligera y sin lácteos.']]},
  {g:'Aderezo de limón y orégano',items:[
   ['aceite_a',3,'cda',45,'ml','aceite de oliva extra virgen','aceite de oliva'],
   ['jugo_a',3,'cda',45,'ml','jugo de limón fresco','jugo de limón'],
   ['vinagre',1,'cda',15,'ml','vinagre de vino tinto','vinagre de vino tinto'],
   ['oregano_a',1,'cdta',1,'g','orégano seco','orégano'],
   ['ajo_a',1,'',3,'g','diente~s de ajo pequeño~s','diente~s de ajo','Rallado fino.'],
   ['mostaza',1,'cdta',5,'g','mostaza Dijon','mostaza Dijon','Ayuda a que el aderezo no se separe.'],
   ['sal_a',.25,'cdta',1.5,'g','sal fina','sal fina']]}],
 steps:[
  {t:'Precalienta el horno',time:'10 min',timer:600,
   x:`Coloca la rejilla en el centro y precalienta el horno a 220 °C (425 °F) con una bandeja grande adentro (dos bandejas si vas a hornear mucha cantidad de garbanzos). Una bandeja caliente dora los garbanzos mucho más rápido y les da el crujido.`,
   cue:'El horno está listo cuando el aviso de temperatura se apaga; espera 2 minutos extra para que la bandeja se caliente de verdad.'},
  {t:'Seca los garbanzos',time:'8 min',
   x:`Escurre {garb} en un colador y enjuágalos con agua fría. Extiéndelos sobre un paño de cocina limpio, cúbrelos con otro paño y presiona suavemente para quitar el agua. Si algunas pieles se sueltan, déjalas: se vuelven crujientes. Deja los garbanzos secar al aire 5 minutos mientras avanzas.`,
   cue:'Al tocarlos se sienten secos y mate, sin brillo de agua. Si siguen mojados, el horno los cocina al vapor en vez de dorarlos.'},
  {t:'Marina el pollo',time:'5 min + 20 min de reposo',v:['pollo'],timer:1200,
   x:`Pon {pollo} entre dos láminas de papel film o papel de horno y golpéalo con un rodillo o el fondo de una sartén hasta que mida unos 2 cm (¾ in) de grosor parejo. Sécalo con papel. En un bowl mezcla {aceite_p}, {jugo_p}, {ajo_p}, {oregano_p}, {sal_p} y {pimienta_p}. Agrega el pollo y voltéalo hasta cubrirlo por completo. Tapa y refrigera 20 minutos (máximo 2 horas: el limón en exceso deja la carne harinosa).`,
   cue:'El pollo queda de grosor parejo, sin una punta más gruesa, y brillante por la marinada.',
   warn:'Seguridad: marina siempre en la nevera, nunca sobre la encimera, y lávate las manos y la tabla después de tocar el pollo crudo.'},
  {t:'Hornea los garbanzos',time:'25–30 min',timer:1500,
   x:`En un bowl mezcla los garbanzos secos con {aceite_g}, {pimenton}, {oregano_g}, {ajo_polvo} y {sal_g}. Con guantes de horno saca la bandeja caliente, extiende los garbanzos en una sola capa sin amontonar y hornea 25–30 minutos, sacudiendo la bandeja a los 12 minutos para que doren parejos. Al sacarlos, déjalos 3 minutos sobre la bandeja: terminan de endurecerse al enfriarse.`,
   cue:'Suenan como maracas al sacudir la bandeja, están dorado oscuro y con la piel un poco arrugada. Por dentro quedan tiernos y por fuera crujen.',
   warn:'La bandeja y el aceite están a más de 200 °C: usa guantes de horno y abre el horno alejando la cara por el vapor.'},
  {t:'Corta las verduras',time:'12 min',timer:600,
   x:`Remoja {cebolla} en un bowl con agua helada 10 minutos para quitarle el picor. Mientras tanto corta {pepino}, {pimiento} y {tomates}, y pon en un bowl grande {lechuga}. Escurre la cebolla, sécala con un paño y agrégala al bowl junto con {aceitunas}. No aliñes todavía: la sal del aderezo suelta agua de las verduras si se mezcla con demasiada anticipación.`,
   cue:'La cebolla se ve ligeramente translúcida, crujiente y con un olor mucho más suave.'},
  {t:'Prepara el aderezo',time:'5 min',
   x:`En un frasco con tapa agrega {aceite_a}, {jugo_a}, {vinagre}, {oregano_a}, {ajo_a}, {mostaza} y {sal_a}. Cierra y agita 20 segundos. Prueba con una hoja de lechuga: debe saber vivo, ácido y aromático.`,
   cue:'El aderezo se ve cremoso y parejo, sin capas de aceite. Si está muy ácido, agrega 1 cdta. de agua; si está plano, una pizca de orégano.'},
  {t:'Cocina el pollo',time:'12 min',v:['pollo'],timer:720,
   x:`Calienta una sartén grande o plancha a fuego medio-alto durante 3 minutos. Saca el pollo de la marinada y deja escurrir el exceso: si hay mucho líquido, el pollo hierve en vez de dorarse. Cocínalo 5–6 minutos por lado, sin moverlo los primeros 4, hasta que se forme una costra dorada. Pásalo a una tabla y déjalo reposar 5 minutos sin cortar.`,
   cue:'Se despega solo de la sartén cuando está dorado; si se pega, dale 1 minuto más. Al cortarlo, el jugo sale transparente y la carne es blanca, sin zonas rosadas.',
   warn:'Seguridad: la parte más gruesa debe marcar 74 °C (165 °F) con termómetro. Desecha la marinada que tocó el pollo crudo.'},
  {t:'Arma la ensalada',time:'6 min',
   x:v=>`Aliña las verduras con dos tercios del aderezo y mezcla con las manos o dos cucharones, con cuidado de no aplastar el tomate. Reparte la ensalada en {N} platos hondos. ${v==='pollo'?'Rebana el pollo contra la fibra en tiras de 1 cm (⅜ in) y colócalo encima de cada plato. Por último, agrega los garbanzos crujientes como topping.':'Reparte los garbanzos crujientes abundantes encima de cada plato: son la proteína de la receta.'} Termina con {feta} desmenuzado y un chorrito del aderezo restante.`,
   cue:'Un plato bien armado tiene mitad verduras, y una buena porción de proteína visible encima. Come los garbanzos pronto, pues pierden el crujido con el aderezo.'}],
 tools:'Horno, 1–2 bandejas de horno, sartén grande o plancha, termómetro de cocina, rodillo (o sartén pesada) para aplanar, frasco con tapa, colador, bowl grande, rallador fino.',
 tips:[
  ['Garbanzos secos = garbanzos crujientes','Sécalos con paño, no con papel (se pega), y no los amontones: si se tocan entre sí, se cuecen al vapor. Si necesitas más espacio, usa dos bandejas.'],
  ['Aderezo que dura','Hazlo con 3 días de anticipación: se guarda en el frasco en la nevera. Saca el frasco 10 minutos antes y agítalo, porque el aceite de oliva se solidifica con el frío.'],
  ['Para toda la familia','Cocina el pollo y los garbanzos por separado y deja que cada quien arme su plato. A la persona mayor, córtale el pollo en trocitos y ofrécele los garbanzos aplastados con un tenedor, o el pollo con las verduras bien picadas.']],
 store:'Pollo cocido: 4 días en la nevera, mejor frío sobre la ensalada o recalentado con 1 cda. de agua, tapado, en el microondas hasta que humee. Garbanzos: 1 día en un recipiente sin cerrar herméticamente; para devolverles el crujido, 5 minutos en horno a 200 °C (400 °F). Verduras cortadas y aderezo: separados, 3 días.',
 swaps:['Queso feta → queso fresco desmenuzado o 2 cdas. de yogur griego por plato.','Pollo → pavo en filetes o tofu extra firme dorado (sin lácteos).','Lechuga romana → espinaca baby o rúcula.','Vinagre de vino tinto → 1 cda. extra de jugo de limón.']},

// ───────────────────────────── 2. SOPA ESPESA DE LENTEJAS ─────────────────────────────
{id:'sopa_lentejas',meal:'Almuerzo',cuisine:'Latina casera',img:'sopa_lentejas',
 title:'Sopa espesa de lentejas con zanahoria, espinaca y limón',
 sub:'Una sopa caliente y reconfortante, con las lentejas tiernas y el caldo espeso, que se sirve con un arroz integral pequeño. Un toque de limón al final la despierta.',
 prep:15,cook:55,total:70,base:4,
 variants:[
  {id:'vegetariana',label:'Vegetariana',sub:'Sin carne',kcal:465,p:20,c:81,f:7,d:'Solo verduras y lentejas. Es vegana si usas caldo de verduras.'},
  {id:'pavo',label:'Con pavo ahumado',sub:'Con jamón de pavo',kcal:530,p:30,c:82,f:9,d:'Cubos de jamón de pavo bajo en sodio, dorados en sartén.'}],
 groups:[
  {g:'Arroz integral pequeño',items:[
   ['arroz',.75,'taza',140,'g','arroz integral','arroz integral','Enjuágalo bajo agua fría. Tarda más que la sopa, así que empieza por él.'],
   ['agua_a',1.5,'taza',355,'ml','agua','agua'],
   ['sal_a',.25,'cdta',1.5,'g','sal fina','sal fina']]},
  {g:'Sopa',items:[
   ['lentejas',1.25,'taza',250,'g','lentejas pardas o verdes secas','lentejas','No uses lentejas rojas: se deshacen. No necesitan remojo; sí enjuagarlas y revisar que no tengan piedritas.'],
   ['aceite',1.5,'cda',22,'ml','aceite de oliva','aceite de oliva'],
   ['cebolla',1,'',150,'g','cebolla~s amarilla~s mediana~s','cebolla~s','En cubos de 5 mm (¼ in).'],
   ['ajo',4,'',12,'g','diente~s de ajo','diente~s de ajo','Picados finos.'],
   ['zanahoria',3,'',270,'g','zanahoria~s mediana~s','zanahoria~s','En cubos de 1 cm (⅜ in), sin pelar si están limpias.'],
   ['apio',2,'',100,'g','tallo~s de apio','tallo~s de apio','En medias lunas finas.'],
   ['tomate',2,'',260,'g','tomate~s maduro~s','tomate~s','Rallados con el lado grueso del rallador; desecha la cáscara.'],
   ['comino',1,'cdta',2.5,'g','comino molido','comino'],
   ['pimenton',1,'cdta',2.5,'g','pimentón ahumado','pimentón ahumado','Es lo que da el toque “a leña” en la versión vegetariana.'],
   ['laurel',2,'',1,'g','hoja~s de laurel','hoja~s de laurel'],
   ['caldo',8,'taza',1900,'ml','caldo de verduras bajo en sodio (o agua)','caldo de verduras','Si usas agua, súmale 1 cdta. extra de sal al final.'],
   ['pavo',8,'oz',225,'g','jamón de pavo bajo en sodio o pechuga de pavo ahumada','jamón de pavo','En cubos de 1 cm (⅜ in). Ya trae sal: prueba antes de salar.',['pavo']],
   ['espinaca',4,'taza',120,'g','espinaca baby o hojas grandes sin tallo','espinaca','Lavada; si son hojas grandes, rómpelas en trozos.'],
   ['sal',1,'cdta',6,'g','sal fina','sal fina','Empieza con ¾ cdta. y ajusta al probar.'],
   ['pimienta',.5,'cdta',1,'g','pimienta negra molida','pimienta negra'],
   ['jugo',3,'cda',45,'ml','jugo de limón fresco','jugo de limón','De 1½ limones, al final de la cocción.'],
   ['cilantro',.25,'taza',12,'g','cilantro o perejil fresco picado','cilantro']]}],
 steps:[
  {t:'Pon a cocinar el arroz',time:'50 min, casi sin esfuerzo',timer:2400,
   x:`Enjuaga {arroz} en un colador fino bajo agua fría, frotando con la mano. En una olla pequeña hierve {agua_a} con {sal_a}, agrega el arroz, tapa y baja el fuego al mínimo. Cocina 40 minutos sin destapar. Apaga el fuego y déjalo tapado otros 10 minutos; luego esponja con un tenedor.`,
   cue:'Los granos están tiernos pero con un ligero mordisco, y el agua se absorbió por completo.',
   warn:'Si el arroz quedó duro y ya no hay agua, agrega 2 cdas. de agua caliente, tapa y cocina 5 minutos más.'},
  {t:'Prepara las verduras y las lentejas',time:'15 min',
   x:`Pon {lentejas} en un colador, enjuágalas con agua fría y revisa que no queden piedritas ni lentejas arrugadas. Corta {cebolla} en cubitos de 5 mm, {zanahoria} en cubos de 1 cm, {apio} en medias lunas finas y pica {ajo}. Ralla {tomate} con el lado grueso del rallador hasta quedarte solo con la cáscara en la mano.`,
   cue:'Los cortes parejos garantizan que todo se cocine al mismo tiempo; la zanahoria no debe ser más grande que el dedo meñique.'},
  {t:'Sofríe la base',time:'10 min',timer:600,
   x:`En una olla grande (4–5 L / 4–5 qt) calienta {aceite} a fuego medio. Agrega la cebolla, el apio, la zanahoria y una pizca de sal. Cocina 6–7 minutos, moviendo cada minuto, hasta que la cebolla esté translúcida. Añade el ajo y cocina 1 minuto. Incorpora {comino} y {pimenton} y revuelve 30 segundos. Agrega el tomate rallado y cocina 3 minutos más.`,
   cue:'La cebolla está suave y transparente, sin dorar, y el tomate se reduce a una pasta oscura que se despega del fondo.',
   warn:'Si el ajo o las especias se oscurecen y huelen amargo, baja el fuego y agrega 2 cdas. de caldo para frenar la cocción.'},
  {t:'Cocina las lentejas',time:'35–40 min',timer:2100,
   x:`Agrega las lentejas, {caldo} y {laurel}. Sube el fuego hasta que hierva, retira la espuma de la superficie con una cuchara, baja el fuego a bajo y deja tapado parcialmente, con una rendija. Cocina 30–35 minutos, moviendo a los 15 minutos para que no se peguen en el fondo.`,
   cue:'Las lentejas se aplastan fácilmente con la cuchara pero siguen enteras, y el caldo se ve algo espeso, de color terracota.',
   warn:'No agregues limón, vinagre ni más tomate ahora: el ácido retrasa que las lentejas se ablanden. El limón va al final.'},
  {t:'Dora el jamón de pavo',time:'5 min',v:['pavo'],timer:240,
   x:`Mientras las lentejas terminan, calienta una sartén antiadherente a fuego medio-alto, sin aceite. Agrega {pavo} y cocina 3–4 minutos, moviendo, hasta que los bordes se doren ligeramente. Pásalo a la sopa durante los últimos 5 minutos de cocción de las lentejas.`,
   cue:'Los cubitos se ven dorados en los bordes y huele a ahumado.',
   warn:'El jamón de pavo ya trae sal: no salas la sopa hasta probarla en el paso final.'},
  {t:'Espesa la sopa',time:'5 min',
   x:`Retira las hojas de laurel. Con el reverso de un cucharón o un machacador, aplasta unas 2 tazas de lentejas y verduras contra la pared de la olla; esto espesa el caldo sin necesidad de harina. Si prefieres una textura más cremosa, usa una licuadora de inmersión 3–4 pulsos directamente en la olla, cuidando que queden trozos.`,
   cue:'El caldo debe cubrir el dorso de una cuchara y caer en un hilo lento, sin ser puré.',
   warn:'Si licúas en una licuadora normal, llena solo la mitad del vaso y deja salir el vapor por la tapa para evitar salpicaduras de líquido hirviendo.'},
  {t:'Termina con espinaca y limón',time:'5 min',timer:120,
   x:`Con la sopa a fuego bajo, agrega {espinaca} en puñados y deja cocinar 2 minutos, hasta que se marchite. Apaga el fuego. Agrega {sal} (empieza con ¾ de la cantidad), {pimienta}, {jugo} y {cilantro}. Prueba y ajusta.`,
   cue:'Debe saber sabrosa y con un fondo fresco por el limón; si te falta “algo”, casi siempre es sal o limón.'},
  {t:'Sirve con el arroz',time:'3 min',
   x:`Reparte la sopa en {N} platos hondos bien calientes. Sirve el arroz integral en un bowl aparte para que cada persona lo ponga dentro de la sopa o al lado, según le guste. Si no hay arroz, acompaña con una rebanada de pan integral tostado.`,
   cue:'La sopa debe servirse muy caliente, humeando, pero sin quemar: espera 2 minutos antes de comer.',
   warn:'Para la adulta mayor, sirve la sopa tibia (no hirviendo) y pregúntale si prefiere las lentejas más aplastadas.'}],
 tools:'Olla grande (4–5 L / 4–5 qt) con tapa, olla pequeña con tapa para el arroz, colador fino, rallador, tabla y cuchillo, cucharón y machacador (o licuadora de inmersión), sartén antiadherente (versión con pavo).',
 tips:[
  ['Sopa más espesa al día siguiente','Las lentejas siguen absorbiendo líquido en la nevera. Al recalentar, agrega ½ taza (120 ml) de agua o caldo por cada 2 porciones.'],
  ['Sal al final','Las lentejas no se endurecen por la sal, pero el ácido sí las frena: agrega limón y tomate en la secuencia indicada y verás lentejas tiernas siempre.'],
  ['Arroz pequeño, saciedad grande','Las lentejas ya aportan fibra y proteína; el arroz es un acompañamiento pequeño. Si tienes prisa, usa arroz integral precocido o pan integral.']],
 store:'Sopa: 4 días en la nevera en recipiente tapado, o 3 meses en el congelador en porciones (sin espinaca, si es posible). Recalienta a fuego medio con un chorrito de agua hasta que humee y hierva suavemente. Arroz cocido: 4 días en la nevera; recalienta con 1 cda. de agua, tapado, en el microondas.',
 swaps:['Lentejas pardas → lentejas verdes francesas (tardan unos 5 minutos más).','Arroz integral → quinoa, fideos de trigo integral o una rebanada de pan integral.','Espinaca → acelga o col rizada sin tallo (cocina 5 minutos).','Jamón de pavo → pechuga de pollo desmenuzada ya cocida (agrega 1 taza al final).']},

// ───────────────────────────── 3. TACOS DE POLLO CON REPOLLO ─────────────────────────────
{id:'tacos_pollo_repollo',meal:'Almuerzo',cuisine:'Latina / mexicana',img:'tacos_pollo_repollo',
 title:'Tacos de pollo con repollo morado y salsa de aguacate',
 sub:'Pollo desmenuzado y jugoso en tortilla de maíz tibia, con un repollo morado crujiente y una salsa cremosa de aguacate y limón. Sale en media hora y se arma en la mesa.',
 prep:20,cook:30,total:50,base:4,
 variants:[
  {id:'pollo',label:'Con pollo',sub:'Sin mariscos',kcal:445,p:33,c:46,f:14,d:'Pechuga cocida en caldo aromático, desmenuzada y dorada con especias.'},
  {id:'camarones',label:'Con camarones',sub:'Con mariscos',sea:1,kcal:440,p:35,c:46,f:13,d:'Camarones grandes marinados 10 minutos y salteados.'}],
 groups:[
  {g:'Pollo desmenuzado',v:['pollo'],items:[
   ['pollo',1,'lb',450,'g','pechuga de pollo sin piel ni hueso','pechuga de pollo','Si una pieza es muy gruesa, córtala a lo largo en dos para que se cocine pareja.',null,.25],
   ['agua_p',3,'taza',710,'ml','agua para cocer el pollo','agua','Debe cubrir el pollo por 2 cm (¾ in).'],
   ['cebolla_p',.5,'',75,'g','cebolla~s blanca~s','cebolla','En dos trozos grandes, solo para el caldo.'],
   ['ajo_p',3,'',9,'g','diente~s de ajo','diente~s de ajo','Aplastados con la palma del cuchillo.'],
   ['laurel',1,'',1,'g','hoja~s de laurel','hoja~s de laurel'],
   ['sal_p',.5,'cdta',3,'g','sal fina','sal fina'],
   ['comino_p',1,'cdta',2.5,'g','comino molido','comino'],
   ['pimenton_p',1,'cdta',2.5,'g','pimentón ahumado (o dulce)','pimentón'],
   ['chile',.5,'cdta',1.5,'g','chile en polvo suave','chile en polvo','Opcional. Omítelo si alguien no tolera el picante.'],
   ['jugo_p',2,'cda',30,'ml','jugo de lima o limón','jugo de lima'],
   ['aceite_p',1,'cda',15,'ml','aceite de oliva','aceite de oliva']]},
  {g:'Camarones sazonados',v:['camarones'],items:[
   ['camaron',1.25,'lb',565,'g','camarones grandes (21/25), pelados y desvenados','camarones','Sécalos con papel antes de marinar.',null,.25],
   ['aceite_c',1,'cda',15,'ml','aceite de oliva','aceite de oliva'],
   ['ajo_c',2,'',6,'g','diente~s de ajo','diente~s de ajo','Rallados finos.'],
   ['comino_c',1,'cdta',2.5,'g','comino molido','comino'],
   ['pimenton_c',1,'cdta',2.5,'g','pimentón ahumado (o dulce)','pimentón'],
   ['chile_c',.5,'cdta',1.5,'g','chile en polvo suave','chile en polvo','Opcional.'],
   ['sal_c',.5,'cdta',3,'g','sal fina','sal fina'],
   ['jugo_c',1,'cda',15,'ml','jugo de lima','jugo de lima']]},
  {g:'Repollo morado',items:[
   ['repollo',4,'taza',280,'g','repollo morado finamente rebanado','repollo morado','En tiras de 2–3 mm, con cuchillo muy afilado o mandolina.'],
   ['jugo_r',3,'cda',45,'ml','jugo de lima fresco','jugo de lima','De 2 limas.'],
   ['sal_r',.25,'cdta',1.5,'g','sal fina','sal fina'],
   ['cilantro',.5,'taza',25,'g','cilantro fresco picado','cilantro','Hojas y tallos tiernos.'],
   ['jalapeno',.5,'',15,'g','jalapeño~s sin semillas','jalapeño','Opcional; en cubitos mínimos.']]},
  {g:'Salsa de aguacate y limón',items:[
   ['aguacate',1,'',200,'g','aguacate~s Hass grande~s maduro~s (unos 200 g de pulpa)','aguacate','Debe ceder un poco al presionar suavemente.'],
   ['yogur',.5,'taza',120,'g','yogur griego natural sin azúcar','yogur griego','Lo hace más cremosa con menos grasa.'],
   ['jugo_s',3,'cda',45,'ml','jugo de limón verde','jugo de limón'],
   ['cilantro_s',.25,'taza',12,'g','cilantro fresco','cilantro'],
   ['ajo_s',1,'',3,'g','diente~s de ajo','diente~s de ajo','Rallado fino.'],
   ['sal_s',.5,'cdta',3,'g','sal fina','sal fina'],
   ['agua_s',3,'cda',45,'ml','agua fría','agua fría','Para aflojar la textura.']]},
  {g:'Para servir',items:[
   ['tortillas',12,'',312,'g','tortilla~s de maíz (de 15 cm / 6 in)','tortilla~s de maíz','3 por persona. Verifica la etiqueta si alguien evita el gluten.',null,1],
   ['limas',2,'',100,'g','lima~s en cuñas','lima~s','Para exprimir sobre cada taco.']]}],
 steps:[
  {t:'Cocina el pollo en caldo aromático',time:'25 min',v:['pollo'],timer:1500,
   x:`En una olla mediana coloca {pollo}, {agua_p}, {cebolla_p}, {ajo_p}, {laurel} y {sal_p}. Lleva a hervor suave, baja el fuego, tapa y cocina 15–18 minutos, hasta que no quede nada rosado. Apaga el fuego y déjalo reposar 5 minutos dentro del caldo para que quede jugoso.`,
   cue:'Al pincharlo con un cuchillo sale jugo transparente y la carne es blanca por dentro.',
   warn:'Seguridad: la parte más gruesa debe marcar 74 °C (165 °F) con termómetro. No dejes que hierva con fuerza: el pollo se pone seco y fibroso.'},
  {t:'Sazona los camarones',time:'10 min de reposo',v:['camarones'],timer:600,
   x:`Seca los {camaron} con papel de cocina. En un bowl mézclalos con {aceite_c}, {ajo_c}, {comino_c}, {pimenton_c}, {chile_c}, {sal_c} y {jugo_c}. Tapa y refrigera 10 minutos (no más de 15: el ácido empieza a “cocinar” el camarón y lo pone gomoso).`,
   cue:'Los camarones se ven parejos, cubiertos de especias y sin charcos de líquido.'},
  {t:'Desmenuza el pollo',time:'5 min',v:['pollo'],
   x:`Pasa el pollo a un plato y deja enfriar 3 minutos para poder tocarlo. Desmenúzalo con dos tenedores en hebras finas. Humedécelo con 3 cdas. del caldo de cocción y reserva el resto del caldo para otra sopa.`,
   cue:'Las hebras son finas y suaves; si se secan, agrega otra cucharada de caldo.'},
  {t:'Dora el pollo con especias',time:'6 min',v:['pollo'],timer:360,
   x:`Calienta {aceite_p} en una sartén grande a fuego medio-alto. Agrega el pollo desmenuzado, {comino_p}, {pimenton_p} y {chile}. Cocina 4–5 minutos moviendo cada minuto, hasta que se evapore el líquido y los bordes se doren un poco. Apaga, agrega {jugo_p} y revuelve.`,
   cue:'El pollo está seco al tacto, con algunos bordes dorados y un olor ahumado y cálido.',
   warn:'Si las especias se oscurecen enseguida, baja el fuego: se queman con facilidad.'},
  {t:'Prepara el repollo',time:'12 min',timer:600,
   x:`En un bowl grande mezcla {repollo} con {jugo_r}, {sal_r}, {cilantro} y {jalapeno}. Masajea con las manos 1 minuto, hasta que el repollo se ablande y suelte color. Déjalo reposar mínimo 10 minutos para que se “cocine” en el limón.`,
   cue:'El repollo se vuelve de un morado vivo, brillante, más suave y todavía crujiente.'},
  {t:'Licúa la salsa de aguacate',time:'5 min',
   x:`Abre {aguacate}, saca la pulpa y colócala en la licuadora (o procesador) junto con {yogur}, {jugo_s}, {cilantro_s}, {ajo_s}, {sal_s} y {agua_s}. Licúa 30–40 segundos hasta que quede lisa y cremosa. Prueba y ajusta con más limón o sal. Si no tienes licuadora, aplástalo con un tenedor y mezcla con el resto de los ingredientes.`,
   cue:'La textura debe ser como una crema espesa, que caiga de la cuchara en cinta lenta, de color verde claro.',
   warn:'Tápala con film pegado a la superficie y refrigérala: el aguacate se oxida si queda en contacto con el aire.'},
  {t:'Saltea los camarones',time:'4 min',v:['camarones'],timer:200,
   x:`Calienta una sartén grande a fuego alto 2–3 minutos, hasta que una gota de agua salte y desaparezca. Agrega los camarones en una sola capa (en dos tandas si no caben). Cocina 90 segundos sin moverlos, voltéalos y cocina 45–60 segundos más. Pásalos de inmediato a un plato y córtalos en 2–3 trozos.`,
   cue:'Forman una “C” abierta, rosados y opacos. Una “O” cerrada significa que se pasaron y quedarán gomosos.'},
  {t:'Calienta las tortillas',time:'5 min',
   x:`Calienta una sartén seca, de hierro o plancha, a fuego medio. Calienta cada tortilla 30–40 segundos por lado, hasta que se ablande y aparezcan manchitas doradas. Apílalas envueltas en un paño limpio: el vapor las mantiene flexibles y no se quiebran.`,
   cue:'La tortilla se infla ligeramente y se dobla sin romperse.',
   warn:'Si usas una llama directa, no dejes la tortilla sin vigilar y usa pinzas para voltearla.'},
  {t:'Arma los tacos',time:'5 min',
   x:v=>`Coloca 3 tortillas en cada plato. Reparte ${v==='pollo'?'el pollo desmenuzado':'los camarones'} en el centro, cubre con repollo morado escurrido y termina con una cucharada generosa de salsa de aguacate. Sirve con {limas} para exprimir encima y {tortillas} calientes en el centro de la mesa.`,
   cue:'No sobrecargues la tortilla: con 2–3 cucharadas de relleno se doblan sin romperse.'}],
 tools:'Olla mediana con tapa (pollo), sartén grande o plancha, licuadora o procesador, termómetro de cocina, tabla y cuchillo afilado, dos tenedores, paño limpio para las tortillas.',
 tips:[
  ['Tortillas que no se rompen','Caliéntalas justo antes de servir y mantenlas envueltas en un paño: el vapor las vuelve flexibles. Las tortillas frías o secas se quiebran al doblar.'],
  ['Pollo jugoso','No lo cocines a hervor fuerte y déjalo reposar dentro del caldo. Si se te pasó de cocción, el caldo tibio que reservas lo hidrata en 1 minuto.'],
  ['Para la adulta mayor','Sirve el pollo en un plato hondo, con repollo muy fino o cocido ligeramente y la salsa de aguacate por encima, y con tortillas cortadas en pedacitos si masticar le cuesta.']],
 store:'Pollo: 4 días en la nevera con un poco de caldo; recalienta en sartén 3 minutos. Camarones: 2 días, mejor fríos sobre ensalada porque recalentados se ponen gomosos. Repollo: 3 días. Salsa de aguacate: 1 día con film pegado a la superficie y un chorrito extra de limón. Tortillas: se calientan al momento.',
 swaps:['Tortilla de maíz → tortilla integral pequeña o hojas de lechuga romana (versión sin tortilla).','Pollo → tofu desmenuzado y sazonado igual, o frijoles negros machacados.','Yogur griego → crema agria ligera o más aguacate con agua.','Repollo morado → repollo verde con una cda. de zanahoria rallada.']},

// ───────────────────────────── 4. POKE BOWL ─────────────────────────────
{id:'poke_bowl',meal:'Almuerzo',cuisine:'Asiática',img:'poke_bowl',
 title:'Poke bowl con arroz integral, edamame y salsa de soya con jengibre',
 sub:'Un bowl fresco y colorido con arroz integral, edamame, pepino, zanahoria y aguacate, aliñado con una salsa de soya, jengibre y sésamo. Puedes elegir tofu, pollo o pescado fresco.',
 prep:25,cook:45,total:70,base:4,
 variants:[
  {id:'tofu',label:'Tofu marinado',sub:'Vegana',kcal:520,p:23,c:58,f:22,d:'Tofu extra firme prensado, marinado y dorado. Vegana de verdad.'},
  {id:'pollo',label:'Con pollo',sub:'Sin mariscos',kcal:545,p:39,c:55,f:19,d:'Cubos de pechuga marinados y salteados.'},
  {id:'salmon',label:'Salmón o atún',sub:'Con pescado',sea:1,kcal:545,p:30,c:55,f:23,d:'Cubos de pescado fresco de grado sushi, o sellados si lo prefieres cocido.'}],
 groups:[
  {g:'Arroz integral',items:[
   ['arroz',1,'taza',190,'g','arroz integral de grano corto o mediano','arroz integral','Enjuágalo bajo agua fría.'],
   ['agua_a',2,'taza',475,'ml','agua','agua'],
   ['sal_a',.25,'cdta',1.5,'g','sal fina','sal fina'],
   ['vinagre_r',1,'cda',15,'ml','vinagre de arroz sin azúcar','vinagre de arroz','Para sazonar el arroz ya cocido.']]},
  {g:'Proteína',items:[
   ['tofu',14,'oz',400,'g','tofu extra firme','tofu','Elige el de textura más firme; el suave se deshace.',['tofu']],
   ['pollo',1,'lb',450,'g','pechuga de pollo sin piel ni hueso','pechuga de pollo','Aplánala un poco y córtala en cubos parejos de 2 cm (¾ in).',['pollo'],.25],
   ['salmon',.75,'lb',340,'g','filete de salmón o atún fresco, sin piel ni espinas','salmón o atún','Solo si es de grado sushi/sashimi y está recién comprado; guárdalo frío hasta usarlo.',['salmon'],.25],
   ['aceite_n',1,'cda',15,'ml','aceite neutro (canola, girasol o aguacate)','aceite neutro','Para dorar.',['tofu','pollo']]]},
  {g:'Salsa de soya y jengibre',items:[
   ['soya',4,'cda',60,'ml','salsa de soya baja en sodio','salsa de soya','Verifica que diga sin gluten si alguien lo requiere.'],
   ['vinagre',2,'cda',30,'ml','vinagre de arroz','vinagre de arroz'],
   ['sesamo_a',1,'cda',15,'ml','aceite de sésamo tostado','aceite de sésamo','Su aroma es muy intenso: no lo calientes.'],
   ['jengibre',1,'cda',6,'g','jengibre fresco rallado','jengibre','Pela la raíz con el borde de una cuchara y rállala fina.'],
   ['ajo',1,'',3,'g','diente~s de ajo','diente~s de ajo','Rallado fino.'],
   ['sirope',1,'cda',20,'ml','sirope de arce (o de agave)','sirope de arce','Mantiene la receta vegana.'],
   ['lima',1,'cda',15,'ml','jugo de lima fresco','jugo de lima']]},
  {g:'Toppings',items:[
   ['edamame',1.5,'taza',225,'g','edamame desgranado (sin vaina), congelado está bien','edamame','Sin descongelar; hierve directo.'],
   ['pepino',1,'',300,'g','pepino inglés','pepino','En medias lunas finas de 3 mm.'],
   ['zanahoria',2,'',180,'g','zanahoria~s mediana~s','zanahoria~s','Rallada gruesa.'],
   ['cebolleta',3,'',45,'g','tallo~s de cebollín o cebolleta','cebollín','En rodajas finas en diagonal.'],
   ['aguacate',1,'',120,'g','aguacate~s Hass mediano~s (unos 120 g de pulpa)','aguacate','Córtalo al final para que no se oscurezca.'],
   ['sesamo',2,'cda',18,'g','semillas de sésamo','semillas de sésamo','Tostadas en seco 2 minutos para que aromaticen.']]}],
 steps:[
  {t:'Cocina el arroz integral',time:'50 min, casi sin esfuerzo',timer:2400,
   x:`Enjuaga {arroz} bajo agua fría hasta que el agua salga casi transparente. En una olla con tapa ajustada hierve {agua_a} con {sal_a}, agrega el arroz, tapa y baja el fuego al mínimo. Cocina 40 minutos sin destapar. Apaga y deja tapado 10 minutos. Pásalo a un bowl, esponja con un tenedor, agrega {vinagre_r} y deja entibiar.`,
   cue:'Los granos están hinchados y tiernos, con un ligero mordisco; no queda agua en el fondo.',
   warn:'No destapes la olla mientras cocina: el vapor se escapa y el arroz queda duro.'},
  {t:'Prepara la salsa',time:'5 min',
   x:`En un frasco con tapa mezcla {soya}, {vinagre}, {sesamo_a}, {jengibre}, {ajo}, {sirope} y {lima}. Cierra y agita 15 segundos. Divide la salsa en dos: una mitad en un bowl para marinar y la otra mitad en el frasco, limpia y reservada para aliñar el bowl.`,
   cue:'La salsa debe oler a jengibre y sésamo, ser salada y ligeramente dulce.',
   warn:'Nunca uses como aderezo la salsa que tocó el pollo o el pescado crudo: por eso se divide antes de marinar.'},
  {t:'Presiona y marina el tofu',time:'20 min',v:['tofu'],timer:1200,
   x:`Escurre {tofu}, envuélvelo en un paño limpio y ponlo sobre un plato; encima coloca un peso (por ejemplo, una sartén con dos latas) durante 15 minutos. Corta el tofu en cubos de 2 cm (¾ in) y mézclalo con la mitad de la salsa. Déjalo marinar 5–10 minutos mientras el arroz termina de cocinarse.`,
   cue:'Al apretar el paño ya sale poca agua y el tofu se siente firme, no esponjoso.'},
  {t:'Corta y marina el pollo',time:'20 min',v:['pollo'],timer:1200,
   x:`Seca {pollo} con papel de cocina y córtalo en cubos de 2 cm (¾ in). Mézclalo en un bowl con la mitad de la salsa. Tapa y refrigera 15–20 minutos (máximo 2 horas).`,
   cue:'Los cubos son del mismo tamaño y están bien cubiertos de salsa.',
   warn:'Seguridad: marina siempre en la nevera y lávate manos y tabla después de tocar el pollo crudo.'},
  {t:'Corta y marina el pescado',time:'15 min',v:['salmon'],timer:600,
   x:`Seca {salmon} con papel y córtalo con un cuchillo bien afilado en cubos de 2 cm (¾ in), sin aplastar. Mézclalo con la mitad de la salsa y refrigera 10 minutos (no más: la soya y la lima cambian la textura del pescado).`,
   cue:'Los cubos se ven brillantes y firmes, con el color profundo del pescado fresco y un olor limpio a mar, nunca fuerte ni a amoníaco.',
   warn:'Pescado crudo: usa solo pescado de grado sushi/sashimi y mantenlo frío. Personas mayores, niños pequeños, embarazadas o con defensas bajas deben comerlo cocido (paso siguiente).'},
  {t:'Dora el tofu',time:'10 min',v:['tofu'],timer:600,
   x:`Calienta {aceite_n} en una sartén antiadherente grande a fuego medio-alto. Escurre el tofu (guarda la marinada) y cocínalo en una sola capa 2–3 minutos por lado, volteando sus cuatro caras, hasta que esté dorado y con una costra firme. En el último minuto agrega 2 cdas. de la marinada para glasearlo, sin dejar de mover.`,
   cue:'Los cubos están dorados y firmes, se mueven sueltos en la sartén y la salsa se vuelve brillante.'},
  {t:'Cocina el pollo',time:'10 min',v:['pollo'],timer:600,
   x:`Calienta {aceite_n} en una sartén grande a fuego medio-alto. Escurre el pollo y desecha la marinada. Cocina los cubos en una sola capa 8–10 minutos, volteándolos cada 2 minutos, hasta que estén dorados por todos lados. Déjalos reposar 3 minutos.`,
   cue:'Los cubos están dorados y al partir uno el interior es blanco, sin zonas rosadas.',
   warn:'Seguridad: el centro debe marcar 74 °C (165 °F) con termómetro. No reutilices la marinada como salsa.'},
  {t:'Mantén frío o sella el pescado',time:'5 min',v:['salmon'],
   x:`Si usas pescado de grado sushi, déjalo en el refrigerador hasta el momento de servir. Si prefieres cocerlo (recomendado para personas mayores o vulnerables), calienta una sartén antiadherente a fuego medio-alto, sin aceite, y sella los cubos 1–2 minutos por lado, hasta que estén opacos y firmes. Desecha la marinada.`,
   cue:'Cocido: los cubos se ven opacos y se desmenuzan fácilmente. Crudo: brillante, húmedo y firme al tacto.',
   warn:'Seguridad: el pescado cocido debe alcanzar 63 °C (145 °F) en el centro.'},
  {t:'Cocina el edamame y corta las verduras',time:'12 min',timer:240,
   x:`Hierve agua con sal en una olla pequeña y cocina {edamame} 4 minutos. Escurre y pásalo a un bowl con agua helada para detener la cocción. Mientras, corta {pepino} y {cebolleta}, y ralla {zanahoria}. Tuesta {sesamo} en una sartén seca a fuego medio 2 minutos, moviendo, hasta que huela a nueces.`,
   cue:'El edamame queda de verde intenso, tierno pero con ligera resistencia, y el sésamo se dora sin ponerse oscuro.'},
  {t:'Arma los bowls',time:'8 min',
   x:v=>`Reparte el arroz tibio en {N} bowls. Coloca en secciones el edamame, el pepino, la zanahoria y ${v==='tofu'?'el tofu dorado':v==='pollo'?'el pollo':'el pescado'}. Corta {aguacate} en láminas y agrégalo al final. Aliña con la salsa reservada, espolvorea sésamo y cebollín. Sirve de inmediato.`,
   cue:'Un buen bowl tiene mitad verduras, un cuarto de arroz y un cuarto de proteína, con la salsa en un hilo por encima.'}],
 tools:'Olla con tapa para el arroz, olla pequeña, sartén antiadherente grande, colador, frasco con tapa, cuchillo muy afilado, tabla (separa una para proteína cruda), rallador, termómetro de cocina.',
 tips:[
  ['Arma por partes','El arroz, la salsa, las verduras y la proteína se guardan por separado hasta 3 días. Arma el bowl al servir para que nada se ablande.'],
  ['Tofu que sí se dora','Presiónalo bien y sécalo antes de la sartén. Muy caliente y sin moverlo los primeros 2 minutos, así forma costra en vez de pegarse.'],
  ['Menos sodio','La soya baja en sodio ya ayuda; no añadas sal al arroz si usas mucha salsa. Prueba antes de aliñar todo el bowl.']],
 store:'Arroz: 4 días en la nevera; recalienta con 1 cda. de agua, tapado, 1–2 minutos en el microondas. Tofu y pollo cocidos: 3 días. Pescado crudo: consúmelo el mismo día; cocido, 2 días. Salsa: 5 días en frasco. Aguacate: córtalo al momento.',
 swaps:['Arroz integral → quinoa o arroz de coliflor (para menos carbohidratos).','Edamame → garbanzos o frijoles negros cocidos.','Sirope de arce → miel (deja de ser vegana).','Aguacate → mango en cubos (más dulce y fresco).']},

// ───────────────────────────── 5. PASTA CON ALBÓNDIGAS ─────────────────────────────
{id:'pasta_albondigas_pavo',meal:'Almuerzo',cuisine:'Americana-italiana',img:'pasta_albondigas_pavo',
 title:'Pasta integral con albóndigas al horno y salsa de tomate con vegetales ocultos',
 sub:'Albóndigas tiernas horneadas (sin freír) sobre pasta integral, con una salsa casera de tomate a la que le rallamos zanahoria y calabacín: nadie los nota, pero están ahí.',
 prep:25,cook:40,total:65,base:4,
 variants:[
  {id:'pavo',label:'Con pavo',sub:'Sin mariscos',kcal:540,p:38,c:58,f:17,d:'Albóndigas de pavo molido magro con avena y parmesano.'},
  {id:'lentejas',label:'Lentejas y champiñón',sub:'Vegetariana',kcal:550,p:26,c:80,f:14,d:'Albóndigas de lentejas y champiñones, con huevo y queso. Vegetariana, no vegana.'}],
 groups:[
  {g:'Albóndigas de pavo',v:['pavo'],items:[
   ['pavo',1,'lb',450,'g','pavo molido magro (93 % magro)','pavo molido','Si usas muy magro (99 %), agrega 1 cda. de aceite de oliva a la mezcla para que no queden secas.',null,.25],
   ['avena_p',.33,'taza',30,'g','avena en hojuelas','avena en hojuelas','Une la mezcla; también se puede usar pan rallado integral.'],
   ['leche_p',2,'cda',30,'ml','leche o agua','leche o agua','Para hidratar la avena.'],
   ['huevo_p',1,'',50,'g','huevo~s','huevo','Mediano o grande.',null,1],
   ['parm_p',.25,'taza',25,'g','queso parmesano rallado','parmesano rallado'],
   ['ajo_p',2,'',6,'g','diente~s de ajo','diente~s de ajo','Rallados finos.'],
   ['cebolla_p',.25,'',40,'g','cebolla~s','cebolla','Rallada fina; así no se notan los trozos.'],
   ['perejil_p',2,'cda',8,'g','perejil fresco picado','perejil'],
   ['oregano_p',1,'cdta',1,'g','orégano seco','orégano'],
   ['sal_p',.75,'cdta',4.5,'g','sal fina','sal fina'],
   ['pimienta_p',.25,'cdta',.5,'g','pimienta negra molida','pimienta negra']]},
  {g:'Albóndigas de lentejas y champiñón',v:['lentejas'],items:[
   ['lent',1.5,'taza',300,'g','lentejas pardas cocidas (de lata, enjuagadas y bien escurridas, o cocidas en casa)','lentejas cocidas','Sécalas sobre un paño: si están húmedas, la mezcla queda blanda.'],
   ['champi',8,'oz',225,'g','champiñones frescos, picados muy finos','champiñones','Casi en polvo grueso, a mano o en procesador.'],
   ['aceite_c',1,'cda',15,'ml','aceite de oliva','aceite de oliva','Para saltear los champiñones.'],
   ['avena_l',.67,'taza',60,'g','avena en hojuelas (o pan rallado integral)','avena en hojuelas','Une y absorbe la humedad.'],
   ['huevo_l',1,'',50,'g','huevo~s','huevo','Mediano o grande.',null,1],
   ['parm_l',.25,'taza',25,'g','queso parmesano rallado (o un queso duro vegetariano)','parmesano rallado','El parmesano tradicional usa cuajo animal; busca uno vegetariano si es importante.'],
   ['ajo_l',2,'',6,'g','diente~s de ajo','diente~s de ajo','Rallados finos.'],
   ['cebolla_l',.25,'',40,'g','cebolla~s','cebolla','Rallada fina.'],
   ['perejil_l',2,'cda',8,'g','perejil fresco picado','perejil'],
   ['oregano_l',1,'cdta',1,'g','orégano seco','orégano'],
   ['sal_l',.75,'cdta',4.5,'g','sal fina','sal fina'],
   ['pimienta_l',.25,'cdta',.5,'g','pimienta negra molida','pimienta negra']]},
  {g:'Salsa de tomate con vegetales ocultos',items:[
   ['aceite_s',1,'cda',15,'ml','aceite de oliva','aceite de oliva'],
   ['cebolla_s',1,'',150,'g','cebolla~s amarilla~s mediana~s','cebolla','Rallada o muy picadita.'],
   ['zanahoria',1,'',100,'g','zanahoria~s grande~s','zanahoria','Rallada fina, con el lado fino del rallador.'],
   ['calabacin',1,'',200,'g','calabacín~es mediano~s','calabacín','Rallado fino; exprímelo en un paño para quitarle el agua.'],
   ['ajo_s',3,'',9,'g','diente~s de ajo','diente~s de ajo','Picados finos.'],
   ['pasta_t',2,'cda',32,'g','pasta de tomate','pasta de tomate','Da profundidad y color.'],
   ['tomate',1,'',800,'g','lata~s de tomate triturado (28 oz / 800 g)','tomate triturado','Busca los que solo digan tomate (sin azúcar añadida).'],
   ['agua_s',.5,'taza',120,'ml','agua','agua','Para enjuagar la lata.'],
   ['albahaca_s',1,'cdta',1,'g','albahaca seca','albahaca seca'],
   ['oregano_s',1,'cdta',1,'g','orégano seco','orégano'],
   ['sal_s',.5,'cdta',3,'g','sal fina','sal fina'],
   ['albahaca_f',.25,'taza',10,'g','albahaca fresca rasgada','albahaca fresca','Opcional; al final.']]},
  {g:'Pasta',items:[
   ['pasta',8,'oz',225,'g','pasta integral (penne, espagueti o fusilli)','pasta integral','Elige una de grano corto si hay quien come con dificultad.'],
   ['sal_pasta',2,'cdta',12,'g','sal gruesa para el agua','sal gruesa','Solo una parte se absorbe.'],
   ['parm_serv',2,'cda',12,'g','parmesano rallado para servir','parmesano para servir','Opcional.']]}],
 steps:[
  {t:'Precalienta y prepara las verduras',time:'15 min',timer:600,
   x:`Precalienta el horno a 200 °C (400 °F) con la rejilla en el centro y forra una bandeja grande con papel de horno. Ralla {cebolla_s} (rallador grueso), {zanahoria} (rallador fino) y {calabacin}; exprime el calabacín en un paño limpio para quitarle el agua. Pica {ajo_s}.`,
   cue:'Las verduras rallan en hebras finas, casi como puré seco; así desaparecen en la salsa.'},
  {t:'Sofríe la base y cocina la salsa',time:'30 min',timer:1500,
   x:`En una olla grande o sartén honda calienta {aceite_s} a fuego medio. Agrega la cebolla, la zanahoria y el calabacín con una pizca de sal; cocina 6–7 minutos, moviendo, hasta que se ablanden. Añade el ajo y la {pasta_t}, y cocina 1 minuto. Vierte {tomate} y {agua_s} (enjuagando la lata), y agrega {albahaca_s}, {oregano_s} y {sal_s}. Hierve suave, tapa parcialmente y cocina 25 minutos, moviendo de vez en cuando.`,
   cue:'La salsa se espesa, se oscurece a rojo ladrillo y huele dulce y a tomate cocido; el aceite aparece ligeramente en la superficie.',
   warn:'La salsa salpica al hervir: mantén la tapa parcialmente puesta y usa fuego bajo.'},
  {t:'Mezcla las albóndigas de pavo',time:'10 min',v:['pavo'],
   x:`En un bowl grande mezcla {avena_p} con {leche_p} y deja reposar 5 minutos para que se hidrate. Agrega {huevo_p}, {parm_p}, {ajo_p}, {cebolla_p}, {perejil_p}, {oregano_p}, {sal_p} y {pimienta_p}. Añade {pavo} y mezcla con las manos solo hasta que se integre, unos 30 segundos.`,
   cue:'La mezcla es húmeda, algo pegajosa y se mantiene unida al apretarla; si se pega mucho a las manos, humedécelas con agua.',
   warn:'No amases de más: las albóndigas quedan duras. Lávate las manos y la tabla después de tocar el pavo crudo.'},
  {t:'Prepara las albóndigas de lentejas',time:'15 min',v:['lentejas'],timer:480,
   x:`Calienta {aceite_c} en una sartén grande a fuego medio-alto. Agrega {champi} y cocina 7–8 minutos, moviendo, hasta que suelten el agua y esta se evapore, y se doren. Deja enfriar 5 minutos. En un bowl aplasta {lent} con un tenedor, dejando algunas lentejas enteras. Agrega los champiñones, {avena_l}, {huevo_l}, {parm_l}, {ajo_l}, {cebolla_l}, {perejil_l}, {oregano_l}, {sal_l} y {pimienta_l}, y mezcla bien. Refrigera la mezcla 10 minutos para que se compacte.`,
   cue:'Los champiñones están dorados y secos en la sartén. La mezcla se mantiene unida cuando la aprietas en un puño.',
   warn:'Si la mezcla queda muy blanda, agrega 2 cdas. más de avena; si queda seca, una cucharada de agua.'},
  {t:'Forma y hornea las albóndigas',time:'25 min',timer:1260,
   x:v=>`Con las manos ligeramente mojadas, forma ${v==='pavo'?'unas 24 albóndigas':'unas 20 albóndigas'} de unos 3,5 cm (1½ in) y colócalas sobre la bandeja, separadas. Hornea ${v==='pavo'?'18–20 minutos, hasta que estén doradas por fuera y cocidas por dentro.':'20–22 minutos, voltéalas a los 10 minutos, hasta que estén firmes y doradas.'}`,
   cue:'Doradas por fuera y firmes al presionarlas; al cortar una, no queda nada crudo en el centro.',
   warn:'Seguridad: si son de pavo, el centro debe marcar 74 °C (165 °F) con termómetro. Las de lentejas también deben llegar a 74 °C porque llevan huevo.'},
  {t:'Cocina la pasta',time:'12 min',timer:600,
   x:`Mientras se hornean las albóndigas, hierve 3 L (12 tazas) de agua con {sal_pasta}. Cocina {pasta} según el paquete, restando 1 minuto para que quede al dente. Antes de escurrir, reserva ½ taza (120 ml) del agua de cocción. Escurre sin enjuagar.`,
   cue:'Al morder un trozo, el centro tiene un puntito blanco apenas visible: firme, pero sin sabor a harina cruda.'},
  {t:'Une la salsa y las albóndigas',time:'5 min',timer:300,
   x:`Con licuadora de inmersión, tritura la salsa 3–4 segundos si quieres que los vegetales desaparezcan (es opcional; así queda más lisa). Pasa las albóndigas horneadas a la salsa y cocina a fuego bajo 5 minutos para que absorban sabor. Agrega {albahaca_f}.`,
   cue:'La salsa envuelve las albóndigas y burbujea suavemente.',
   warn:'Si usas licuadora de vaso, hazlo con la salsa tibia, llenando solo la mitad, para evitar salpicaduras calientes.'},
  {t:'Mezcla y sirve',time:'3 min',
   x:`Agrega la pasta a la salsa y mezcla, añadiendo agua de cocción de a cucharadas hasta que la salsa brille y se pegue a la pasta. Reparte en {N} platos hondos, con 5–6 albóndigas por plato, y termina con {parm_serv}.`,
   cue:'La pasta se ve brillante, cubierta de salsa, sin charcos de líquido ni seca.'}],
 tools:'Olla grande para pasta, olla o sartén honda para la salsa, bandeja de horno con papel de horno, rallador, bowl grande, termómetro de cocina, licuadora de inmersión (opcional), colador.',
 tips:[
  ['Vegetales que no se notan','Ralla fino y exprime el calabacín: así no suelta agua ni se ve. La zanahoria endulza la salsa y no hace falta azúcar.'],
  ['Albóndigas jugosas','No amases la mezcla y no las hornees de más. Si usas pavo muy magro, el aceite de oliva en la mezcla ayuda a que queden tiernas.'],
  ['Prepara el doble','Forma el doble de albóndigas y congela la mitad ya horneadas en una bandeja: en bolsa, duran 3 meses y se recalientan directo en la salsa.']],
 store:'Salsa: 5 días en la nevera o 3 meses en el congelador. Albóndigas: 4 días en la nevera, 3 meses congeladas; recalienta en la salsa a fuego bajo 8–10 minutos hasta que humeen (74 °C / 165 °F). Pasta cocida: guarda aparte con 1 cdta. de aceite, hasta 4 días.',
 swaps:['Pasta integral → pasta de lentejas o garbanzos (más proteína) o espagueti de calabacín.','Pavo → pollo molido o carne de res magra (cocina a 71 °C / 160 °F).','Avena → pan rallado integral o galletas de soda molidas.','Parmesano → pecorino o levadura nutricional (para quitar el lácteo).']},

// ───────────────────────────── 6. SOPA DE POLLO CON VERDURAS ─────────────────────────────
{id:'sopa_pollo_verduras',meal:'Almuerzo',cuisine:'Latina casera',img:'sopa_pollo_verduras',
 title:'Sopa de pollo con verduras, papa, maíz y cilantro',
 sub:'El caldo de pollo de toda la vida: dorado, con zanahoria, papa, mazorca y arroz, terminado con cilantro y limón. Reconfortante, saciante y fácil de comer.',
 prep:20,cook:55,total:75,base:4,
 variants:[
  {id:'pollo',label:'Con pollo',sub:'Sin mariscos',kcal:500,p:40,c:65,f:9,d:'Pechuga cocida en el caldo y desmenuzada.'},
  {id:'pescado',label:'Con pescado blanco',sub:'Con pescado',sea:1,kcal:465,p:35,c:65,f:7,d:'Trozos de pescado blanco que se cocinan al final, solo 6–8 minutos.'}],
 groups:[
  {g:'Caldo base',items:[
   ['aceite',1,'cda',15,'ml','aceite de oliva','aceite de oliva'],
   ['cebolla',1,'',150,'g','cebolla~s amarilla~s mediana~s','cebolla','En cubos de 5 mm (¼ in).'],
   ['ajo',3,'',9,'g','diente~s de ajo','diente~s de ajo','Picados finos.'],
   ['apio',2,'',100,'g','tallo~s de apio','tallo~s de apio','En medias lunas finas.'],
   ['zanahoria',3,'',270,'g','zanahoria~s mediana~s','zanahoria~s','En rodajas de 1 cm (⅜ in).'],
   ['tomillo',1,'cdta',1,'g','tomillo seco','tomillo','Opcional; unas ramitas frescas también sirven.'],
   ['laurel',2,'',1,'g','hoja~s de laurel','hoja~s de laurel'],
   ['caldo',8,'taza',1900,'ml','caldo de pollo bajo en sodio (o agua)','caldo de pollo','Si usas agua, necesitarás más sal al final.',['pollo']],
   ['caldo',8,'taza',1900,'ml','caldo de verduras bajo en sodio (o agua)','caldo de verduras','Evita el caldo de pollo en la versión con pescado: tapa su sabor.',['pescado']],
   ['sal',1,'cdta',6,'g','sal fina','sal fina','Ajústala al final.']]},
  {g:'Proteína',items:[
   ['pollo',1.25,'lb',565,'g','pechuga de pollo sin piel ni hueso (o muslos deshuesados)','pechuga de pollo','Si una pieza es muy gruesa, córtala a lo largo en dos.',['pollo'],.25],
   ['pescado',1.25,'lb',565,'g','filetes de pescado blanco firme (tilapia, merluza, bacalao o mero), sin espinas','pescado blanco','Cortado en trozos de 3–4 cm (1¼–1½ in). Revisa que no queden espinas con los dedos.',['pescado'],.25]]},
  {g:'Verduras y arroz',items:[
   ['papa',1.5,'lb',680,'g','papa~s amarilla~s o blancas','papas','En cubos de 2,5 cm (1 in), sin pelar si la cáscara es fina.',null,.25],
   ['mazorca',2,'',500,'g','mazorca~s de maíz tierno','mazorcas de maíz','Cortadas en rodajas de 4 cm (1½ in).'],
   ['arroz',.5,'taza',95,'g','arroz blanco','arroz','Enjuagado hasta que el agua salga casi clara. Si usas integral, cocínalo aparte.'],
   ['calabacin',1,'',200,'g','calabacín~es mediano~s','calabacín','Opcional; en medias lunas de 1 cm (⅜ in). Se agrega al final.']]},
  {g:'Para terminar',items:[
   ['cilantro',.5,'taza',25,'g','cilantro fresco picado','cilantro','Hojas y tallos tiernos.'],
   ['jugo',3,'cda',45,'ml','jugo de lima o limón','jugo de lima'],
   ['pimienta',.5,'cdta',1,'g','pimienta negra molida','pimienta negra']]}],
 steps:[
  {t:'Corta las verduras',time:'15 min',
   x:`Corta {cebolla}, {apio} y {zanahoria} como se indica en la lista; pica {ajo}. Corta {papa} en cubos de 2,5 cm (1 in) y colócalos en un bowl con agua fría para que no se oscurezcan. Corta {mazorca} en rodajas de 4 cm (1½ in) con un cuchillo grande, sobre una tabla estable. Enjuaga {arroz} en un colador hasta que el agua salga casi clara.`,
   cue:'Los cortes parejos aseguran que todo termine de cocinarse a la vez.',
   warn:'Las mazorcas son duras: apoya la parte plana sobre la tabla, sujeta con una toalla y corta con firmeza y la mano plana lejos del filo.'},
  {t:'Sofríe la base',time:'8 min',timer:420,
   x:`En una olla grande (5 L / 5 qt) calienta {aceite} a fuego medio. Agrega la cebolla, el apio, la zanahoria y una pizca de la {sal}; cocina 5 minutos, moviendo, hasta que la cebolla esté translúcida. Añade el ajo, {tomillo} y {laurel}, y cocina 1 minuto más.`,
   cue:'La cebolla está suave y brillante, sin dorar, y la cocina huele a sofrito.',
   warn:'Si el ajo toma color marrón oscuro, huele amargo: baja el fuego y agrega 2 cdas. de caldo.'},
  {t:'Cocina el pollo en el caldo',time:'20 min',v:['pollo'],timer:1200,
   x:`Vierte {caldo} y sube el fuego hasta que hierva. Agrega {pollo} entero, baja el fuego a medio-bajo, tapa parcialmente y cocina a hervor suave 18–20 minutos, hasta que no quede nada rosado. Retira el pollo a un plato y déjalo reposar 5 minutos; luego desmenúzalo con dos tenedores.`,
   cue:'El caldo está ligeramente dorado, sin hervir fuerte. Al pinchar el pollo, sale jugo transparente.',
   warn:'Seguridad: la parte más gruesa debe marcar 74 °C (165 °F) con termómetro. Retira la espuma gris que sube a la superficie.'},
  {t:'Lleva el caldo a hervor',time:'8 min',v:['pescado'],timer:420,
   x:`Vierte {caldo} y sube el fuego hasta que hierva. Baja a fuego medio-bajo, tapa parcialmente y deja hervir suave 5–7 minutos para que el caldo tome el sabor del sofrito.`,
   cue:'El caldo huele a verduras y hierba, y está ligeramente dorado.'},
  {t:'Cocina las verduras y el arroz',time:'18–20 min',timer:1080,
   x:`Escurre las papas y agrégalas junto con {mazorca} y {arroz}. Cocina a hervor suave, con la tapa parcialmente puesta, 15–18 minutos, moviendo una o dos veces para que el arroz no se pegue.`,
   cue:'Un cubo de papa se atraviesa fácilmente con un tenedor, el arroz está hinchado y los granos de maíz se ven brillantes.',
   warn:'Si el caldo se evapora mucho y la sopa queda muy espesa, agrega ½ taza (120 ml) de agua caliente.'},
  {t:'Termina el pollo',time:'5 min',v:['pollo'],timer:180,
   x:`Devuelve el pollo desmenuzado a la olla y cocina 3 minutos para que se caliente por completo y absorba sabor. Agrega {calabacin} si lo usas, y cocina 2 minutos más.`,
   cue:'El pollo se ve jugoso en el caldo y el calabacín conserva un ligero mordisco.'},
  {t:'Cocina el pescado al final',time:'8 min',v:['pescado'],timer:420,
   x:`Baja el fuego a bajo. Agrega {calabacin} si lo usas y cocina 2 minutos. Seca los trozos de {pescado} con papel y colócalos con cuidado en el caldo. Tapa y cocina 6–7 minutos sin mover la olla (si lo mueves, se desmenuzan), hasta que estén opacos y se separen en lascas.`,
   cue:'El pescado cambia de translúcido a blanco opaco y se separa en capas al presionarlo con un tenedor.',
   warn:'Seguridad: el pescado debe alcanzar 63 °C (145 °F) en el centro. Si queda alguna parte translúcida, cocina 1–2 minutos más.'},
  {t:'Termina con cilantro y limón',time:'3 min',
   x:`Retira el laurel. Apaga el fuego y agrega {cilantro}, {jugo} y {pimienta}. Prueba el caldo, ajusta la sal si hace falta y deja reposar tapada 3 minutos.`,
   cue:'El limón al final “despierta” el caldo: debe saber a pollo o verduras, con un toque cítrico fresco.'},
  {t:'Sirve',time:'3 min',
   x:`Reparte la sopa en {N} platos hondos calientes, con una buena cantidad de caldo, verduras y proteína en cada uno. Sirve con una cuña de lima y, si lo deseas, un poco más de cilantro.`,
   cue:'Debe servirse bien caliente, pero espera 2 minutos antes de comer para no quemarte.',
   warn:'Para la adulta mayor, sírvele la sopa tibia, con la papa y el pollo en trozos pequeños, y desgrana el maíz de la mazorca.'}],
 tools:'Olla grande (5 L / 5 qt) con tapa, tabla grande estable, cuchillo de chef, colador, cucharón, dos tenedores, termómetro de cocina.',
 tips:[
  ['Caldo más claro','Retira la espuma gris de la superficie con una cuchara durante los primeros 5 minutos de hervor y no dejes que hierva con fuerza: así queda claro y limpio.'],
  ['Arroz y papa','La papa y el arroz siguen absorbiendo caldo. Si cocinas con anticipación, agrega ½ taza (120 ml) de agua o caldo al recalentar.'],
  ['Más fácil de comer','Para quien le cuesta masticar, corta la papa en cubos pequeños, usa pollo bien desmenuzado y retira el maíz de la mazorca.']],
 store:'Sopa de pollo: 4 días en la nevera tapada o 3 meses en el congelador (sin el calabacín, que se ablanda de más). Recalienta a fuego medio hasta que hierva suavemente (74 °C / 165 °F). Sopa de pescado: 2 días; recalienta a fuego bajo sin remover mucho para que no se deshaga.',
 swaps:['Papa → camote o yuca (cocina un poco más).','Arroz blanco → fideos finos o quinoa.','Mazorca → 1½ tazas (225 g) de granos de maíz congelados.','Pollo → pavo en trozos, o garbanzos cocidos para una versión vegetariana (con caldo de verduras).']}
];
